### ISSUE TITLE
Problem with GooglePay

### ISSUE THREAD

**Issue by udongeex** [stripe/stripe-terminal-android#104]
I'm trying to test with GooglePay on the example app, I just want to get the response even if it false. But it keep repeat Swipe/Insert/Tap messages, sometime "Multiple Contactless Cards Detected" (I did make sure remove all card except one).

![Capture](https://user-images.githubusercontent.com/29280577/77251021-70100a80-6c7e-11ea-9fa2-ff0c15551e90.PNG)

**Comment by corin-stripe** [comment]
Hi @udongeex, sorry for the delayed response - we've been very busy but are doing our best to prioritize these issues. Can you share a few more details to help us try to reproduce your issue? What kind of device are you running the point of sale software on? And what kind of device are you using for Google Pay? Any additional detail you can provide (SDK version, Android API version, etc) would be super helpful as well.

**Comment by billfinn-stripe** [comment]
Closing this issue. Feel free to reopen if you are able to provide a minimal reproducible example.
