### ISSUE TITLE
Terminal#createPaymentIntent is not observing the description param

### ISSUE THREAD

**Issue by rscherf** [stripe/stripe-terminal-android#112]
## Summary
The `description` parameter is not passed along via the SDK to Stripe. Although I am setting it via the `PaymentIntentParameters` builder, I cannot seem to get it to persist at Stripe. The PaymentIntent succeeds, but `description` is ignored. This behavior works properly 

## Code to reproduce
```Java
PaymentIntentParameters params = new PaymentIntentParameters.Builder()
        .setAmount(7777)
        .setDescription("Charge Desc")
        .setCurrency("usd")
        .build();

Terminal.getInstance().createPaymentIntent(params, new PaymentIntentCallback() { ... })
```
Here is a TEST mode request, which shows `description` as `null`. `req_LkDIGwE4APei9x`

## Android version
compile/target sdk version: 28

## Impacted devices
Samsung Galaxy Note 5 and Simulator are the only devices tested to date.

## Installation method
Sync via Maven & Gradle

## SDK version
`stripe-android 14.4.1`
`stripe-terminal 1.0.0-b7` (have not updated due to other conflicts in app outlined in #113 )

## Other information
Obviously these requests proxy through my backend, then to Stripe, however I've confirmed that my backend receives the `description` param from my client, and sends it along to the Stripe API. All other `PaymentIntentParameters` are observed.

**Comment by corin-stripe** [comment]
hey @rscherf, me again. I took a look at that request and I do see the missing `description` param, sorry you're running into this! Same story as the other issue, @chander-stripe will look into it as soon as he can, right after July 4. Thanks again for your detailed report and patience, we really appreciate both.

**Comment by rscherf** [comment]
@corin-stripe No worries!

**Comment by chander-stripe** [comment]
Ok taking a look at this now - I'm not able to repro w/ the latest verison of the sdk (1.0.17), and unfortunately our release process doesn't really allow us to backport fixes to older versions.

Sounds like #113 is the real bug here, so let me check out that one instead. (Lemme know if anything I said is totally wrong @rscherf )

**Comment by rscherf** [comment]
@chander-stripe sounds right to me. I figured this was already fixed in the later versions of the SDK, but as you stated, I ran into #113 and just abandoned completely for a bit. Once #113 is fixed, I'll go ahead and see if that resolved both issues.
