### ISSUE TITLE
Did not work with QPOS30.52-29-5 build maxSDK 29 was changed to 30 and keep crash

### ISSUE THREAD

**Issue by malkahtani** [stripe/stripe-terminal-android#117]
## Summary

It says sdk 24 and above.
Crash

build Warring

DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.

## Android version

10 Q SDK 29
## Impacted devices (Android devices or readers)

Did not work crash
## SDK version

29

**Comment by chander-stripe** [comment]
Hi @malkahtani - the build warning `DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.` shouldn't cause a crash.

Do you have a full stack trace that you ran into?

**Comment by chander-stripe** [comment]
Closing due to lack of response.
