### ISSUE TITLE
Canceling software update does not work

### ISSUE THREAD

**Issue by r-grabowski** [stripe/stripe-terminal-android#119]
## Summary
Canceling software update does not work in Example project.
Looks like callback is not called and OTA update is not terminated after cancel call

## Android version
tested on Android 8 and 10

## Impacted devices (Android devices or readers)
Physical devices and emulator

## SDK version
implementation "com.stripe:stripeterminal:1.0.17"

**Comment by billfinn-stripe** [comment]
@r-grabowski -- we've released 2.0.0 which we believe fixes this issue. I'm going to optimistically close this issue, but feel free to re-open or raise a new one if you are still encountering problems.
