### ISSUE TITLE
Reader battery level changes

### ISSUE THREAD

**Issue by r-grabowski** [stripe/stripe-terminal-android#120]
## Summary
Is it possible to follow the reader battery level change in real time?
It seems that there is only static battery level value after connection succeeded.
I also did not find any property whether the battery is charging or not.
Same on iOS SDK

**Comment by danwaters-stripe** [comment]
We're currently looking into this, and are hoping to have it in a future release. We'll update this issue when we have a better idea of a timeline!

**Comment by msoliman22** [comment]
Hello, do we have updates about this feature , so I want to let the user know if the battery is low

**Comment by chr-stripe** [comment]
When you call `Terminal.connectBluetoothReader()` or `Terminal.connectUsbReader()`, you can provide a [`ReaderListener`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/index.html) implementation which allows you to accept callbacks for two different battery-related events:
- [`onBatteryLevelUpdate`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/on-battery-level-update.html): The Terminal reports batteryLevel, [BatteryStatus](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-battery-status/index.html) and charging status every 10 minutes
- [`onReportLowBatteryWarning`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/on-report-low-battery-warning.html): The Terminal reported that the reader's battery level is low
