### ISSUE TITLE
SDK version 1.0.18: Terminal.getInstance().connectReader onSuccess callback does not called

### ISSUE THREAD

**Issue by xxllexx** [stripe/stripe-terminal-android#131]
## Summary
`Terminal.getInstance().connectReader` onSuccess callback does not called, and connection failed with timeout even for simulated Reader. At the same time `TerminalListener.onConnectionStatusChange` recieve status `ConnectionStatus.CONNECTING` and then `ConnectionStatus.CONNECTED`. 
In case of triggering some additional actions with the "connected" reader (eg: Payment process), SDK fails with an error 
` UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR: Operation in progress wasn't completed before starting new operation`

## Code to reproduce

```
Terminal.getInstance().connectReader(reader, object : ReaderCallback {
      override fun onSuccess(reader: Reader) {
         //any code here won't work
      }
      override fun onFailure(e: TerminalException) {
         //will get her with timeout
      }
    })
```

## Android version
10, 11 

## SDK version
com.stripe:stripeterminal:1.0.18

**Comment by billfinn-stripe** [comment]
Hi @xxllexx -- have you tried running the example app? Locally, I am able to see the `onSuccess` callback fire:

https://github.com/stripe/stripe-terminal-android/blob/8778d1ac0ea406588756411d570dd6a7b565316b/Example/kotlinapp/src/main/java/com/stripe/example/fragment/discovery/ReaderClickListener.kt#L17-L35

**Comment by xxllexx** [comment]
Hi @billfinn-stripe, You are right, this is local issue with React-Native wrapper. Sorry for false alarm and thanks for your help
