### ISSUE TITLE
"com.stripe:stripeterminal:2.0.0-b3" Could not find com.stripe.terminal.updater:core:

### ISSUE THREAD

**Issue by toanabacus** [stripe/stripe-terminal-android#132]
By upgrading from "com.stripe:stripeterminal:2.0.0-b2" to "com.stripe:stripeterminal:2.0.0-b3". The app can build but can not run and got the following message:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.stripe.terminal.updater:core:.
     Required by:
         project :app > com.stripe:stripeterminal:2.0.0-b3

**Comment by billfinn-stripe** [comment]
Hi @toanabacus -- thanks for bringing this to our attention. We've updated the b3 artifacts to remove the missing dependency -- can you try again? You may need to invalidate your local cache.

**Comment by toanabacus** [comment]
HI @billfinn-stripe , I'm still getting the issue with 
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.stripe.terminal.updater:core:.
     Required by:
         project :app > com.stripe:stripeterminal:2.0.0-b3

I've "Invalidate Cache & Restart" also. 
Additionally, may I ask about this new SDK if it still have the conflict issue with Google Firebase Libraries as of b1 and b2?

**Comment by billfinn-stripe** [comment]
Hi @toanabacus -- unfortunately, I don't think Android Studio's "Invalidate Cache & Restart" properly invalidates all cached artifacts from gradle's cache. 

Can you try `./gradlew --refresh-dependencies`?

If that doesn't work, can you try manually removing your gradle cache? Something like `rm -rf ~/.gradle/caches/`? Note that your next build will take extra time, as gradle rebuilds your local cache.

See also https://stackoverflow.com/a/23029580/584663.

**Comment by billfinn-stripe** [comment]
Regarding:
> Additionally, may I ask about this new SDK if it still have the conflict issue with Google Firebase Libraries as of b1 and b2?

Yes, this version still has the protobuf conflict issue with Google Firebase.

**Comment by toanabacus** [comment]
Ah, may I know when the issue will be resolved sometime early in the future? and Also if you have any work around on it during the waiting time?

**Comment by billfinn-stripe** [comment]
Hi @toanabacus -- unfortunately, we currently don't have a timeline for resolving the protobuf conflict nor do we have a workaround at the moment.

**Comment by billfinn-stripe** [comment]
@toanabacus -- I believe the original issue is resolved, so I'm going to close this issue. Feel free to open a new issue with details re: the protobuf collision errors you're seeing.
