### ISSUE TITLE
ANR or OnSuccess returned when a reader disconnects during a software update

### ISSUE THREAD

**Issue by malinajirka** [stripe/stripe-terminal-android#134]
## Summary
When a reader unexpectedly disconnects while a software update is in progress one of the following happens
1. The application freezes -> ANR.
2. onSuccess is returned.

I believe neither of the results is expected. I'd expect the app not to freeze and invoke "Callback.onError(..)" since the update failed.

To test:
1. Connect to a hw reader (not a simulated reader) in the sample app
2. Tap on "Update reader software"
3. Tap on "Check for update" and wait
4. Tap on "Install update"
5. When the update progress is greater than 0% manually turn off the reader
6. Notice that sometimes the app freezes and sometimes "onSuccess" is invoked

## Code to reproduce
Sample app - AFAICT happens even in other apps using the SDK.

## Android version
Android 11

## SDK version
1.0.18

**Comment by billfinn-stripe** [comment]
Hi @malinajirka -- thanks for the detailed bug report. We're currently working on a 2.x release of the SDK. I've tested the same scenario that you've described, and the SDK behaves as expected. The update installation procedure is managed slightly differently in 2.x, and we'll include a migration guide when we publish 2.x.

I'll leave this issue open until we release 2.x.

**Comment by billfinn-stripe** [comment]
Hi @malinajirka -- we have released version 2.0.0, and I believe this problem should be resolved. I'm going to optimistically close this issue, but feel free to re-open or raise a new one if you are still encountering problems.
