### ISSUE TITLE
Update fails with `low battery` error even when the reader is charging

### ISSUE THREAD

**Issue by malinajirka** [stripe/stripe-terminal-android#141]
## Summary
I'm not able to connect to a reader in the sample app as the reader is not up to date and it keeps failing with "Update failed due to low battery on the reader" error even when the reader is charging. I'd expect to be able to update the reader and connect to it when it's charging even when the current state of the battery is low.

## Code to reproduce
The sample app

## Android version
11

## Impacted devices (Android devices or readers)
Tested with BBPOS Chipper 2X BT

## SDK version
2.0.0

**Comment by jayjah** [comment]
@malinajirka The reader needs at least 50% battery to allow an update.

**Comment by malinajirka** [comment]
I'd expect it to work when the charger is attached. Otherwise, the merchant might not be able to accept a payment if there is a required update available and their reader is not charged. Wdyt?

**Comment by jayjah** [comment]
@malinajirka Well, that's actually the case, as far as I know. The merchant is responsible to have a charged and an up-to-date card reader.

**Comment by rv-stripe** [comment]
Unfortunately, having the reader plugged in still poses a risk during updates should the charger be disconnected after the update starts. 
This is why applying an update requires the battery at this minimum threshold, as a power loss during this update can cause the reader to become entirely inoperable.
Closing this issue out - but please reply with any additional questions information that you may have.
