### ISSUE TITLE
Unable to discover reader when minifyEnabled and shrinkResources are enabled

### ISSUE THREAD

**Issue by matejkramny** [stripe/stripe-terminal-android#142]
## Summary

Hello, we found a strange issue. The SDK cannot find any bluetooth readers (wisepad3 specifically, haven't tested others). I've traced this down to a setting in build.gradle, as outlined below.

## Code to reproduce

in build.gradle

```
android {
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
        }
}
```

If you then build for release it will appear working, but will never find a terminal. If you disable the minify and shrink flags, the sdk starts working.

## Android version

10-11

## Impacted devices (Android devices or readers)

Wisepad3, all androids AFAIK

## SDK version

2.0.0. Observed from 2.0.0-beta2

## Other information

Submitted a bug report to stripe (via email) but it may not have reached the right team

**Comment by billfinn-stripe** [comment]
Hi @matejkramny -- can you include the log output and what you mean by not being able to find any Bluetooth readers? Do you call `discoverReaders`, and none of your `DiscoveryListener.onUpdateDiscoveredReaders`, `Callback.onSuccess` nor `Callback.onFailure` is called?

**Comment by matejkramny** [comment]
Hey, @billfinn-stripe. Nothing changed except for those flags

It does call Discover readers (as it works with the flags off). I made a demo project (https://github.com/matejkramny/stripe-terminal-bug-2), if that's of any use. It might need migrating from the beta library

Will send the logs over the weekend hopefully

Thanks

**Comment by matejkramny** [comment]
To answer your other question.

Consider a project (the stripe demo f.e.) where Discover readers usually finds a nearby reader if it's on etc.
With those gradle flags set as true (and no other changes) - this no longer works. I don't think the flags work for builds outside release/profile btw, so any testing should target release builds to validate.

I am suspecting it's something related to R8 or proguard, and it might be stripping some of the stripe code (??). I'm not able to / willing to deep dive into compiled code to figure out what and why is missing when these flags are on.
Tried setting proguard rules to ignore stripe libraries, to no avail.

**Comment by mattjamesaus** [comment]
We're seeing the exact same with our build. Works when in debug mode but release just doesn't return any readers..

We're going to take a deeper look over the next few days and can report back if we find the problem.

**Comment by dhenry-stripe** [comment]
Hi @matejkramny, thanks for reporting this. You're correct, Proguard/R8 is being overzealous in its removal of Stripe code. We'll look at bundling keep rules with the SDK. In the meantime though you can work around this by adding the following keep rules to your project:

```
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-dontwarn com.stripe.**
-keep class com.stripe.** { *; }
-keep interface com.stripe.** { *; }

-dontwarn com.google.protobuf.**
-keep class com.google.protobuf.** { *; }
-keep interface com.google.protobuf.** { *; }
```

**Comment by dhenry-stripe** [comment]
Resolved by: https://github.com/stripe/stripe-terminal-android/releases/tag/v2.2.0
