### ISSUE TITLE
WisePad 3 hangs after confirming a contactless Google Pay payment by unlocking the phone

### ISSUE THREAD

**Issue by piotr767** [stripe/stripe-terminal-android#146]
## Summary

When making a contactless Google Pay payment using an Android phone user is sometimes asked to confirm it by unlocking the phone (this behaviour is described here: [Google Pay Help](https://support.google.com/pay/answer/7644132?hl=en&co=GENIE.Platform%3DAndroid&oco=0)).

When this happens during a payment with a WisePad 3 the reader hangs without any logs after I unlock the phone. I use the same Android phone for everyday payments in shops and everything works fine. Contactless payments with a WisePad 3 also work fine unless I'm asked by Google Pay to unlock the phone for confirmation.

## Impacted devices (Android devices or readers)

WisePad 3

## SDK version

2.0.0

**Comment by matejkramny** [comment]
@piotr767 to get it unstuck, do you have to hard reset it (with the pin reset button)?

**Comment by piotr767** [comment]
@matejkramny yes, exactly.

**Comment by rv-stripe** [comment]
I believe this issue was fixed in version 2.4 of the SDK, and does not occur on the latest 2.12
Closing out this older issue - Please re-open if this occurs in newer versions of the SDK.
