### ISSUE TITLE
Currency symbols inconsistency on transaction display

### ISSUE THREAD

**Issue by uncured** [stripe/stripe-terminal-android#147]
## Summary
Devices: Android 11 phone, iOS 12 phone and WisePad 3 EMV
Environment: Connection to EMV is performed using the New Zealand location
When performing the payment collection using the NZ location and NZD currency there is a currency display inconsistency between iOS and Android terminal:
- on iOS the amount on the WisePad display is shown as `Sale NZD10.00`
![image](https://user-images.githubusercontent.com/1299851/127301469-383debdc-9856-4ccb-a9de-ffe009e5fd84.png)
- on Android the amount on the WisePad display is shown as `Sale $20.00` (Don't mind the difference in amount, these are different transactions for different amounts, the issue is only in the currency symbol display)
![image](https://user-images.githubusercontent.com/1299851/127301742-21352c7b-67a1-4ea6-961e-8177efca4ab7.png)

In both cases the payment intent object reported and the Stripe Payments Dashboard correctly have the currency as `NZD`, so the issue is only in how WisePad 3 is displaying the amount.

Same behaviour observed when using the location in Australia and using the `AUD` as a currency

## Code to reproduce
Nothing specific, just start the payment collection with the WisePad 3 EMV

## Android version
Android 11

## Impacted devices (Android devices or readers)
Nothing specific device-related

## SDK version
Android SDK 2.0.0
iOS SDK 2.0.1

## Other information
Nothing

**Comment by chr-stripe** [comment]
Hi @uncured! I just tried the same steps to initiate a $1 NZD payment from the latest Android SDK version (2.12.0) and it seems like it's working as you'd expect now – seeing `NZD1.00` on the WisePad. We'll close this ticket out as it seems to have been resolved in the meantime.
