### ISSUE TITLE
Payment collection timeout inconsistency with iOS SDK

### ISSUE THREAD

**Issue by uncured** [stripe/stripe-terminal-android#148]
## Summary
When starting the payment collection and not providing any input the behaviour for iOS and Android SDK differs:
- on iOS SDK if user don't present the payment collection input when prompted for 5 minutes the collection fails with the error code `SCPErrorCardReadTimedOut = 2830`
- on Android SDK in the same conditions transaction don't fail due to the timeout and user can present the card for payment collection even after 10 minutes of waiting for the input

## Code to reproduce
Nothing special, I assume the sample app RocketRides can be used to replicate the issue during the payment collection stage

## Android version
Android 11

## Impacted devices (Android devices or readers)
Nothing specific

## SDK version
Android SDK 2.0.0
iOS SDK 2.0.1

## Other information
Nothing

**Comment by ball1008** [comment]
Has this been resolved?  We are using Android sdk 2.9 and do not get a timeout when we call collectpaymentmethod.  Is it possible to set a timeout on the sdk call?

**Comment by chr-stripe** [comment]
Thanks for the issue report! We're looking at this discrepancy internally and will update you shortly with the final outcome.

**Comment by chr-stripe** [comment]
After some discussion within the team, I believe we will be altering the iOS timeout behaviour to match Android's. Currently the Android timeout for payment collection is set to **1 hour**, and iOS will be aligning with this value now as well.

While you aren't able to override this timeout in your own applications, you are still able to implement timeouts by cancelling the payment collection when it suits you best. For example, after calling:

```kotlin
val collectTask = Terminal.getInstance().collectPaymentMethod(...)
```

You can save a reference to that task and call `collectTask.cancel(...)` after 5 minutes if you have not received any success/failure within that time in your `PaymentIntentCallback`.
