### ISSUE TITLE
Connection never finishes (deadlock) when reader's battery is almost empty

### ISSUE THREAD

**Issue by malinajirka** [stripe/stripe-terminal-android#159]
## Summary

When reader's battery is almost empty (<1%), then `ReaderCallback` passed to `Terminal.getInstance().connectBluetoothReader` doesn't get invoked - the SDK gets stuck in this state forever.

## Code to reproduce

I was able to reproduce this issue with both SDK v1 and SDK v2 in our app. I've reproduces it also on the current `master` branch of the example app (https://github.com/stripe/stripe-terminal-android/commit/960318dc9dbaa5b89e8ce845d9de0b09c92688f0).

## Android version

Android 11 - I was able to reproduce this on 2/2 devices (Samsung and Pixel)

## Impacted devices (Android devices or readers)

I have tested just the BBPOS Chipper 2X.

## SDK version

2.2.0 (example app) (Also reproduced on 1.0.22)

## Other information

- It works as expected when the battery is around 2% - the issue appears only when the battery is almost empty. 
- I was able to reproduce it +- 30times from 30 attempts == 100%.
- It seems the SDK internally blocks the thread - when I tried to wrap the code in `withTimeout` the cancellation exception doesn't get thrown.
- I noticed that when I manually turn off bluetooth on the device, the SDK gets unstuck - `withTimeout` starts working.
- It seems the CardReader object is in "Connecting" state however, calling disconnect on it doesn't work - at least `connectBluetoothReader` doesn't get unstuck.

**Comment by malinajirka** [comment]
I haven't tested this for quite some time - I usually keep my reader charged. If you can't reproduce it, let's close it and I'll re-open it if we encounter it again. Thanks!

**Comment by chr-stripe** [comment]
Thanks! Please don't hesitate to comment if you do encounter this again.
