### ISSUE TITLE
Issues with onRequestReaderDisplayMessage on SDK 2.x

### ISSUE THREAD

**Issue by vikesh-simplifeye** [stripe/stripe-terminal-android#168]
## Summary
The `onRequestReaderDisplayMessage` doesn't get called after upgrading to SDK 2.x. Further, `collectPaymentMethod` doesn't complete until the card is removed, whereas `onSuccess` or `onFailure` would work in 1.x of the SDK

## Code to reproduce
    public void collectPaymentMethod() {
        pendingCreatePaymentIntent = Terminal.getInstance().collectPaymentMethod(lastPaymentIntent, new PaymentIntentCallback() {
            @Override
            public void onSuccess(@Nonnull PaymentIntent paymentIntent) {
                pendingCreatePaymentIntent = null;
                lastPaymentIntent = paymentIntent;
                /** Show "authorizing" screen and initiate capture in the background **/
            }

            @Override
            public void onFailure(@Nonnull TerminalException e) {
                pendingCreatePaymentIntent = null;
                /** Show failure to authorize funds **/
            }
        });
    }

    public void onRequestReaderDisplayMessage(@Nonnull ReaderDisplayMessage readerDisplayMessage) {
        switch(readerDisplayMessage.name()) {
            case "REMOVE_CARD":
                /** Show "Remove Card" UI **/
                break;
            default:
                /** Show "Try another read method" UI **/
                break;
        }
    }

## Android version
Android 9 & Android 10

## Impacted devices (Android devices or readers)
**Tablets:** Amazon Fire Tablets, Lenovo Tab M8 HD
**Reader:** BBPOS 2X BT

## SDK version
2.3.1

## Other information
N/A

**Comment by dhenry-stripe** [comment]
Okay, thanks for following up @vikesh-simplifeye.
