### ISSUE TITLE
The current Android SDK versions are no longer support insert card before start the payment

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#173]
## Summary

Before SDK 1.0 version, the customer could insert the card before the payment start. But after 2.0 version, customers must insert the card after we start the payment. There are many cases that customer insert the card earlier than payment start and we need to ask them to remove card and restart the payment. Moreover we have to ask customer verbally when they are trying to do so. It sometimes make customer thought the reader is not smart enough.

Could we support customer insert the card before BBPOS get the payment start like the version older than 1.0 SDK? That will helps a lot when our client restaurant facing the high peak time.

## Android version

7 and 9
## Impacted devices (Android devices or readers)

BBPOS
## SDK version

2.0 and newer

**Comment by ohmyleonia** [comment]
![wecom-temp-5cffbc623582831b82a447ffe73e4f52](https://user-images.githubusercontent.com/91237182/139611607-adfa1fd6-9a3b-492a-bfff-4fdc91e4f80c.jpg)
PFA. Many of our customers in U.S used to insert card before payment intention start, but BBPOS always feedback this error and it influence our customer experience a lot. Before SDK 1.0 it won't happened.

**Comment by ohmyleonia** [comment]
> Can you please also provide the error that you're seeing (if any) and a device serial number?
It happens in all our BBPOSs.

**Comment by dhenry-stripe** [comment]
Thanks for reporting @ohmyleonia! We'll have a fix available in the next release.

**Comment by vikesh-simplifeye** [comment]
Our customers have been running into this issue as well. Is there a timeline for the next release?

**Comment by dhenry-stripe** [comment]
@vikesh-simplifeye there is! Version 2.5.0 is scheduled for release on the week of 11/15.

**Comment by dhenry-stripe** [comment]
Resolved in [v2.5.0](https://github.com/stripe/stripe-terminal-android/releases/tag/v2.5.0)
