### ISSUE TITLE
Android Demo cannot connect to WisePOS E device 

### ISSUE THREAD

**Issue by mamw** [stripe/stripe-terminal-android#174]

**Comment by dhenry-stripe** [comment]
Hi @mamw, can you please fill out the template in the issue description including a summary, code to reproduce,the Android version, Impacted devices (Android devices or readers), the SDK version, and any other information you think might be helpful?

**Comment by mamw** [comment]
![image](https://user-images.githubusercontent.com/19991384/140605044-bef0d1c3-d732-47e6-8e05-48f24e1586ab.png)

The android demo Terminal App started，the "DISCOVERY METHOD" cannot be switch to "Intent".

**Comment by dhenry-stripe** [comment]
Thanks @mamw, we'll look into it!

**Comment by dhenry-stripe** [comment]
Internet reader connectivity added to the example apps in [v2.6.0](https://github.com/stripe/stripe-terminal-android/releases/tag/v2.6.0).
