### ISSUE TITLE
Terminal gets stuck when a payment is cancelled

### ISSUE THREAD

**Issue by malinajirka** [stripe/stripe-terminal-android#181]
## Summary

When I tap a card on either M2 or Chipper 2x reader and I cancel the payment flow right after that (before the sdk reaches processing payment state), the SDK returns "Cancelable.onSuccess" but it gets into a weird/stuck state. When I try to collect another payment or the same payment again, the SDK doesn't communicate at all.

## Code to reproduce

The official example app (kotlin version) - commit 92da292cc5857197575ccc03eaae13d9bfc00387. I had to make two changes to the app to be able to reproduce the issue:
1. I had to change maxSdkVersion to 31. The code is referencing `BLUETOOTH_CONNECT` and `BLUETOOTH_SCAN` which were introduce in API 31. ([source](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_SCAN))
2. I added the following code to [this line](https://github.com/stripe/stripe-terminal-android/blob/69af2ee70c88f914e8a30449aec0a487667d0293/Example/kotlinapp/src/main/java/com/stripe/example/fragment/event/EventFragment.kt#L201) so I could try collecting another payment
```
activityRef.get()?.let {
                        if (it is NavigationListener) {
                            it.runOnUiThread {
                                it.onRequestExitWorkflow()
                            }
                        }
                    }
```

## Android version

Android 30 and 31

## Impacted devices (Android devices or readers)

Both Chipper 2X and M2 readers - I've tested it on two android devices API 30 and 31.
## SDK version

2.5.1 and 2.4.1 ( I didn't test any other version)

## Other information

Reproduction steps
1. Connect to a reader
2. Tap on Collect Card Payment
3. Tap on Collect Payment
4. Wait until "Swipe/Insert/Tap" event appears
5. Tap your card on the reader and right after that (0-100ms) on cancel in the top left corner
6. Tap on Collect Card Payment
7. Tap on Collect Payment
8. Notice no events appear - the reader is stuck

**Comment by dhenry-stripe** [comment]
Thanks @malinajirka, the details and steps to reproduce are very helpful! The fix will be included in the next release (date TBD).

**Comment by dhenry-stripe** [comment]
Resolved in https://github.com/stripe/stripe-terminal-android/releases/tag/v2.5.2
