### ISSUE TITLE
Pre-dipping failed when BBPOS initialized the first payment intent.

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#182]
## Summary

In SDK version 2.5.1, we found a bug. The first payment intent after BBPOS initialized will fail as long as it is pre-dipping. It shows the "collectPaymentMethod" failed and the code return with "TerminalException-> USER_ERROR.CANCELED"
After the first payment (no matter it is pre-dipping or not), the rest payments with pre-dipping works good.

## Code to reproduce

collectPaymentMethod  onFailure   TerminalException-> USER_ERROR.CANCELED

## Android version

7 & 9
## Impacted devices (Android devices or readers)

BBPOS
## SDK version

2.5.1

**Comment by dhenry-stripe** [comment]
Resolved in https://github.com/stripe/stripe-terminal-android/releases/tag/v2.5.2
