### ISSUE TITLE
Example App Asks for Pairing Pin

### ISSUE THREAD

**Issue by scottwilson312** [stripe/stripe-terminal-android#191]
## Summary
I have tried my own app and the sample app and get the same issue. When trying to pair it first asks via a notification  if I want to pair, I say yes. Then immediately another pairing requests pops up and asks for a pin number. I am not sure how to set up this pin number or if this is expected behavior or not.

This is is on both a Lenvovo Tab M8 and a Google Pixel 3A. Both are running Android 10. I am using the Stripe Reader M2. I am using the Heroku backend.

![Screenshot from 2021-12-21 04-49-53](https://user-images.githubusercontent.com/16478974/146917876-9ea67aff-ad1c-4ab5-91ea-3da71cdf5ed3.png)

![Screenshot from 2021-12-21 04-50-14](https://user-images.githubusercontent.com/16478974/146918024-6b58dfb7-0476-4440-9028-c542b1352fe5.png)

**Comment by scottwilson312** [comment]
I have tried entering this "Key Identifier" as the pin with no luck. https://stripe.com/docs/terminal/readers/stripe-m2

![Screenshot from 2021-12-21 04-54-53](https://user-images.githubusercontent.com/16478974/146918595-12a431d9-6f53-4f23-9fab-80632e400df4.png)

**Comment by scottwilson312** [comment]
Other things I have tried:

1. Restarting the m2 via the power button
2. Resetting the m2 with a paper clip
3. Factory reset my Lenovo Tablet
4. Uninstall / reinstall the app

**Comment by scottwilson312** [comment]
Note that I am able to connect to a BBPOS Chipper 2X just fine through the sample app. It just automatically connects after pressing connect. It does NOT prompt me to connect via bluetooth through a notification, like the M2 does in the screenshots above.

**Comment by dhenry-stripe** [comment]
Hi @scottwilson312, do you see a 6 digit number printed on the back of the M2 in the top left? Can you try entering that when prompted for a pin?

**Comment by scottwilson312** [comment]
dhenry - that was the magic ticket! Thank you very much for the help
