### ISSUE TITLE
Pairing request become a notification but  not a dialog

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#204]
System：Android 
Sdk version : 2.5.2 
When connect a new reader , there is a pair request , sometimes  is a dialog popup  , this is ok . But sometimes  is notification  ,this notification is very to make the user ignore it  ,so this will cause connect reader failed . 
My question is what should I do can make the pairing request always a dialog ?

**Comment by dhenry-stripe** [comment]
@minjie0707 this is unfortunately out of our hands. Android determines how the pairing request is presented.
