### ISSUE TITLE
Where can I get the sdk release note ?

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#207]
what is difference between 2.7.0 , 2.60,2.5.2 ? Where can I get the release notes for the every version ?
 
And what is difference between M2 reader and  BBPOS Chipper 2X BT . Can they use the same android code ?

**Comment by billfinn-stripe** [comment]
Hi @minjie0707!

> what is difference between 2.7.0 , 2.60,2.5.2 ? Where can I get the release notes for the every version ?

You can have a look at the CHANGELOG: https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md

> And what is difference between M2 reader and BBPOS Chipper 2X BT . Can they use the same android code ?

They can use the same Android code. Have a look at our docs located here: https://stripe.com/docs/terminal.
