### ISSUE TITLE
why the M2 reader lost the paired info ?

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#208]
M2 already paired to the android device , but sometimes  when connect to this reader , they still need me to repair again , I think this is abnormal  ,  I do know why this happen ?
SDK Version : 2.5.2

**Comment by minjie0707** [comment]
> Hi @minjie0707, can you please provide a serial number for one of the M2 devices that's experiencing this behavior?

STRM26139016696  and  STRM26138001579

**Comment by dhenry-stripe** [comment]
Thanks @minjie0707, I don't see anything unusual in the logs for those devices. Is this the error you're describing? `READER_ERROR.BLUETOOTH_DISCONNECTED: Bluetooth unexpectedly disconnected during operation.`

If so, I do see several occurrences of that error for both `STRM26139016696` and `STRM26138001579`.

Each of the errors follows a similar pattern:
1. A bluetooth connect operation begins
2. 30-60 seconds passes
3. The following error occurs: `lass=BBPOSControllerListener message="onError FAIL_TO_START_BT, Bluetooth (error code - 3020)(BLE status : 22, newState : 0)`

This looks like normal Bluetooth activity, in that a device is unable to be reached and fails to connect. 

Do you have connection retry logic built into your application? If not, you may want to consider adding it.
