### ISSUE TITLE
Metadata example in sample.

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#21]
Hey folks is it possible to get an example of adding some additional metadata to the transaction in the sample application? We tried to pass some along through with the transaction as per the docs but it doesn’t appear against the transaction in the API so I feel we maybe doing something wrong..

**Comment by danwaters-stripe** [comment]
Hi, can you give me some more detail on how you're passing metadata? And which method you're passing it on?

**Comment by legomanaustralia** [comment]
hi @danwaters-stripe!

We're passing it through on the createPaymentIntent function. see below.

Screenshots of the debugger with the values in the object. 
https://clip2net.com/s/41cHQsQ

` public void startTransaction() {
        try {

            if(StripeReaderConnectPresenter.READER_CONNECTED) {
                Terminal instance = Terminal.getInstance();
                if(instance == null) {
                    getViewState().connectStripeReader();
                } else {
                    PaymentIntentParameters paymentParams = new PaymentIntentParameters.Builder()
                            .setAmount(m_TopupLogService.getCashAmount().intValue() * 100)
                            .setCurrency(m_TopupLogService.getAddCurrency().code)
                            .setDescription(getEventAndTopupStationName() + " - " +getFormattedAmount())
                            .setMetadata(m_TopupLogService.getMetadata(m_SelfDataService.getSelfId(), null, null))
                            .build();
                    instance.createPaymentIntent(paymentParams, new CreatePaymentIntentCallback());
                }
            } else {
                getViewState().connectStripeReader();
            }
        } catch (Throwable ex) {
            LOG(ex.getMessage(), ex);
        }
    }`

**Comment by danwaters-stripe** [comment]
Ah, thanks for the heads up. Due to an oversight in the Android SDK, we're not passing that on to the server. I'll make sure to get that working in our next beta release.

**Comment by danwaters-stripe** [comment]
Just wanted to confirm that this fix was included in release 1.0.0-b3. Let me know if you still see any problems with it.

**Comment by rscherf** [comment]
@danwaters-stripe I've been using `1.0.0-b7` and I'm not seeing the values from `setApplicationFeeAmount` being passed along either. Was this fixed in a later release?
