### ISSUE TITLE
Version 2.7.0 can not get the PaymentStatus.PROCESSING‘s callback

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#210]
SDK Version : 2.7.0
reader's serial-Number:  CHB20Y118028750
Use the USB method to connect the reader 

When I invoke this "Terminal.getInstance().processPayment(collectPaymentIntent, processPaymentCallback) " . Normally We should receive the onPaymentStatusChange's callback and the parameter status should == PaymentStatus.PROCESSING , but sometimes we can not receive this callback and block the payment . so could you help us to check it .

happened time is around 1:57:12.941 am, Wed, Mar 9, 2022 UTC time

**Comment by minjie0707** [comment]
who can give me help ?

**Comment by dhenry-stripe** [comment]
Duplicated by https://github.com/stripe/stripe-terminal-android/issues/212
