### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-android#211]
## Summary

After upgrading to 2.7.0, I now get this error while building. 

It seems that this is maybe an issue with a dependency that was upgraded in 2.7.0? 

```
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-java-res, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /Users/nprail/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/nprail/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
```

## Android version

N/A

## Impacted devices (Android devices or readers)

N/A

## SDK version
2.7.0

**Comment by dhenry-stripe** [comment]
Hi @nprail, this sounds like a gradle or java incompatibility. Can you please post the gradle version and java version used by your project?

**Comment by nprail** [comment]
@dhenry-stripe Here are the versions I'm using:

```
------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Mac OS X 11.2 x86_64
```

**Comment by dhenry-stripe** [comment]
okay, and just to confirm - are you setting the following in your `build.gradle`? 
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

It could also be related to your `compileSdkVersion` value. Is it currently set to 31? If not, can you try updating to 31 and see if that resolves it?

**Comment by nprail** [comment]
Yep, I do have those compile options set and I am using `compileSdkVersion` 31.

**Comment by dhenry-stripe** [comment]
ah, it looks like this is a bug with Jetifier. This thread has the details: https://issuetracker.google.com/u/0/issues/209825727

Are you using AGP 4.2.2? Can you try updating to the latest?

**Comment by nprail** [comment]
I was am using 4.2.0. Tried 4.2.2 which didn't help and then also tried 7x but that caused other issues. However, I did find a workaround by adding the moshi jar to the jetifier ignorelist.

**Comment by dhenry-stripe** [comment]
okay, thanks for sharing your solution!
