### ISSUE TITLE
Terminal sdk upgrade  version v2.7.1  error

### ISSUE THREAD

**Issue by xiaohu369** [stripe/stripe-terminal-android#214]
![image](https://user-images.githubusercontent.com/86939162/160082163-b175eb90-091a-4ddd-b921-ee312f2d25eb.png)
![image](https://user-images.githubusercontent.com/86939162/160082265-19cfd850-6080-443f-be13-9f0cadd03218.png)

**Comment by xiaohu369** [comment]
from v2.5.2 to v2.7.1

**Comment by dhenry-stripe** [comment]
Thanks for reporting @xiaohu369. Can you please try updating your kotlin version to 1.6?

**Comment by gstcyr** [comment]
I'm getting the same error even after updating my kotlin version to 1.6

**Comment by dhenry-stripe** [comment]
Which version of Android Gradle build tools are you using? Can you please try the solution described here: https://github.com/stripe/stripe-terminal-android/issues/211#issuecomment-1064458462

**Comment by dhenry-stripe** [comment]
More details here: https://github.com/square/moshi/issues/1454#issuecomment-989981705

**Comment by gstcyr** [comment]
Yup finally got it building by adding `android.jetifier.blacklist=moshi-1.13.0.jar` to my `gradle.properties`

**Comment by fahadtahir1** [comment]
I'd also tried ` android.jetifier.blacklist=moshi-1.13.0.jar to my gradle.properties` 
and I got this error then in android studio.

`A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

**Comment by chr-stripe** [comment]
@fahadtahir1 this looks like a different issue since the stack trace is different than the one posted in the original comment. Can you file a separate issue with more information on the details of the build failure?
