### ISSUE TITLE
BPos Terminal Exception in decode Response

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#22]
Hey Folks,

One of our QA team cam across this error whilst testing the integration on the new -b2 version.  Screenshot attached. Apparently it was fired while trying to process a payment.

https://drive.google.com/file/d/1YC2foh09UGLieTrbhCSdGcwFg_wBZGFe/view?usp=sharing

**Comment by danwaters-stripe** [comment]
Hi,

It looks like that error was for an invalid card number. Do you know if they were using a strange card type at the time? Or is this happening on all charges?

**Comment by legomanaustralia** [comment]
Nope definitely not happening on all transactions, that would actually make sense as i think they were trying hotel cards etc to see if they could trip it up.
