### ISSUE TITLE
fetchConnectionToken method inside TokenProvider class Failed to fetch connection token from api

### ISSUE THREAD

**Issue by doshikh** [stripe/stripe-terminal-android#223]
I have implemented Terminal SDK inside native android app.

## Summary
Application case 
1. App starts in offline and init method of terminal code in first case where it failed to fetch token from server api 
2. Now sdk always return Terminal.isInitialized() = true so I can't reinit the terminal 

How can call that fetch connection token method again and set token in TokenProvider class ?
Please help me to setup token to sdk again because fetch connection token not call again in case of api failed in first go.

## Code to reproduce
Example app crashing when we start it in offline

## Android version
11

## Testing in Samsung Real device 
SM-M127G

## SDK version
2.7

## Other information
I have initialised terminal using 
Terminal.initTerminal(getApplicationContext(), LogLevel.VERBOSE, new TokenProvider(),
                    new TerminalEventListener());

**Comment by billfinn-stripe** [comment]
> How can call that fetch connection token method again and set token in TokenProvider class ?

The Terminal SDK will reuse the same instance of the `TokenProvider` class provided to fetch a new token. You should not have to provide a new instance. Instead, your `TokenProvider` class should re-fetch a token whenever `fetchConnectionToken` is called. If fetching the connection token failed, the Terminal SDK will retry to fetch the connection token the next time an operation is requested that requires a connection token.

**Comment by doshikh** [comment]
Yes I have figure out that , Thank you for answer.
I have setup SDK with flutter so trying to provide connection token from Flutter to Native Android but retry not working and reinitialisation not allowed so Setup api call in native in Provider class and initialisation time so it works for me.
