### ISSUE TITLE
SDK includes previous tip value in background even when tipping is disabled

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#224]
## Summary
Let's say a transaction is done which includes a tip(eg £2.50). After disabling tipping, reconnecting to reader, and doing a new  transaction without tipping, the terminal does not show the tipping UI. But in the background, the SDK holds the previous tip amount(£2.50) and includes it in the payment intent request.

So, on the reader it looks like the transaction is of £10.00 but the actual deducted amount is £12.50.
Works fine if the app is closed and re-opened, thus re-initialising the SDK.

## Steps to reproduce
Take a payment with tip, disable tipping, reconnect reader(for changes to apply) and take another payment, in the same session(without closing the app)

## Android version
12

## SDK version
2.8.0

## Other information
Snapshots, videos, and payment intents are available on request.

**Comment by dhenry-stripe** [comment]
Thanks for reporting @yogen-p, we're looking into this now and will update you when we have a fix.

**Comment by billfinn-stripe** [comment]
@yogen-p -- we're working on building a fix on top of 2.8.0. We'll let you know when it's been released.

**Comment by billfinn-stripe** [comment]
Hi @yogen-p -- version `2.8.1` is now available in Maven Central, and it contains a fix for this bug. Thanks again for reporting this, and please let us know if you encounter any other issues.

**Comment by yogen-p** [comment]
Thanks @billfinn-stripe and @dhenry-stripe for your quick response.
