### ISSUE TITLE
Add Refresh Token Flow To Sample App

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#23]
We spotted this error in our application, looks like the token needs to be refreshed after some time. At this time of writing it the correct way to deal with this doesn't appear in the sample application.

Any chance of getting this added to the sample application to see how we should be implementing this correctly.

Screenshot.
https://drive.google.com/file/d/1jnax7DrzuIvcuaGmmGIEf2iFhXpU2mwh/view?usp=sharing

**Comment by anton8900** [comment]
You library has TokenProvider why it doesn't use fetchConnectionToken method on expiration? Or maybe you need to add refreshConnectionToken method

**Comment by danwaters-stripe** [comment]
We made a change to the SDK to automatically disconnect from the reader in this scenario (and alert you that this happened so that you can cue the user to reconnect). This will be reflected in the example app in our next release.

**Comment by danwaters-stripe** [comment]
This is now reflected in the example app released with 1.0.0-b5.
