### ISSUE TITLE
USB_PERMISSION_DENIED error

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#231]
The first time use usb to connect the reader , there is a dialog popup 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/82426849/167608069-34af42a8-328e-4402-bc2e-f61652acc52d.png">
When  I click the "OK"  , then give me the discovery reader failed callback , the errorCode is TerminalException.TerminalErrorCode.USB_PERMISSION_DENIED.

SDK version : 2.9.0

**Comment by chenmin-stripe** [comment]
Hi @minjie0707 ,
I saw two failed `discoverReaders` for your reader within past 24 hours. I also saw two success `discoverReaders` right after the failed one. Could you let me know if you succeed discovered reader after the failed one? 

Could you also try check the box to allow permanent usb permission?

**Comment by minjie0707** [comment]
> Hi @minjie0707 , I saw two failed `discoverReaders` for your reader within past 24 hours. I also saw two success `discoverReaders` right after the failed one. Could you let me know if you succeed discovered reader after the failed one?
> 
> Could you also try check the box to allow permanent usb permission?

Because we re-try it again after failed , this time will be succeed . 
I think this is a new issue in 2.9.0 . It is fine in 2.7.1

**Comment by chenmin-stripe** [comment]
Hi @minjie0707 , did the issue happened to you consistently? First attempt always failed while second will succeed?

**Comment by minjie0707** [comment]
> Hi @minjie0707 , did the issue happened to you consistently? First attempt always failed while second will succeed?

yes, it is happened consistently.

**Comment by chenmin-stripe** [comment]
Hi @minjie0707 , could you try to check the box to allow permanent permission to see if that resolves the issue?

**Comment by minjie0707** [comment]
> Hi @minjie0707 , could you try to check the box to allow permanent permission to see if that resolves the issue?

This issue also happened when I check the box

**Comment by minjie0707** [comment]
@chenmin-stripe  Could you try it yourself ?

**Comment by chenmin-stripe** [comment]
Hi @minjie0707 , we have identified the issue and working on the fix. Aiming to have the fix released in 2.10.0. Thanks for your patience.

**Comment by sjl-stripe** [comment]
@minjie0707 we've just released [v2.10.0](https://github.com/stripe/stripe-terminal-android/releases/tag/v2.10.0) with the fix.
