### ISSUE TITLE
PaymentIntentStatus missing Processing value

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-android#236]
## Summary
The `PaymentIntentStatus` enum seems to be missing an option for `Processing` which exists in the iOS SDK and of course on the Stripe API. 

## Code to reproduce
N/A

## Android version
N/A

## Impacted devices (Android devices or readers)
N/A

## SDK version
2.10.0

**Comment by chr-stripe** [comment]
Thanks for pointing this out @nprail! We have added the `PROCESSING` option internally and it will be available in the next SDK release.
