### ISSUE TITLE
onRequestReaderInput and onRequestReaderDisplayMessage not triggering with ReadReusableCard

### ISSUE THREAD

**Issue by raelsonraujo** [stripe/stripe-terminal-android#237]
## Summary
Hi!

Trying to implement Stripe Terminal for Android that's working as we would expect, until I reach the part of reading credit cards. 

For that I'm using the method **ReadReusableCard**, which only partially works. I'm getting the credit card back in the simulated reader and BBPOS 2X BT, in the PaymentMethodCallback, but the callbacks for _onRequestReaderInput_ and _onRequestReaderDisplayMessage_ are failing to trigger completely. So the user doesn't get the hints about what to do.

However, whenever I go the route of using **SetupIntents**, they work as expected. I still haven't figured out how to get the payment method information in a similar fashion that ReadReusableCard gives us, (Brand, Last4, etc.) with SetupIntents.

So, I have three questions:

- Is the **ReadReusableCard** intended to not trigger the _onRequestReaderInput_ and _onRequestReaderDisplayMessage_ message callbacks? We do pass the _BluetoothReaderListener_ upon connection to the reader, which triggers the firmware update messages as we would expect for example. 
- Do we really have migrate to **SetupIntents**? 
- And if yes, how do we get the credit card information using **SetupIntents** in a similar fashion that **ReadReusableCard** does?

## Android version
Android 11

## Impacted devices (Android devices or readers)
Issue reported in BBPOS 2X BT and also in the simulated reader

## SDK version
Stripe Terminal Android 2.7.0

## Other information
I have an implementation for Stripe Terminal iOS in which _onRequestReaderInput_ and _onRequestReaderDisplayMessage_ works as expected using the **ReadReusableCard**.

**Comment by raelsonraujo** [comment]
Quick update:
When I run the Example (javaapp), if I connect the reader and then tap the **Read card for recurring payment** button, the only callback I'm seeing being triggered is the success of the PaymentMethodCallback right at the end. 

Comparing to how the SDK behaves in Stripe Terminal iOS, I was expecting _onRequestReaderInput_ and _onRequestReaderDisplayMessage_ to also trigger, in a similar fashion that happens if we go with SetupIntent.

**Comment by chenmin-stripe** [comment]
Hi @raelsonraujo , thanks for reaching to us and report your findings.
I would suggest you switching to `SetupIntents` entirely. Here is the [doc](https://stripe.com/docs/terminal/features/saving-cards/overview) for your reference. The reason is also listed in doc, quoted below
> We currently support readReusableCard in our SDKs and server-driven integration, but will eventually phase it out in favor of [SetupIntents](https://stripe.com/docs/terminal/features/saving-cards/save-cards-directly), which supports contactless cards in more countries.

For payment details, here is the [doc](https://stripe.com/docs/api/setup_intents) reference
> If the SetupIntent is used with a [Customer](https://stripe.com/docs/api/setup_intents#setup_intent_object-customer), upon success, it will automatically attach the resulting payment method to that Customer.

**Comment by raelsonraujo** [comment]
Gotcha, this is what I needed. I'll be closing the issue and will migrate to the SetupIntents once the opportunity arrives. Thanks so much!
