### ISSUE TITLE
Verifone P400 Support

### ISSUE THREAD

**Issue by condesales** [stripe/stripe-terminal-android#242]
Are there any plans to add support to P400 terminals to Android, matching iOS and JavaScript counterparts?

**Comment by rv-stripe** [comment]
You should be able to connect to a P400 on Android and perform transactions in supported countries.
Please note that, while the P400 is still supported, it is no longer being sold and will not see new functionality added to Terminal. More information available on our [WisePOS E Questions Page](https://support.stripe.com/questions/bbpos-wisepos-e)

**Comment by condesales** [comment]
yep, we tested that and it worked perfectly.
It's interesting that the stripe website doesn't mention the P400 as supported by Android SDK as it does for iOS.
That's where our confusion came from. It would be nice to have it documented.
