### ISSUE TITLE
Not able to create payment intent in client side

### ISSUE THREAD

**Issue by L-is-0** [stripe/stripe-terminal-android#247]
## Summary
I am trying to create payment intent from client side by following the docs, however I am keep getting the error of "You did not provide an API key. You need to provide your API key in the authorization header"

## Code to reproduce
`  PaymentIntentParameters params = new PaymentIntentParameters.Builder()
                .setAmount(Long.parseLong(amountInPence))
                .setCurrency("gbp")
                .build();

        Terminal.getInstance().createPaymentIntent(params, new PaymentIntentCallback() {
            @Override
            public void onSuccess(PaymentIntent paymentIntent) {
                LogUtil.d(TAG, "create payment intent successful");
                retrievePaymentIntent(paymentIntent.getClientSecret());
            }

            @Override
            public void onFailure(TerminalException exception) {
                LogUtil.e(TAG, "createPaymentIntent() - onFailure");
            }

        });`

## Android version
android 11

**Comment by L-is-0** [comment]
> Hi @L-is-0 How were you fetching `connectionToken`, did you provide your stripe account apiKey when fetching `connectionToken`? Could you also provide your reader serial?

Hi @chenmin-stripe 
I fetched it on TokenProvider implements ConnectionTokenProvider by following the instruction in Android doc
I get a client_secret from backend side and passed it to connectionTokenCallback.onSuccess() method

**Comment by lambda0xff** [comment]
I'm getting the same exact error.

@L-is-0 : did you manage to fix it or found any issue ?

**Comment by chenmin-stripe** [comment]
Hi @lambda0xff @L-is-0 could you provide the reader serial and timestamp when did you encountered the issue? I can dig more on our side

**Comment by lambda0xff** [comment]
@chenmin-stripe:
serial number : WPC323121010066
timestamp     : Not too sure what you mean by this; I get this error everytime I try to create a payment intent. The unix timestamp of one such error: 1660196466676.

Also, and that maybe another issue: when running the example application, trying to connect to the reader always pops up a "do you want to pair with [S/N]" dialog.

If I answer no, the connection fails with "Failed to connect with error: Bluetooth unexpectedly disconnected during operation"; if I answer yes, then the connection operation is stuck at "Connecting..."

**Comment by lambda0xff** [comment]
@chenmin-stripe :
Looking at the logs of my app, it looks like a connection error; the connection status is stuck at "CONNECTING" and if I try to create a payement intent anyway then I get the API error; otherwise, after a while the terminal throws a TerminalException: Blutooth unexpectedly disconnected during operation.

**Comment by lambda0xff** [comment]
@chenmin-stripe : when trying to connect with a USB cable, the example app displays "connecting" and I get this error log:

com.stripe.example D/BbposControllerListener: {date: Sat Aug 13 15:28:00 GMT+02:00 2022,type: CALLBACK,message: errorState : DEVICE_BUSY, errorMessage : Device busy with command/callback: getDeviceInfo ***,callback: onError}
com.stripe.example I/StripeTerminal: class=BbposControllerListener message="onError DEVICE_BUSY, Device busy with command/callback: getDeviceInfo ***"

**Comment by chenmin-stripe** [comment]
thanks for the detail @lambda0xff , looking for more detail on our side. Will keep the thread updated

**Comment by chenmin-stripe** [comment]
>  it looks like a connection error; the connection status is stuck at "CONNECTING" and if I try to create a payement intent anyway then I get the API error;

@lambda0xff did you get to the connected screen but log still showed reader was "CONNECTING"?

**Comment by lambda0xff** [comment]
@chenmin-stripe 
No, I never got to the connected screen.
This is what I get when trying to connect with bluetooth:
![screen1](https://user-images.githubusercontent.com/38687176/184688118-bd839373-ea80-4e6c-94f6-8b89ed2b02dc.png)
![screen2](https://user-images.githubusercontent.com/38687176/184688126-c08b7296-4852-45c4-b28c-ade02e685b6b.png)
![screen3](https://user-images.githubusercontent.com/38687176/184688134-42ad1722-fdcd-4cf8-8043-05e33bec6ca7.png)
![logcat](https://user-images.githubusercontent.com/38687176/184688163-babd122f-616b-4db0-a16d-9836d9dd1d14.png)
With bluetooth, I get the disconnection error after a few seconds.  When trying with a USB cable it doesn't crash but is indefinitely stuck at the "Connecting" stage.

Tried turning the reader on/off but without any change.

I'm really not sure what's going on here. Could it be that the reader maybe faulty ?

**Comment by lambda0xff** [comment]
@chenmin-stripe 
Logcat with USB cable
![logcat usb](https://user-images.githubusercontent.com/38687176/184689441-90a80cc0-f0da-4d74-b53e-f3b2bd0a16e5.png)

**Comment by chenmin-stripe** [comment]
@lambda0xff Are you able to get the unfiltered logs for bluetooth and usb and attach them here

**Comment by lambda0xff** [comment]
@chenmin-stripe 
[bluetooth.txt](https://github.com/stripe/stripe-terminal-android/files/9338974/bluetooth.txt)
[usb.txt](https://github.com/stripe/stripe-terminal-android/files/9338976/usb.txt)

**Comment by chenmin-stripe** [comment]
@lambda0xff Sorry for not being clear. Could you include android OS log, I'd like to check the paring from OS level

**Comment by lambda0xff** [comment]
@chenmin-stripe 
Sorry for the delay.  I actually managed to connect to reader to another device and it took a while to update the firmware.

I think I was originaly confused by this section in the docs:
![stripe doc](https://user-images.githubusercontent.com/38687176/184696964-78fcd80a-5d44-4515-919b-45d2f23981c4.png)
Everytime the pairing pop up would appear I would respond no, thinking the pairing would be taken care of by the SDK.

Now, after pairing the device, the connection process works flawlessly on one device but is still stuck at "connecting" on the other device.

The only significant difference between both devices I can think of is the the one which cannot connect doesn't have a gps whilst the one that connects successfully does have one.  However, I was under the impression that as long as the "location" permission was granted that wouldn't make a difference ?

Attached are the unfiltered logs for both:

[bluetooth_not_working.txt](https://github.com/stripe/stripe-terminal-android/files/9339217/bluetooth_not_working.txt)
[bluetooth_working.txt](https://github.com/stripe/stripe-terminal-android/files/9339218/bluetooth_working.txt)

**Comment by billfinn-stripe** [comment]
From reading the `bluetooth_not_working.txt` logs, it appears as though the device does connect:

```
2022-08-15 20:41:59.847 18849-18849/com.stripe.example D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTED)
```

When trying to get the device info from the device, the SDK receives a `DEVICE_BUSY` error:

```
2022-08-15 20:42:00.685 18849-18849/com.stripe.example I/StripeTerminal: class=BbposControllerListener message="onError DEVICE_BUSY, Device busy with command/callback: getDeviceInfo ***"
```

Can you update to the latest version of the SDK and share any error logs you are seeing on the app?

**Comment by billfinn-stripe** [comment]
Hi @L-is-0 -- I'm going to close this issue due to inactivity, but feel free to reopen if/when you have additional information to help us troubleshoot.
