### ISSUE TITLE
ReaderInputOptions access to the inner list

### ISSUE THREAD

**Issue by fh-apanfilov** [stripe/stripe-terminal-android#248]
## Summary
Feature Request.
With the current api of the `ReaderInputOptions`
https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-reader-input-options/index.html
Developers can't base their logic on specific input options, compared to iOS SDK.

Example: If I'm as a developer want to check if the [Swipe] input option is available during the payment - I simply can't, because the inner list of the options is not available from the interface.

Possible solution would be to have any kind of checking interface, e.g.:
- Public read access to the inner list of [ReaderInputOption] objects
- New method [.contains(ReaderInputOption)] that can report if a specific option is contained in the ReaderInputOptions object

## Code to reproduce
None

## Android version
Any

## Impacted devices (Android devices or readers)
Chipper 2X and WisePad3

## SDK version
2.10.2

## Other information
None

**Comment by ugochukwu-stripe** [comment]
@fh-apanfilov this issue should be resolved in `2.13.0`. Thanks for the detailed request!
