### ISSUE TITLE
Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option

### ISSUE THREAD

**Issue by Jimitshah2312** [stripe/stripe-terminal-android#250]
## Summary

I facing this Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option error while using the latest version of the stripe terminal.

Also, face this Super calls of '@JvmDefault' members are only allowed with -Xjvm-default option error.

## Android version

Any

## SDK version

implementation "com.stripe:stripeterminal:2.12.0"

## Other information

minSdkVersion 24
targetSdkVersion 31

![Screenshot from 2022-08-04 18-50-59](https://user-images.githubusercontent.com/83710086/182857427-e7abd2d2-d226-477a-ab9e-983066adf5e9.png)

**Comment by rv-stripe** [comment]
What version of Kotlin is your project using?
And is `lifecycle-viewmodel` a dependency of your project? 
I suspect you may be running into [this issue](https://issuetracker.google.com/issues/217593040) from Google - There's a workaround to try in that ticket, if that's the issue.

**Comment by Jimitshah2312** [comment]
Kotlin Version: 1.5.31
Lifecycle Version: 2.4.1

I will look at the above link. If you find it useful then put it here it'll help.

Thanks, @rv-stripe.

**Comment by Jimitshah2312** [comment]
Thanks for your response @rv-stripe 
It resolves to upgrade ```lifecycle-viewmodel``` and kotlin version.
