### ISSUE TITLE
FR: Serializing PaymentIntentParameters

### ISSUE THREAD

**Issue by pc-coholic** [stripe/stripe-terminal-android#255]
## Summary
I would like to see a facility to easily serialize a `PaymentIntentParameters` object.

## Code to reproduce
Right now, there is no easy way to serialize the `PaymentIntentParameters` - the next best thing would be to use something similar to
````kotlin
val params = PaymentIntentParameters.Builder()
    .setFoo(bar)
    .build()
val p = JSONObject()

for (prop in PaymentIntentParameters::class.memberProperties) {
    p.put(prop.name, prop.get(params))
}
````

Being able to do `JSONObject(params)` would be ideal - but anything that can be used to post the params to our own API-client would be great.

## Android version
10

## Impacted devices (Android devices or readers)
Android devices

## SDK version
2.13.0

## Other information
Using Bluetooth-readers, the PI can be created on the Android device directly - however for Internet-terminals (P400/WisePOS E), the PI needs to be generated server-side. (I don't really see why to be honest - the result seems to be pretty much the same no matter where the PI has been generated). So in order to cut down on duplicate code, we'd love to generate the `PaymentIntentParameters` object once and then pass it either to the built-in PI-requestor or our own API-client that passes it to our server backend for PI-generation.

I would also be open to just having the PI-generator in the SDK being able to generate the PI for Bluetooth and Internet-Terminals - but I'm assuming this limitation exists for a reason ;-)

**Comment by chr-stripe** [comment]
Hi @pc-coholic, thanks for the feature request!

I'm curious if you have considered using something like [Gson](https://github.com/google/gson/blob/master/UserGuide.md) for serializing/deserializing the `PaymentIntentParameters` object. By default, it effectively does something similar to your code snippet above, using reflection to translate the parameters to and from json.

**Comment by pc-coholic** [comment]
Hi @chr-stripe,

yes - I did indeed consider that (and am using Jackson) - but this is not exactly a perfect solution...

Take for example the following `PaymentIntentParams`:
```kotlin
val params = PaymentIntentParameters.Builder(
        amount = (receipt_total * BigDecimal("100.00")).toLong(),  // TODO: Does not work for 0-digit currencies
        currency = event_currency.toLowerCase(),
        captureMethod = CaptureMethod.Automatic,
        allowedPaymentMethodTypes = listOf(PaymentMethodType.CARD_PRESENT, PaymentMethodType.INTERAC_PRESENT)
)
        .setDescription(desc)
        .setStatementDescriptor(desc.substring(0, min(desc.length, 22)))
        .setMetadata(mapOf(
                "app" to "pretixPOS",
                "appversion" to BuildConfig.VERSION_NAME,
                "organizer" to conf.organizerSlug,
                "event" to event_slug,
                "posid" to conf.devicePosId.toString(),
                "posserial" to conf.devicePosSerial,
                "receipt" to receipt_id.toString()
        ))
        .build()
```

**Comment by chr-stripe** [comment]
Ah yes, I see what you're saying now. Unfortunately our [Mobile Device SDKs](https://stripe.com/docs/libraries#stripe-mobile-sdks) don't have this kind of interoperability with our [Server-side SDKs](https://stripe.com/docs/libraries#server-side-libraries). This is partly because they serve two different purposes, but also because versioning between the two SDKs would make this difficult – the mobile SDK would not know which version of the server SDK you'd like to serialize a model into (and that model may change across versions!)

That being said, we are looking into improving the experience with creating payment intents for internet-enabled readers, including re-evaluating this existing limitation you're running into.
