### ISSUE TITLE
retrievePaymentIntent is not giving a success or failure callback

### ISSUE THREAD

**Issue by matghazaryan** [stripe/stripe-terminal-android#258]
## Summary
retrievePaymentIntent is not giving a success or failure callback. If I do the first time it's okay, the second time it's okay. 
I am starting not to receive a callback if I am creating the payment and canceling it immediately then creating again then canceling it again. 

## Code to reproduce

 Terminal.getInstance().retrievePaymentIntent(clientSecret,
                object : PaymentIntentCallback {
                    override fun onFailure(e: TerminalException) {}
                    override fun onSuccess(paymentIntent: PaymentIntent) {  }
 })

I also copied the logs maybe it will be helpful. 

## Android version
   Android 11

## Impacted devices
all devices

## Installation method
Gradle

## Dependency Versions
  implementation "com.stripe:stripeterminal:2.12.0"

## Other information
 I/StripeTerminal: class=CrpcClient message="GatorService.reportTrace response={}"
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent request=null"
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent response={}"

**Comment by chr-stripe** [comment]
Hi @matghazaryan, can you describe a bit more about what steps are leading to not receiving the `retrievePaymentIntent()` callback? You're creating and cancelling several payment intents, and then retrieving which one exactly? Are you using the SDK for all of these calls, or is your creation/cancellation happening through a backend?

**Comment by matghazaryan** [comment]
Hi chr-stipe

Let me describe the case.
I am creating paymentIntent using my backend. when I am getting the secret key I am calling Stripe's retrievePayment api to get PaymentIntent object to continue.

When I am creating PaymentIntent and waiting for collectPayment to be called I am closing the screen. In that case cancelPayment Stripe SDK is calling which giving me success callback. 
Than I am repeating this step 3 or 4 times and retreivePayment stucking and never getting any callback. 

In sort. Opening screen and closing screen immediately 3 or 4 times retrievePayment never gives me a callback.

It's unclear what's happening and why I am not receiving callback

**Comment by chr-stripe** [comment]
Can you share a code snippet of what your cancellation code looks like? For how you initiate the cancellation of the payment intent and how you handle the callback from that process? I suspect the issue might be lying in there – it might be possible that an issue with cancelling the previous payment intent might block other operations from taking place within the SDK, including calling `retrievePaymentIntent()`.

**Comment by matghazaryan** [comment]
This is my cancel request
`suspend fun cancelPaymentIntent(paymentIntent: PaymentIntent): PaymentTerminal =
        suspendCancellableCoroutine { continuation ->
            Terminal.getInstance().cancelPaymentIntent(paymentIntent, object : PaymentIntentCallback {
                override fun onFailure(e: TerminalException) {
                    continuation.resume(PaymentTerminal(null, e), null)
                }

                override fun onSuccess(paymentIntent: PaymentIntent) {
                    continuation.resume(PaymentTerminal(paymentIntent, null), null)
                }
            })
        }`

and this is my retrievePaymentIntent
` suspend fun retrievePaymentIntent(clientSecret: String): PaymentTerminal =
        suspendCancellableCoroutine { continuation ->
            Terminal.getInstance().retrievePaymentIntent(clientSecret,
                object : PaymentIntentCallback {
                    override fun onFailure(e: TerminalException) {
                        println("MGMessageTerminalException="+e.errorMessage)
                        continuation.resume(PaymentTerminal(null, e), null)
                    }

                    override fun onSuccess(paymentIntent: PaymentIntent) {
                        println("MGMessageTerminalExceptionSuccess")
                        continuation.resume(PaymentTerminal(paymentIntent, null), null)
                    }
                })
        }`

**Comment by matghazaryan** [comment]
This is the full code: 
https://gist.github.com/matghazaryan/29aeef383c8ffdece3331dcc649be1c3
https://gist.github.com/matghazaryan/59efb56f1319f4bdcec3061578e201b3

**Comment by chr-stripe** [comment]
When you are calling your `suspend fun cancelPaymentIntent()`, are you receiving the callback in your `onFailure()` or `onSuccess()` method? I have a suspicion that if you are having to use your backend server to create the payment, I believe you _might_ also need to use your backend server to _cancel_ the payment intent as well. Calling the SDK's `Terminal.getInstance().cancelPaymentIntent()` method on a payment intent created on the server may (for now) be causing an issue that results in `onFailure()` to be called upon cancellation.

In some cases, in my own experience, that callback might even be called with a bit of delay, in which case that would also delay subsequent SDK calls (such as `Terminal.getInstance().retrievePaymentIntent()`!)

**Comment by matghazaryan** [comment]
Maybe we should try to cancelPaymentIntent using our backend. I will try this way to see how it works. Thanks for your help

**Comment by chr-stripe** [comment]
Sounds good! Please let me know what the outcome of that change is, once you manage to test it out.

**Comment by chr-stripe** [comment]
@matghazaryan any updates on how that change has worked out for you?

**Comment by matghazaryan** [comment]
@chr-stripe currently it's started to work without changing anything. I am not sure why. I didn't make any changes there. Thanks for asking.

**Comment by chr-stripe** [comment]
Sounds good. I'll close it for now, but feel free to reopen if you encounter this again!
