### ISSUE TITLE
Terminal shows Dollar($) sign instead of Pound(£)

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#259]
## Summary
The production card readers for some of our customers are showing the Dollar($) sign instead of Pound(£).
The transaction itself goes through fine in GBP and even when adding tips the amount is shown properly as GBP(£).
It's just the final confirmation amount before paying that shows Dollar($).

We've been seeing this after the latest firmware update.

It'd be great if we could sort this ASAP.

## Impacted devices (Android devices or readers)
Terminals with latest firmware 4.01.00.27

## SDK version
2.0.13

## Other information
This has not affected all our merchants, just a handful so far.
But it looks like it's growing, and creating some trust issues for us.

**Comment by rv-stripe** [comment]
Thanks for the report. We are looking into this and will follow up as soon as possible.

**Comment by rv-stripe** [comment]
We've identified the source of this issue and will address it in an upcoming release. I'll leave this issue open until it is resolved.

**Comment by Ekalips** [comment]
I can confirm that it's also happening here. It seems like that's a regression from **2.0.12**.

**Comment by rv-stripe** [comment]
We have resolved this issue in version `2.13.1` of the SDK.
Please update as soon as possible to resolve this issue.

Thanks again for reporting this!
