### ISSUE TITLE
process was blocked when call Terminal.initTerminal

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#268]
when invoke Terminal.initTerminal , the process block there .  I guess the stripeTerminal was waiting for the permission ,please help check it .

 StripeTerminal Version: 2.11.0
Android Version: Android 11

**Comment by minjie0707** [comment]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/82426849/199213972-26e2f5ae-9618-45d2-b5a3-83ec81b309b8.png">
Is this error log relate to the issue ?

**Comment by billfinn-stripe** [comment]
Hi @minjie0707 -- can you try upgrading your SDK to at least 2.12.0? We did fix an issue related to keystores in that version.

**Comment by minjie0707** [comment]
thanks , It is fine now when I upgrade the sdk to 2.14.0
