### ISSUE TITLE
Geo Lock When In Test Mode for readReusableCard

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#27]
hey folks,

not sure if this is intentional or an oversight but the readReusableCard function doesn't work for Belarus in test mode, our initial testing hasn't had any issues with geo restrictions when using test mode and it seems a little counterproductive for distributed/remote teams :)
(https://stripe.com/au/blog/remote-hub)

**Comment by bg-stripe** [comment]
Hi @legomanaustralia ! 

Terminal will be blocked based on the country the Stripe account is registered in. You'll need to provide your Belarus team with access to a US-registered Stripe account to unblock them. 

Hope that helps!

Ben
