### ISSUE TITLE
Run time error in Stripe Terminal discover device code build using kotlin

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#270]
I am trying to integrate stripe terminal code with my android app build using kotlin, unfortunately I am getting the following run time error which I could not able to fix

`java.lang.IllegalStateException: initTerminal must be called before attempting to get the instance`

The code I have added is used below

`  
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_pay_screen)
        onDiscoverReaders()
    }

    fun onDiscoverReaders() {
        val config = DiscoveryConfiguration(
            timeout         = 0,
            discoveryMethod = DiscoveryMethod.LOCAL_MOBILE,
            isSimulated     = false,
            location        = "xxxxxxxxxxxxxxx"
        )
        discoveryCancelable = Terminal.getInstance().discoverReaders(config,
        discoveryListener = object : DiscoveryListener {
        override fun onUpdateDiscoveredReaders(readers: List<Reader>) {
        }
        },object : Callback {
            override fun onSuccess() {
            println("Finished discovering readers")
            }

            override fun onFailure(e: TerminalException) {
            e.printStackTrace()
            }
        })
    }
`

I have added this to one of my activity and my intention is to check if my phone is supporting [stripe tap on mobile](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-on-mobile)

I guess the issue could be calling onDiscoverReaders() from a wrong place, someone please help me to fix this issue

Thanks in advance

**Comment by rv-stripe** [comment]
It looks like you're missing the initialization call that provides the SDK with a context and Token.
There are a couple of steps that need to be done to initialize the terminal, you can find the docs for doing that, including Kotlin examples [here](https://press.stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=android#initialize)
All of that should happen before the discover call. Let me know if that fixes your issue.

**Comment by ajithv11** [comment]
Thanks it works!

But I got another error on discoverReader function as given below
`com.stripe.stripeterminal.external.models.TerminalException: The Terminal `localmobile` module must be included for this DiscoveryMethod`

Please let me know If this work for NFC supporting mobiles only. By the way. I have checked in both NFC and Non NFC mobiles as well

Thanks in advance

**Comment by rv-stripe** [comment]
For that, make sure you add
`implementation("com.stripe:stripeterminal-localmobile:2.15.0")` (matching the version with the version of `stripeterminal` you're currently using)
in your `build.gradle` file.

**Comment by ajithv11** [comment]
Got error as given below

Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties' from inputs:
   .gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15to18/1.69/bf2bf57dad9a17f1fadf8db38894e780d1532f1a/bcprov-jdk15to18-1.69.jar
    Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

**Comment by rv-stripe** [comment]
It seems like there's a packaging conflict between dependencies. As the error suggests you may be able to resolve this with something like:

```groovy
android {
    // ...

    packagingOptions {
        pickFirst 'org/bouncycastle/x509/CertPathReviewerMessages.properties'
        pickFirst 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties'
    }
}
```

You may have to tweak that if you encounter additional similar errors.

**Comment by ajithv11** [comment]
Thanks , errors are gone now 

Now I am struck with the following error
`Error ReaderCallback : Account not enabled for Tap on Mobile functionality`
Do I need to enable anything from on stripe account . I am in test mode right now.

Thanks in advance

**Comment by rv-stripe** [comment]
If you're getting that error, the account you're using may not be be enrolled in the beta feature. Please reach out to support through the website to get that resolved for the account you're testing with.

**Comment by ajithv11** [comment]
Still the issue persist after enabling beta mode.. I am checking from India, will it make any sense in that error?

**Comment by davidyang-stripe** [comment]
Hi @ajithv11 Tap to Pay on Android is current in private beta. Is your Stripe account gated into this beta?

**Comment by ajithv11** [comment]
Hi @davidyang-stripe  my stripe account is already in beta. I wounder if tap to pay for android NFC phone may have different code base?  I have followed this documentation https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-on-mobile  , my implementation code is already added in the above thread (The code where I am struck )

Please let me know if beta has another code base and do we need to contact the beta support team to provide that?

I believe that if beta is different from public code, then I guess the code will be different from the above link and there should be a beta documentation as well for implementing the feature to android phones. Please let me know your thoughts

Thank you

**Comment by davidyang-stripe** [comment]
Hi @ajithv11 , can you reach out to tap-on-mobile@stripe.com and we can help you there. Thanks!

**Comment by rv-stripe** [comment]
Closing this to move to email thread.
