### ISSUE TITLE
Network error on connecting to Local NFC Reader : API_SERVER_ERROR: Attestation server returned internal server error

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#273]
Hi,

 I am getting the following error when I tried to connect to local NFC reader 

`API_SERVER_ERROR: Attestation server returned internal server error`
The code where I got the error is given below

    val config = ConnectionConfiguration.LocalMobileConnectionConfiguration("xxxxxxxxxxxxxxxxx");
    Terminal.getInstance().connectLocalMobileReader(
        firstReader, // This will have the reader instance
        config,
        object : ReaderCallback {

            override fun onSuccess(reader: Reader) {
                Log.d("Response Tap", "Connected to mobile device");
            }

            override fun onFailure(e: TerminalException) {
                Log.d("Response Tap","Error ReaderCallback : " + e.errorMessage); // Here the error comes
            }
    });

**Comment by chr-stripe** [comment]
Hi @ajithv11, I'll look into seeing why you might be getting a server error when attempting to connect to a local NFC reader. Can you provide me with the version of the SDK you're using, as well as what kind of Android device you're attempting to run this on?

**Comment by ajithv11** [comment]
@chr-stripe  The SDK version I am using is 2.15.0  and the mobile I used for testing is Galaxy F23 5G
Note: The above code works 4 days back, the only difference is that I have tested from another place last day , Does it make any sense , I mean the IP address?

I think this is a blocking from stripe server.

**Comment by chr-stripe** [comment]
We think this might be an issue relating to how some device identifiers are persisted by the SDK and potentially backed up by the OS.

The user workaround for this issue right now is unfortunately to delete the app data from the Settings app (_not_ uninstalling and reinstalling the app). We will have a permanent fix for this in version 2.17.0 of the SDK, which should be released by the end of the year.

**Comment by ajithv11** [comment]
@chr-stripe  
It works when I installed the app on other phone with NFC support.
So the issue was  what you said on the above comment, some old app data on my previous installation is causing the issue. 

Unfortunately it still didnt work after clearing app data from settings and install it again on my old developer mobile  Galaxy F23 5G.

Could you please let me know an alternate solution for making it work on same  Galaxy F23 5G, for example some other way of clearing data from mobile

**Comment by ajithv11** [comment]
@chr-stripe  I could fix the issue by Factory Reset Data. It would be good if you could able to explain this case.
Hope this issue might be fixed in version 2.17.0 of the SDK, since factory reset isnt an ideal solution for this case.
Thanks for your response :)

**Comment by chr-stripe** [comment]
Hi @ajithv11, _just_ clearing the app data would have worked. If you installed it again immediately afterwards, it may have restored the original contents if your app manifest contains `android:allowBackup=true`, which would bring back the malformed data. Glad to hear it was indeed solved though, despite with a factory reset.

But yes, in 2.17.0 this will no longer be an issue at all.
