### ISSUE TITLE
BLUETOOTH_PERMISSION_DENIED on Android 12 

### ISSUE THREAD

**Issue by Thamizhan** [stripe/stripe-terminal-android#276]
## Summary
Getting `BLUETOOTH_PERMISSION_DENIED` TerminalException when trying to initialize the SDK.

We recently migrated our app to Andorid 13 and added required permission for Bluetooth

```
     <uses-permission android:name="android.permission.BLUETOOTH" />
     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
     <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```

Also implemented dynamic permission to get Bluetooth permission. But when trying to initialize SDK getting TerminalException with `BLUETOOTH_PERMISSION_DENIED` error code

When I check both location and bluetooth permissions are granted, with this issue we can't complete our setup and test Stripe Terminal in Andorid 12 and 13 devices.

## Code to reproduce
BT Permission handling.
```
permissionLauncher = fragment.registerForActivityResult(new ActivityResultContracts.RequestPermission(), granted -> {
            if (granted)
                initStripeSDK()
        });
permissionLauncher.launch(this.permission);
```

Stripe Initialization
```
if (!Terminal.isInitialized()) {
            try {
                Terminal.initTerminal(SPApp.instance().getApplicationContext(), LogLevel.VERBOSE, new StripeSmartReaderViewModel(), this);
            } catch (TerminalException ex) {
                ex.printStackTrace();
            }
        }
```

## Android version
Android 12 & 13

## Impacted devices (Android devices or readers)
Smart & Bluetooth Readers

## SDK version
2.16.0

## Other information
We also have location permission and location permission is granted and location services are enabled. Same setup was working with targetSdkVersion 30, but getting this error with targetSdkVersion 33.

**Comment by billfinn-stripe** [comment]
Hi @Thamizhan -- I'm not able to reproduce the crash you are seeing with a fresh install of the example Java application. See gif below.

Can you confirm that you don't have the location or Bluetooth settings disabled on your device's settings screen?

I'm testing on Android 12:

```
$ adb shell getprop ro.build.version.sdk
31
```

![2022-12-02_12-46-12 (1)](https://user-images.githubusercontent.com/76448000/205364995-8f4d5a82-332c-4b27-ac83-a515d2caca12.gif)

**Comment by Thamizhan** [comment]
I got it working.
The problem was, I tried only with BLUETOOTH_CONNECT permission, but we need to ask both BLUETOOTH_CONNECT and BLUETOOTH_SCAN permission to make it work. 

Also we need Precise Location, just giving Aproxmiate Location permission still throw Locatin permission error.

I would like these info should be added in the documentation and also in the error message.
