### ISSUE TITLE
Why SDK triggers remove card after cancelling the payment?

### ISSUE THREAD

**Issue by matghazaryan** [stripe/stripe-terminal-android#285]
## Summary
I integrated StripeTerminal into my Android app. Everything is working perfectly. As soon I approached to cancel the payment, I could see something was not working as I expected. 
The issue is when I am canceling the payment, SDK is calling. 

```
class=TerminalStatusManager message=TerminalStatusManager "requestReaderDisplayMessage Remove Card."
23:07:37.856  I  class=ProxyReaderListener message="onRequestReaderDisplayMessage(Remove Card)"
```

At first sight, it seemed okay when I saw this message, but why it required a tap on the reader to proceed with the cancellation?

## Code to reproduce

```
   suspend fun cancelPaymentIntent(paymentIntent: PaymentIntent): PaymentTerminal =
        suspendCancellableCoroutine { continuation ->
            Terminal.getInstance().cancelPaymentIntent(paymentIntent, object : PaymentIntentCallback {
                override fun onFailure(e: TerminalException) {
                    continuation.resume(PaymentTerminal(null, e), null)
                }

                override fun onSuccess(paymentIntent: PaymentIntent) {
                    continuation.resume(PaymentTerminal(paymentIntent, null), null)
                }
            })
        }
```

## Android version

Android 10,11,12,13

## Impacted devices (Android devices or readers)

It appears on Samsung devices that I tested, also on simulators.

## SDK version

`    implementation "com.stripe:stripeterminal:2.16.0"`

## Other information

23:35:23.385  I  class=CrpcClient message="GatorService.reportTrace response={}"
23:35:23.385  V  Sent 4 traces
23:35:23.385  V  Reporting 3 events
23:35:23.385  I  class=CrpcClient message="GatorService.reportEvent request=null"
23:35:23.596  I  class=CrpcClient message="GatorService.reportEvent response={}"
23:35:23.596  V  Sent 3 events
23:35:25.191  D  app_time_stats: avg=181.79ms min=12.57ms max=6962.90ms count=42
23:35:25.232  I  null
23:35:25.242  I  MGMessagePaymentIntentCreate newOrderUUID30ab4fc8-7402-4d67-b6b4-df19b2f37273
23:35:25.242  I  MGMessagePaymentIntentCreate
23:35:25.242  D  KioskPaymentIntentCreate...
23:35:25.243  I  --> POST https://www.example.com/m/stripe/reader/paymentintent/create/
23:35:25.243  I  Content-Type: application/json; charset=UTF-8
23:35:25.243  I  Content-Length: 202
23:35:25.243  I  {"amount":947,"card_id":49609,"apiKey":"5f406b8b375994a85e2f65511a00f294428a0b5d","buildNumber":"20","source":"kiosk","store_id":122,"timezone":"Asia/Yerevan","userId":53673,"versionNumber":"1.0.4-dev"}
23:35:25.243  I  --> END POST (202-byte body)
23:35:25.683  I  <-- 200 OK https://www.example.com/m/stripe/reader/paymentintent/create/ (440ms)
23:35:25.683  I  Date: Mon, 02 Jan 2023 08:56:43 GMT
23:35:25.683  I  Content-Type: application/json
23:35:25.683  I  Transfer-Encoding: chunked
23:35:25.683  I  Connection: keep-alive
23:35:25.683  I  Server: gunicorn/19.9.0
23:35:25.683  I  Vary: Accept, Cookie
23:35:25.683  I  X-Frame-Options: SAMEORIGIN
23:35:25.683  I  Allow: POST, OPTIONS
23:35:25.683  I  Strict-Transport-Security: max-age=31536000; includeSubdomains
23:35:25.684  I  {"paymentintent_id":"pi_3MLjp1LNxtmwejBI1ZYcrRCy","paymentintent_client_secret":"pi_3MLjp1LNxtmwejBI1ZYcrRCy_secret_fJq3T1EuRfXmCnSFbmdlabpNM"}
23:35:25.684  I  <-- END HTTP (143-byte body)
23:35:25.686  I  MGMessagePaymentIntentCreateSuccess
23:35:25.686  D  KioskPaymentIntentCreatedSuccessfully...
23:35:25.689  I  MGMessagePaymentIntentPaymentIntentId=pi_3MLjp1LNxtmwejBI1ZYcrRCy
23:35:25.689  I  MGMessagePaymentIntentPaymentIntentClientSecret=pi_3MLjp1LNxtmwejBI1ZYcrRCy_secret_fJq3T1EuRfXmCnSFbmdlabpNM
23:35:25.689  D  KioskretrievePaymentIntent...
23:35:25.689  D  class=Terminal message=retrievePaymentIntent
23:35:25.690  D  class=ApiClient message=retrievePaymentIntent
23:35:25.691  I  class=RestClient message="url=https://api.stripe.com/v1/payment_intents/pi_3MLjp1LNxtmwejBI1ZYcrRCy request={}"
23:35:26.077  I  REST response with code 200 received
23:35:26.077  I  request-id: req_jNJGF9oM4TWhzD
23:35:26.079  I  class=RestClient message="url=https://api.stripe.com/v1/payment_intents/pi_3MLjp1LNxtmwejBI1ZYcrRCy status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=1509, content-type=application/json, date=Mon, 02 Jan 2023 08:56:44 GMT, idempotency-key=1672601725691CHB20SIMULATOR:145724b9-2f1e-4d81-b121-23511efd03e9Svs1c0iy, request-id=req_jNJGF9oM4TWhzD, server=nginx, strict-transport-security=max-age=63072000; includeSubDomains; preload, stripe-version=2019-02-19} response={"amount":"947","amountCapturable":"0","amountDetails":{"tip":{}},"amountReceived":"0","captureMethod":"manual","charges":{"hasMore":false,"totalCount":0},"clientSecret":"pi_3MLjp1LNxtmwejBI1ZYcrRCy_secret_fJq3T1EuRfXmCnSFbmdlabpNM","created":"1672649803","currency":"usd","description":"Payment for kiosk order:53673","id":"pi_3MLjp1LNxtmwejBI1ZYcrRCy","livemode":false,"metadata":{"app":"kiosk","card_id":"49609","user_id":"53673"},"status":"requires_payment_method"}"
23:35:26.081  I  MGMessageRetrievePaymentIntentSuccess
23:35:26.082  I  MGMessageRetrievePaymentIntentSuccess
23:35:26.082  D  KioskretrievePaymentIntentSuccess...
23:35:26.082  I  MGMessageDiscoverReaders
23:35:26.082  I  MGMessageDiscoverReadersAlreadyHaveReader
23:35:26.082  I  MGMessageHandeIntentStatus=processingCard
23:35:26.082  I  MGMessageCollectPaymentMethod
23:35:26.082  D  KioskCollectMethodStarted
23:35:29.087  D  KioskCollectingMethod...
23:35:29.090  D  class=Terminal message=collectPaymentMethod
23:35:29.093  I  class=TerminalStatusManager message=TerminalStatusManager waitForInput.
23:35:29.093  D  class=ProxyTerminalListener message=onPaymentStatusChange(WAITING_FOR_INPUT)
23:35:29.094  I  class=TerminalStatusManager message=TerminalStatusManager "requestReaderInput Insert / Swipe / Tap."
23:35:29.094  I  class=ProxyReaderListener message="onRequestReaderInput(Insert / Swipe / Tap)"
23:35:29.095  I  MGMessageOnRequestReaderInput=Insert / Swipe / Tap
23:35:29.095  I  MGMessageFragmentHost=PaymentFragment{cf96173} (88b6c173-992a-4816-b954-92360d3afbc2 id=0x7f0901c1)
23:35:29.095  I  MGMessageMessageSentToPaymentFragment
23:35:29.095  I  MGMessageMessagePaymentTitle=Insert / Swipe / Tap
23:35:29.095  I  MGMessageMessagePaymentDesc=
23:35:29.095  I  MGMessageMessagePaymentFinishedInstallation=false
23:35:29.107  D  app_time_stats: avg=150.00ms min=0.98ms max=3496.59ms count=25
23:35:30.114  D  app_time_stats: avg=16.47ms min=8.74ms max=20.63ms count=61
23:35:30.279  W  Expecting binder but got null!
23:35:31.115  D  app_time_stats: avg=5.55ms min=0.97ms max=37.72ms count=60
23:35:31.530  D  app_time_stats: avg=102.48ms min=0.88ms max=1067.62ms count=12
23:35:31.549  I  MGMessageCancelPayment
23:35:31.562  D  endAllActiveAnimators on 0xb40000715912e500 (RippleDrawable) with handle 0xb40000706903b580
23:35:31.566  D  class=Terminal message=cancelPaymentIntent
23:35:32.130  D  app_time_stats: avg=2.45ms min=1.26ms max=8.17ms count=61
23:35:33.096  I  class=TerminalStatusManager message=TerminalStatusManager "requestReaderDisplayMessage Remove Card."
23:35:33.096  I  class=ProxyReaderListener message="onRequestReaderDisplayMessage(Remove Card)"
23:35:33.096  I  MGMessageOnRequestReaderDisplayMessage=Remove Card
23:35:33.096  I  MGMessageFragmentHost=PaymentFragment{cf96173} (88b6c173-992a-4816-b954-92360d3afbc2 id=0x7f0901c1)
23:35:33.096  I  MGMessageMessageSentToPaymentFragment
23:35:33.096  I  MGMessageMessagePaymentTitle=Remove Card
23:35:33.096  I  MGMessageMessagePaymentDesc=
23:35:33.096  I  MGMessageMessagePaymentFinishedInstallation=false
23:35:33.096  D  class=ApiClient message=cancelPaymentIntent
23:35:33.097  D  KioskCollectingMethod...
23:35:33.097  I  MGMessageCollectPaymentMethodSuccess
23:35:33.097  D  KioskCollectingSuccess...
23:35:33.097  I  else
23:35:33.098  I  class=RestClient message="url=https://api.stripe.com/v1/payment_intents/pi_3MLjp1LNxtmwejBI1ZYcrRCy/cancel request={}"
23:35:33.132  D  app_time_stats: avg=2.26ms min=1.14ms max=5.68ms count=60
23:35:33.520  I  REST response with code 200 received
23:35:33.521  I  request-id: req_9qBAxKZXqDsQWm
23:35:33.522  I  class=RestClient message="url=https://api.stripe.com/v1/payment_intents/pi_3MLjp1LNxtmwejBI1ZYcrRCy/cancel status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=1500, content-type=application/json, date=Mon, 02 Jan 2023 08:56:51 GMT, idempotency-key=1672601733099CHB20SIMULATOR:145724b9-2f1e-4d81-b121-23511efd03e95wAgPaRz, original-request=req_9qBAxKZXqDsQWm, request-id=req_9qBAxKZXqDsQWm, server=nginx, strict-transport-security=max-age=63072000; includeSubDomains; preload, stripe-should-retry=false, stripe-version=2019-02-19} response={"amount":"947","amountCapturable":"0","amountDetails":{"tip":{}},"amountReceived":"0","canceledAt":"1672649811","captureMethod":"manual","charges":{"hasMore":false,"totalCount":0},"clientSecret":"pi_3MLjp1LNxtmwejBI1ZYcrRCy_secret_fJq3T1EuRfXmCnSFbmdlabpNM","created":"1672649803","currency":"usd","description":"Payment for kiosk order:53673","id":"pi_3MLjp1LNxtmwejBI1ZYcrRCy","livemode":false,"metadata":{"app":"kiosk","card_id":"49609","user_id":"53673"},"status":"canceled"}"
23:35:33.523  I  MGMessageCancelPaymentSuccess
23:35:33.523  D  Cancel payment intent success

**Comment by billfinn-stripe** [comment]
Hi @matghazaryan -- I think there may be a misunderstanding for how `cancelPaymentIntent` is meant to be used. `cancelPaymentIntent` does the same thing as making [a `/payment_intent/:id/cancel` API request to stripe.com](https://stripe.com/docs/api/payment_intents/cancel). If you are trying to cancel the payment method collection, you should use the [`Cancelable.cancel`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-cancelable/cancel.html) returned from the `collectPaymentMethod`.

To answer your specific question:

> At first sight, it seemed okay when I saw this message, but why it required a tap on the reader to proceed with the cancellation?

The message is telling your integration that it should prompt the user to remove their card. This message may happen if the transaction is canceled, the card has been successfully read, or if the transaction has timed out.

**Comment by matghazaryan** [comment]
Thanks, @billfinn-stripe, for the comment, but I think I am using the right method for canceling the payment because in iOS, I am using the same method, and it's working good. I mean `Terminal.getInstance().cancelPaymentIntent`. 

I am attaching a video for you to be more precise.

When I press a button, you can see that it goes on a standard flow as described in Stripe documentation(createIntent,retreivePaymentIntent, collectPaymentMethod etc). As soon I press the close button on the top left and confirm I want to cancel payment (assuming the user changed his mind) I am calling Terminal.getInstance().cancelPaymentIntent` and I am waiting for a callback to make sure the payment is canceled. You can see cancellation only works as soon as I tap on the reader. 

My question is, why? What am I doing wrong on Android?

Here is the video [link](https://www.dropbox.com/s/tn9168e6sbie60t/IMG_2546.MOV?dl=0)

**Comment by billfinn-stripe** [comment]
Hi @matghazaryan -- to cancel a payment in the event that the user has changed their mind, please use the `Cancelable` returned from `collectPaymentMethod`. Calling `Cancelable.cancel` will issue a command to the reader which will cancel the payment method collection process.

Then, if you would also like to cancel the Payment Intent in the backend, you may also call `Terminal.cancelPaymentIntent`.

**Comment by matghazaryan** [comment]
Thanks so much @billfinn-stripe
