### ISSUE TITLE
must open GPS_PROVIDER？

### ISSUE THREAD

**Issue by mamw** [stripe/stripe-terminal-android#287]
The code in the example application does not work with devices that do not have GPS because the verifyGpsEnabled method will keep the app stuck with the permission dialog.

The SDK does not work on devices that do not have GPS chips ? If not, it might be usefull to change the example code or to mention it in the README.

**Comment by rv-stripe** [comment]
The SDK requires a location provider to be enabled, however this does not need to be the GPS provider. The device may also provide location based on network data. Make sure you have location services enabled on the device in the device's settings to enable this.

**Comment by rv-stripe** [comment]
Ah, I see now that the example application is [requiring](https://github.com/stripe/stripe-terminal-android/blob/78685e605c43ccc28a5ec1f378c17b1f3a912cfd/Example/kotlinapp/src/main/java/com/stripe/example/MainActivity.kt#L372) GPS, though.
I will get the example updated to reflect the SDK's requirements more clearly. Thanks for pointing that out.

In the meantime, know that your implementation may rely on the network location, and does not require GPS so long as location services are enabled on the device.

**Comment by mamw** [comment]
Please help to confirm from which version, this does not need to be the GPS provider.

**Comment by rv-stripe** [comment]
The latest version of the SDK does not require a gps provider, nor does any 2.x version that I am aware of. 
The example application checks for gps, but the SDK itself does not require it.
Apologies for the confusion.

**Comment by mamw** [comment]
Got it, thank you very much.
