### ISSUE TITLE
Terminal SDK is supported to Dynamic Feature Module?

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#302]
I have try to implement but facing lots of issue and bugs like following

**java.lang.NoSuchMethodError: No static method checkNotNullFromProvides(Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions'** 

i have implemented all dependacy 

so it is support to Dynamic Feature Module ?

**Comment by chr-stripe** [comment]
Hi @VijayRathodM, can you please use [our issue template](https://github.com/stripe/stripe-terminal-android/blob/master/.github/ISSUE_TEMPLATE/terminal-android-sdk-issue.md?plain=1) to provide more information on what kind of issue you're running into?
