### ISSUE TITLE
All package the same library 

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#303]
**Summary**

I need implement both SDK for stripe and square reader terminal and  issue is  **all package the same library**

**Code to reproduce**

ext {
    androidx_lifecycle_version = '2.5.1'
    kotlin_coroutines_version = '1.6.4'
    okhttp_version = '4.10.0'
    retrofit_version = '2.9.0'
    stripeTerminalVersion = "2.18.1"
}

dependencies {

 / /Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlin_coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlin_coroutines_version"

    // OK HTTP
    implementation "com.squareup.okhttp3:okhttp:$okhttp_version"

    // Retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"

    // Stripe Terminal library
    implementation "com.stripe:stripeterminal:$stripeTerminalVersion"

    //Square Reader 
    def readerSdkVersion = "1.7.4"
    implementation "com.squareup.sdk.reader:reader-sdk-$SQUARE_READER_SDK_APPLICATION_ID:$readerSdkVersion"
    runtimeOnly("com.squareup.sdk.reader:reader-sdk-internals:$readerSdkVersion")
}

**Android version**
Project not running runtime error in All Version

**SDK version**

Stripe : 2.18.1
Square Reader : 1.7.4

**Other information**

I need both use stripe and square reader so issue is library conflict . how to solve and run both SDK

**Comment by chr-stripe** [comment]
Hi @VijayRathodM, can you post the stacktrace of the runtime error you're seeing occur?

**Comment by VijayRathodM** [comment]
> Hi @VijayRathodM, can you post the stacktrace of the runtime error you're seeing occur?

**Note : I have implement all module as Dynamic Feature Module**

Execution failed for task ':app:checkSampleProjectDebugLibraries'.
> [:SquareDynamicModule, :StripeDynamicModule] all package the same library [androidx.lifecycle:lifecycle-livedata-core-ktx].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [androidx.lifecycle:lifecycle-livedata-ktx].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [androidx.security:security-crypto].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.google.crypto.tink:tink-android].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.moshi:moshi].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.moshi:moshi-adapters].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.retrofit2:adapter-rxjava2].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.retrofit2:converter-gson].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.retrofit2:retrofit].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [com.squareup.wire:wire-runtime-jvm].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [io.reactivex.rxjava2:rxjava].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [org.jetbrains.kotlin:kotlin-parcelize-runtime].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [org.jetbrains.kotlinx:kotlinx-coroutines-reactive].
  [:SquareDynamicModule, :StripeDynamicModule] all package the same library [org.reactivestreams:reactive-streams].

**Comment by VijayRathodM** [comment]
Please any suggestions or response

**Comment by chr-stripe** [comment]
Going to close this ticket due to inactivity, but @VijayRathodM please feel free to let me know if this solution works for you!
