### ISSUE TITLE
The Stripe Terminal ConnectionToken has already been redeemed

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#304]
Hi,

I am struck with the error as follows
`The Stripe Terminal ConnectionToken has already been redeemed. Please generate a new one using v1/terminal/connection_tokens.`
It happens when I close tap to pay white screen. The app retains its old screen but , I cannot initiate tap again, If goes to a dead state.

How can i get rid of this issue?

**Comment by rv-stripe** [comment]
This is typically an issue with the `fetchConnectionToken` implementation. Can you verify that the android code is calling your backend for a new connection token each time the callback is invoked. Verify that the code is not caching or storing the connection token when it does this. 
The backend implementation should not cache or store this token either and should call stripe `v1/terminal/connection_tokens` endpoint upon each call. Please verify this as well.

More info can be found at this [example].

[example]: https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=android#connection-token-client-side

**Comment by Mr-Sudharsan** [comment]
I tried, But I don't know how to change the connection-token without recalling Terminal.initTerminal();

**Comment by chr-stripe** [comment]
@Mr-Sudharsan there's no need to call `Terminal.initTerminal()` again. The Terminal SDK will automatically request a new connection token from your `ConnectionTokenProvider` implementation when it needs to – you just need to ensure that your implementation always returns a new, fresh connection token when it's invoked.

**Comment by jorgtz** [comment]
I got a similar case, the code actually calls for the new token and receives it but for some strange reason, the `fetchConnectionToken` callback is receiving the old and used token, so that's why I got the error. I have checked and I am only assigning the mStripeToken in one place, but this callback is not using the new value. Any suggestions ?
Thanks!
