### ISSUE TITLE
The Stripe Terminal ConnectionToken has already been redeemed. Please generate a new one using v1/terminal/connection_tokens.

### ISSUE THREAD

**Issue by Mr-Sudharsan** [stripe/stripe-terminal-android#308]
Hi, this shows even I disconnect the reader. this will be solved only when killing the app opens again. I'm using Android SDK 2.18.0

**Comment by chr-stripe** [comment]
Hi @Mr-Sudharsan, it looks like you're reporting a duplicate of #304. Can you try the suggestions [in this comment](https://github.com/stripe/stripe-terminal-android/issues/304#issuecomment-1482788628) and let me know if that solves this issue for you?

**Comment by chr-stripe** [comment]
Closing as duplicate.
