### ISSUE TITLE
Generated Card ID is not returned in SDK

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#31]
When processing a payment the stripe documentation says the following here.

https://stripe.com/docs/terminal/payments/saving-cards#saving-payment-intent-card

> Save card details for online reuse from a customer’s in-person transaction. When you successfully process a PaymentIntent, the returned object contains a list of attempted charges in reverse chronological order—so the first is the successful one. This charge contains a generated_card ID.

However when actually processing a payment the generated card id is not returned via the SDK.

`
   public static class CardPresentDetails {
        private String brand;
        private String country;
        @SerializedName("emv_auth_data")
        private String emvAuthData;
        @SerializedName("exp_month")
        private int expMonth;
        @SerializedName("exp_year")
        private int expYear;
        private String fingerprint;
        private String last4;
        private PaymentMethodDetails.ReceiptDetails receipt;
`

**Comment by danwaters-stripe** [comment]
Looks like our documentation got out of sync with the Android SDK on this one. A `generatedCard` field has been added to the `CardPresentDetails` object and will be available in the next SDK release.

**Comment by danwaters-stripe** [comment]
Version 1.0.0-b4 has been released with support for generatedCard.
