### ISSUE TITLE
There is a 50% chance that the device cannot recognize the Discover bank card payment in Apple pay.

### ISSUE THREAD

**Issue by jia748961024** [stripe/stripe-terminal-android#316]
Device:M2
Version:2.01.00.16-SZZZ_Prod_US_v1-480001, 100
When a customer pays with the Discover bank card in Apple Pay, there is a certain chance that the device will not be able to recognize the payment device and cannot perform the reading operation, and will always “WAITING_FOR_INPUT”. Is there any special configuration for this?

**Comment by chr-stripe** [comment]
Hi @jia748961024, thanks for the report. Can you please use [our issue template](https://github.com/stripe/stripe-terminal-android/blob/master/.github/ISSUE_TEMPLATE/terminal-android-sdk-issue.md?plain=1) to provide more information on what kind of issue you're running into? If you're able to provide a serial number that would be greatly appreciated!

**Comment by jia748961024** [comment]
the device cannot recognize the Discover bank card payment in Apple pay

## Android version
Android 9

Device:M2
Serial Numer: STRM26232029849

SDK Version:
"com.stripe:stripeterminal:2.16.0"
"com.stripe:stripeterminal-localmobile:2.16.0"
 "com.stripe:stripeterminal-core:2.16.0"

M2 Version:
2.01.00.16-SZZZ_Prod_US_v1-480001, 100

**Comment by chr-stripe** [comment]
I looks like this is a known issue (specifically Discover cards stored in Apple Pay) and is being tracked internally. I'll update this thread if there are any developments here.

**Comment by chr-stripe** [comment]
We just released version `3.3.0` which should contain the fix for this issue on Chipper 2X and M2 readers. Discover cards stored via Apple Pay should now be able to be processed without issue on those readers.

We will follow up at a future date with a fix for WisePad 3 readers.
