### ISSUE TITLE
Reader updated failed for unknown reason.

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#32]
We get the following error when attempting to update the reader.

`e = {TerminalException@7553} "com.stripe.stripeterminal.TerminalException"
 apiError = null
 errorCode = {TerminalException$TerminalErrorCode@7949} "READER_SOFTWARE_UPDATE_FAILED(380)"
 errorMessage = "Update failed for unknown reason"
 cause = {TerminalException@7553} "com.stripe.stripeterminal.TerminalException"
 detailMessage = null
 stackState = null
 stackTrace = {StackTraceElement[10]@7951} 
 suppressedExceptions = {Collections$EmptyList@7952}  size = 0
 shadow$_klass_ = {Class@868} "class com.stripe.stripeterminal.TerminalException"
 shadow$_monitor_ = -1329362584
`

`e.getStackTrace() = {StackTraceElement[10]@7994} 
 0 = {StackTraceElement@7995} "com.stripe.stripeterminal.BbposDeviceOtaControllerListener.onReturnTargetVersionResult(BbposDeviceOtaControllerListener.java:94)"
 1 = {StackTraceElement@7996} "com.bbposstripe.bbdevice.ota.BBDeviceOTAController$10.run(SourceFile:157)"
 2 = {StackTraceElement@7997} "android.os.Handler.handleCallback(Handler.java:815)"
 3 = {StackTraceElement@7998} "android.os.Handler.dispatchMessage(Handler.java:104)"
 4 = {StackTraceElement@7999} "android.os.Looper.loop(Looper.java:194)"
 5 = {StackTraceElement@8000} "android.app.ActivityThread.main(ActivityThread.java:5637)"
 6 = {StackTraceElement@8001} "java.lang.reflect.Method.invoke(Native Method)"
 7 = {StackTraceElement@8002} "java.lang.reflect.Method.invoke(Method.java:372)"
 8 = {StackTraceElement@8003} "com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)"
 9 = {StackTraceElement@8004} "com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)"`

Code block below:
```
public void tryToConnect() {
        presenter = this;

        Terminal terminal = getTerminal(application);

        if(terminal != null) {
            Reader connectedReader = terminal.getConnectedReader();
            if(connectedReader == null) {
                getViewState().showLoading();
                getViewState().showStatus(application.getString(R.string.init_sdk));
                try {
                    getViewState().showStatus("Discovering readers");

                    subscriptions.add(readersSubject
                            .subscribeOn(Schedulers.from(m_OtherWorkThreadPool))
                            .observeOn(AndroidSchedulers.mainThread())
                            .subscribe(
                                    reader -> {
                                        subscriptions.add(
                                            connectionSubject
                                                .subscribeOn(Schedulers.from(m_OtherWorkThreadPool))
                                                .observeOn(AndroidSchedulers.mainThread())
                                                .subscribe(
                                                      connected -> {
                                                          READER_CONNECTED = true;
                                                          getViewState().showStatus("Checking updates");
                                                          currentCancelable = terminal.checkForUpdate(new SoftwareCallback(reader, terminal));
                                                      } , error -> getViewState().showErrorMessage(error.getMessage())
                                                )
                                        );
                                        terminal.connectReader(reader, new ConnectionCallback());
                                    }, error -> getViewState().showErrorMessage(error.getMessage())
                            ));

                    currentCancelable = terminal.discoverReaders(new DiscoveryConfiguration(0, DeviceType.CHIPPER_2X, false),
                            new ReaderDiscoveryListener(), new DiscoveryCallback());

                } catch (Exception e) {
                    getViewState().showErrorMessage(e.getMessage());
                }
            } else {
                READER_CONNECTED = true;
                getViewState().showConnected(connectedReader.getSerialNumber());
                if(AUTO_CONNECT) {
                    getViewState().exit();
                }
            }
        } else {
            getViewState().showErrorMessage("Initializing stripe failed");
        }
    }
```

**Comment by anton8900** [comment]
I am trying to update reader when it connected and this error occures. Exception and stack trace in comment above

**Comment by anton8900** [comment]
I am trying to check update for reader when it connected and this error returned in callback. Exception and stack trace in comment above

**Comment by danwaters-stripe** [comment]
Just noting that we're continuing to look into this issue and will update once we understand what's happening.

**Comment by anton8900** [comment]
With 1.0.0-b4 exception the same. 
I am using phone Land Rover X8 Android 5.1. 
Every check for update return this error
Testing environment

**Comment by SharathKaribasappaGB** [comment]
i am observing this issue every time i call the method "Terminal.getInstance().checkForUpdate".
Have observed this issue in the example app as well.
Testing on version 1.0.0-b5, same issue is there in 1.0.0-b4 as well.
Serial number: CHB204832000496, CHB204744003340

**Comment by danwaters-stripe** [comment]
Apologies for the long delay on this one. We were finally able to replicate the problem and made a backend change that fixed it for our devices. Let me know if you're able to test and confirm that the fix worked for you too.

**Comment by chander-stripe** [comment]
Hi @legomanaustralia , @SharathKaribasappaGB and @anton8900 - we've just released our latest release candidate. Please let us know if this issue continues to persist on RC1. Thanks!
