### ISSUE TITLE
UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR

### ISSUE THREAD

**Issue by L-is-0** [stripe/stripe-terminal-android#326]
## Summary
terminal tap to pay, getting UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR

## Code to reproduce
We have reported this issue before, but got reply saying this issue only happens if the app is not in foreground, so we added a check in our code to printout app foreground status when this issue came up. However, in the logs we can still see this issue presents even appforeground is true. Could you please kindly advise on this regarding what is the cause of this and how we can resolve it?

## Android version
Android 11

## Impacted devices (Android devices or readers)
Simulated Reader - tap to pay

## Other information
here is the logs from our code:

Tue May 16 09:57:45 GMT+01:00 2023 ContactlessPaymentUtil-1101 retrieving payment intent...
Tue May 16 09:57:45 GMT+01:00 2023 BaseActivity-1101 adjustedBrightness is : 255
Tue May 16 09:57:45 GMT+01:00 2023 TokenProvider-1101 fetchConnectionToken...
Tue May 16 09:57:45 GMT+01:00 2023 AwsApiManager-1101 New request:
URL: /getConnectionToken
Type: GET
Async: false
Auth: true
JSON: null
Tue May 16 09:57:47 GMT+01:00 2023 apiEndpoint-1101 onSuccess: Response{protocol=h2, code=200, message=, /stripe/getConnectionToken}
Tue May 16 09:57:47 GMT+01:00 2023 TokenProvider-1101 fetchConnectionToken successful
Tue May 16 09:57:47 GMT+01:00 2023 TokenProvider-1101 generated token secret 
Tue May 16 09:57:47 GMT+01:00 2023 ContactlessPaymentUtil-1101 retrievePaymentIntent success
Tue May 16 09:57:47 GMT+01:00 2023 StripeUseCase-1101 generated payment intent at: 2023-05-16 09:57:47
Tue May 16 10:00:38 GMT+01:00 2023 ConnectionStatusChange-1101 READY
Tue May 16 10:00:38 GMT+01:00 2023 ContactlessPaymentUtil-1101 collectPayment() onFailure - exception: UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR
Tue May 16 10:00:38 GMT+01:00 2023 BaseActivity-1101 isAppOnForeground true
URL: /ttintegrations/getErr
Type: POST
Async: true
Auth: true
JSON: {"appforeground":true,"deviceid":"907904","error_code":"UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR","integration":"stripe","message":"Contactless transaction failed java.lang.IllegalStateException: App Error: INVALID_REQUEST \u0027Failed to parse request with error Job was cancelled\u0027.","step":"payment","tableid":28}

**Comment by maggiewhite-stripe** [comment]
@L-is-0 There is information about how to handle unexpected disconnects in our public documentation here:
> To get started, provide the current application context, the [ConnectionTokenProvider](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-connection-token-provider/index.html) implemented in [Step 3](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=android#connection-token), and a [TerminalListener](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-terminal-listener/index.html) object. You can use this listener to handle events from the SDK, such as disconnects. For more information, see [Handling disconnects](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=bluetooth#handling-disconnects).

https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=android#initialize

There's more information here about how to handle unexpected disconnects, but unfortunately it's bluetooth specific:
https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=bluetooth#handling-disconnects

Step 1 is relevant to Tap to Pay but Step 2 is not.

**Comment by L-is-0** [comment]
Hi @maggiewhite-stripe , any chance you can help on this one?

**Comment by L-is-0** [comment]
Hi @maggiewhite-stripe, we are still encountering this issue in the latest SDK 2.21.1. Could you please kindly advise on how we could resolve the problem?

**Comment by L-is-0** [comment]
Hi @rv-stripe we are still having this issue when updated to the latest SDK, could you please advise on how we could resolve the problem?

**Comment by L-is-0** [comment]
Hello @maggiewhite-stripe @rv-stripe,  we managed to get more logs for this error, would you please be able to advise is there anything we could do to resolve it as we are still getting the same issue on daily basis.

here is the logs we have "Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Service never connected."

`Thu Aug 10 11:16:36 GMT+01:00 2023 StatusBarHelper-2901 app discharged from charging
Thu Aug 10 11:16:36 GMT+01:00 2023 MainApplication-2901 isAppOnForeground true
Thu Aug 10 11:16:36 GMT+01:00 2023 TerminalReaderService-2901 connect() - reader not connected
Thu Aug 10 11:17:36 GMT+01:00 2023 TerminalReaderService-2901 discoverSimulatedReader failure: Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Service never connected.
Thu Aug 10 11:17:36 GMT+01:00 2023 AwsApiManager-2901 New request:
URL: /v2/ttintegrations/getErr
Type: POST
Async: true
Auth: true
JSON: {"appforeground":true,"deviceid":"900384","error_code":"UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR","integration":"stripe","message":"Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Service never connected.","sessionid":"29963","step":"discharge","tableid":27}
`

**Comment by L-is-0** [comment]
Hi @rv-stripe could you please kindly provide any suggestion to this issue?

**Comment by nazli-stripe** [comment]
hey @L-is-0 are you still running into this issue on the latest SDK version?

**Comment by billfinn-stripe** [comment]
I'm going to close this due to inactivity. Feel free to reopen if it's still an issue.
