### ISSUE TITLE
Problem with readReausableCard

### ISSUE THREAD

**Issue by przemek9x9** [stripe/stripe-terminal-android#33]
we are facing problem with readReusableCard: 

> Payment was declined by reader ---> PAYMENT_DECLINED_BY_READER(650)

reader is previously detected and connected.
MWE:
`
public void createReusableCard() {
    ReadReusableCardParameters params = new ReadReusableCardParameters.Builder().build();
    cancelable = terminal.readReusableCard(params, new ReaderListener(), new PaymentMethodCallback() {
      @Override
      public void onSuccess(PaymentMethod paymentMethod) {
        Log.i("FIND_ME", paymentMethod.getId());
      }
      @Override
      public void onFailure(@Nonnull TerminalException e) {
        Log.i("FIND_ME", "error: " + e.getErrorMessage() + " ---> " + e.getErrorCode().toString());
      }
    });
  }
`

**Comment by danwaters-stripe** [comment]
Hi,

Thanks for the report. We found a bug in the SDK that is causing the behavior you're seeing. We'll be sure to include a fix in the next release.

**Comment by danwaters-stripe** [comment]
Release 1.0.0-b4 includes a fix for this issue.
