### ISSUE TITLE
Tap to pay on NFC enabled mobile phone shows TAP TO SIMULATE PAYMENT screen always instead on waiting for real card

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#330]
Hi,
Tap to pay on NFC supporting  mobile phone shows **TAP TO SIMULATE PAYMENT** screen always instead of waiting for real card, It happens when I update stripe terminal version to **2.20.1**. The code used is given below

       if (discoveryTask == null && Terminal.getInstance().connectedReader == null) {
            val config = DiscoveryConfiguration(
                timeout = 0,
                discoveryMethod = DiscoveryMethod.LOCAL_MOBILE,
                isSimulated = true,
                location = Constants.LOCATIONID
            )
            discoveryTask = Terminal.getInstance().discoverReaders(config,
                discoveryListener = object : DiscoveryListener {
                override fun onUpdateDiscoveredReaders(readers: List<Reader>) {

                    val firstReader = readers.first();
                    this@TapViewModel.reader.postValue(firstReader);
                    val config = ConnectionConfiguration.LocalMobileConnectionConfiguration(Constants.LOCATIONID);
                    Terminal.getInstance().connectLocalMobileReader(firstReader, config,
                        
                        object : ReaderCallback {

                            override fun onSuccess(reader: Reader) {
                                val params = PaymentIntentParameters.Builder().setAmount(amt*100).setCurrency(Constants.CURRENCY).build();
                                Terminal.getInstance().createPaymentIntent(params, object: PaymentIntentCallback {
                                    override fun onSuccess(paymentIntent: PaymentIntent) {
                                        val collectConfig = CollectConfiguration.Builder().updatePaymentIntent(true).build();
                                        val cancelable = Terminal.getInstance().collectPaymentMethod(paymentIntent,
                                            object : PaymentIntentCallback {
                                                override fun onSuccess(paymentIntent: PaymentIntent) {

                                                    Log.d("Response Tap", "paymentIntent Before : "+paymentIntent.id)

                                                    Terminal.getInstance().processPayment(paymentIntent, object :
                                                        PaymentIntentCallback {
                                                        override fun onSuccess(paymentIntent: PaymentIntent) {
                                                            // Placeholder for notifying your backend to capture paymentIntent.id TODO
                                                            Log.d("Response Tap", "paymentIntent Success : "+paymentIntent.id)
                                                            
                                                        }

                                                        override fun onFailure(exception: TerminalException) {
                                                            Log.d("Response Tap", "paymentIntent Error : "+paymentIntent.id)
                                                            
                                                        }
                                                    })
                                                }

                                                override fun onFailure(exception: TerminalException) {
                                                    Log.d("Response Tap", "paymentIntent Error : "+exception.errorMessage )
                                                }
                                            })

                                    }
                                    override fun onFailure(exception: TerminalException) {
                                        Log.d("Response Tap", "paymentIntent Error : "+exception.errorMessage )
                                    }
                                })
                            }
                            override fun onFailure(e: TerminalException) {
                                Log.d("Response Tap", "paymentIntent Error : "+e.errorMessage )
                            }
                        });
                }
                },
                object : Callback {
                    override fun onSuccess() {
                        discoveryTask = null
                        //Log.d("Response Tap", "Readers Discovered Success!");
                    }
                    override fun onFailure(e: TerminalException) {
                        discoveryTask = null
                        Log.d("Response Tap", "Reader Discovery Failed : " + e.errorMessage);
                         
                    }
                })
        }

Do I need to change anything on the above code for making tap card enabled? It was working and wait for real card on version **2.17.1**

**Screenshot of version 2.17.1 which if fine**

![Screenshot_20221124-174019_SiftDonate](https://github.com/stripe/stripe-terminal-android/assets/22443417/1b9f0267-677f-4743-907b-d33610a828e2)

**Screenshot of version 2.20.1 : Issue I need real tap card here**
![Screenshot_20230523_194632_SwiftDonate](https://github.com/stripe/stripe-terminal-android/assets/22443417/669bf042-c23f-4f95-97dd-77a297a03f17)

Same happens on both stripe test mode and live mode

**Comment by rscherf** [comment]
It appears that you have set:

```
isSimulated = true
```

I imagine this should be set to `false`.

**Comment by ajithv11** [comment]
@rscherf  You said it :) Thanks a lot

So I believe in previous version, There is no simulation option in LocalMobileConnection, In the later version **2.20.1** simulation is available, so the **isSimulated = true** comes into effect.

**Comment by maggiewhite-stripe** [comment]
Thanks @rscherf!

@ajithv11 Yes, we added support for the simulated Tap to Pay reader in 2.18.1:
https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2181---2023-03-15
