### ISSUE TITLE
getBatteryLevel return null

### ISSUE THREAD

**Issue by YevgeniiHolub** [stripe/stripe-terminal-android#334]
Since we updated sdk version from 2.18.1 to latest we have an issue with battery level. 
getBatteryLevel () return null instead of battery level

## Code to reproduce
Terminal.getInstance().getConnectedReader().getBatteryLevel();

## SDK version
"com.stripe:stripeterminal:2.19.0"

## Other information
Last worked version "com.stripe:stripeterminal:2.18.1"

**Comment by chr-stripe** [comment]
Duplicate of https://github.com/stripe/stripe-terminal-android/issues/310
