### ISSUE TITLE
UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR

### ISSUE THREAD

**Issue by MuradBajwa** [stripe/stripe-terminal-android#335]
## Summary
28 UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR's experienced over the bank holiday weekend (26/05/2023 to 29/05/2023) through the terminal tap to pay.

Contactless transaction failed java.lang.IllegalStateException: App Error: INVALID_REQUEST 'Failed to parse request with error Job was cancelled'.

## Android version
Android version 11

## Impacted devices (Android devices or readers)
Simulated Reader - tap to pay
We are experiencing these errors on the following device ids:
907910
907867

## SDK version
2.16.0-b1

**Comment by bperez-stripe** [comment]
@MuradBajwa is this still an issue? Can you try this again with an updated SDK version?

**Comment by dmatthews-stripe** [comment]
Hi @MuradBajwa. We will be archiving this ticket due to inactivity. Please feel free to reopen if this happens again!
