### ISSUE TITLE
INTEGRATION_ERROR.NOT_CONNECTED_TO_READER

### ISSUE THREAD

**Issue by MuradBajwa** [stripe/stripe-terminal-android#336]
## Summary
71 INTEGRATION_ERROR.NOT_CONNECTED_TO_READER over the bank holiday weekend (26/05/2023 to 29/05/2023).

## Android version
Android version 11

## Impacted devices (Android devices or readers)
Simulated Reader - tap to pay
We are experiencing these errors on the following device ids:
907868
907880
907919
907961
908359
908370

## SDK version
2.16.0-b1

## Other information
example message
{"appforeground":true,"deviceid":"907961","error_code":"INTEGRATION_ERROR.NOT_CONNECTED_TO_READER","integration":"stripe","message":"LocalMobile reader is not connected","step":"payment","tableid":17}

**Comment by maggiewhite-stripe** [comment]
Hi @MuradBajwa, this looks like the same issue as this issue:
https://github.com/stripe/stripe-terminal-android/issues/327

Please take a look at the suggestions there, and let me know if that resolves your issue.

**Comment by maggiewhite-stripe** [comment]
Closing since this issue hasn't gotten a response in 3 weeks.
