### ISSUE TITLE
Location Services Not Being Detected

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#34]
We're seeing a strange occurrence where we attempt to process a payment and the stripe library returns an error stating that we must enable location services, when we're clearly running location service and requesting both coarse and fine locations.

it takes restarting the application and turning off location services a number of times in order for the reader to accept the payment, however once it does the first payment after that it seems just fine.

It doesn't appear to be limited to one make or model, we've tried it on a half dozen in our lab and seeing consistent issues.

It only appears to be this latest 1.00+ range that was affected up till then it's worked just fine.

**Comment by danwaters-stripe** [comment]
Thanks for the report. I just made a couple changes that should make location handling more consistent. Let me know if you still see any issues in our next release.

**Comment by danwaters-stripe** [comment]
1.0.0-b4 includes a number of improvements that should address this issue. Let me know if you continue to see problems!
