### ISSUE TITLE
invalid_request_error

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#340]
## Summary
Check this following error message from stipe api

**{
  "error": {
    "message": "You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}**

## Code to reproduce
 I will split payment  first transaction is completed and after the new transaction to get this terminal SDK error 

## Android version
12 

## Impacted devices (Android devices or readers)
No

## SDK version
implementation "com.stripe:stripeterminal:2.21.0"

**Comment by L-is-0** [comment]
hi @VijayRathodM I am getting the same error, did you have it resolved?

**Comment by VijayRathodM** [comment]
Yes @L-is-0  I resolve it 

**Terminal.getInstance().clearCachedCredentials()** remove it because it refresh and generate new toke so be careful to use it
