### ISSUE TITLE
After upgrading to the latest SDK, there is no permission to connect to M2.

### ISSUE THREAD

**Issue by JessieLau-CT** [stripe/stripe-terminal-android#341]
## Summary
Hi. I have encountered a situation similar to this problem. (https://github.com/stripe/stripe-terminal-android/issues/290). 
To solve this problem, I upgraded to the latest SDK(2.21.0). However, an error message appeared stating that I didn't have permission to connect to the device. The console showed that the device was connected but immediately disconnected, and then the following error was reported.
<img width="567" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/59676668/cf120279-ddcd-4a5e-b651-44f85c29e20e">
<img width="931" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/59676668/8cb3eb6b-df93-4a8a-b69e-786813d04fbe">

## Android version
Android 10

## Impacted devices (Android devices or readers)
M2 serial number: STRM26142036028

## SDK version
React-native: 0.66.5
@stripe/stripe-terminal-react-native: 0.0.1-beta.12
Android terminal SDK: 2.21.0

**Comment by billfinn-stripe** [comment]
If you are integrating using the React Native SDK, can you please move this issue to https://github.com/stripe/stripe-terminal-react-native/issues?

From the description, it's not clear which SDK you are integrating with. You have listed both React Native and Terminal SDK. If you are integrating with React Native, please only depend on the React Native SDK.

**Comment by chr-stripe** [comment]
From the description it also looks like you're attempting to connect to your reader via USB, given the error message you are receiving upon connection:

> To request access to this beta feature, please contact us at stripe-terminal-betas@stripe.com.

You are encouraged to reach out to that email, and someone will assist you in getting your developer account opted into this beta feature.

**Comment by JessieLau-CT** [comment]
@chr-stripe I previously contacted beta support and they told me to create an issue on GitHub. I will contact them again. Thank you for your reply.

**Comment by JessieLau-CT** [comment]
@billfinn-stripe Hi. I previously used RN SDK version 0.0.1-beta.11, and the Android SDK version under this version was 2.14.0. However, I encountered a similar issue#290, so I upgraded the RN SDK to 0.0.1-beta.12 and the Android SDK patch to 2.21.0. So I think this is android terminal SDK issue.
