### ISSUE TITLE
Stuck when connecting to BT Reader with low battery

### ISSUE THREAD

**Issue by jasells** [stripe/stripe-terminal-android#343]
## Summary

When connecting to a reader with critically low battery (~ or < 10%), the SDK gets stuck in an un-recoverable state where the `ConnectBluetoothReader()` call never completes, and `DiscoverBluetootherReaders()` never times out.  The `BluetoothReaderListener.onReportLowBatteryWarning()` callback is called, but nothing else happens after that (discover/connect never complete with any callback error or otherwise).  

IFF application code cancels the current `discoverReaders()` call upon receiving the `onReportLowBatteryWarning` callback, Things are ok, until ~5% battery at which point even after cancelling the discovery call, any future calls to `discoverReaders()` will never complete or timeout, even when canceled by application code.

If the reader is powered down while the SDK is in this "Stuck" state, the `onUnexpectedReaderDisconnect` callback is invoked, and the SDK returns to normal operating behavior.

## Android version

13

## Impacted devices (Android devices or readers)

Pixel 4
Stripe M2 Reader (BT)

## SDK version
2.20.0

## Other information
Seems possibly related to #313

`discoverReaders()` and/or `connectBluetoothReader()` should return error in callback at some point (within the normal 5-8 second time window) in this case?  At least, `discoverReaders()` should return timeout?

The iOS SDK returns an error immediately from the equivalent of `connectBluetoothReader()` callback when battery ~<=10%.

**Comment by TatsuUkraine** [comment]
it seems the same issue exists in v3.1

**Comment by chr-stripe** [comment]
Hi all, we've looked into this some more and identified a fix for the issue. We're planning to land this in the upcoming 3.3.0 SDK release. It will be called out in the release notes when it's launched but I'll also update this thread once it's available.

**Comment by chr-stripe** [comment]
Hi all, we just released version `3.3.0` which should contain the fix for this issue. Attempting to connect or use a reader with a critically low battery will result in an automatic disconnection, and a [READER_BATTERY_CRITICALLY_LOW](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-terminal-exception/-terminal-error-code/-r-e-a-d-e-r_-b-a-t-t-e-r-y_-c-r-i-t-i-c-a-l-l-y_-l-o-w/index.html) exception will be thrown.
