### ISSUE TITLE
`discoverReaders` callback never seems to get called, can't discover twice

### ISSUE THREAD

**Issue by atrauzzi** [stripe/stripe-terminal-android#345]
## Summary
According to [the documentation](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-to-pay#discover-readers) for [discoverReaders](https://stripe.dev/stripe-terminal-android/core/com.stripe.stripeterminal/-terminal/discover-readers.html), there are two callback mechanisms at play:

![image](https://github.com/stripe/stripe-terminal-android/assets/115199/57903ecc-dbd2-4693-a72e-7ed668240898)

One is the `DiscoveryListener` and the other is a simple callback which doesn't return any value on success.

Based on what I understand, this has two implications for the lifecycle when discovering local devices:

 - I can only discover once as if I call a second time, `onUpdateDiscoveredReaders` is never called, on account of the fact that they haven't _changed_ since the last invocation
 - The second callback is really kind of pointless?

## Code to reproduce

I've created the following class in my project to make the Stripe Terminal discovery process more...suspense-ful :laughing: :

```kotlin
suspend fun Terminal.discoverReaders(stripeTerminalConfiguration: DiscoveryConfiguration): List<Reader> = suspendCoroutine { continuation ->

    var lastReaders: List<Reader>? = null
    lateinit var something: Cancelable

    val dummyCallback = object : Callback {
        override fun onFailure(e: TerminalException) {
        }
        override fun onSuccess() {
        }
    }

    something = discoverReaders(
        stripeTerminalConfiguration,
        object : DiscoveryListener {
            override fun onUpdateDiscoveredReaders(readers: List<Reader>) {

                lastReaders = readers

                something.cancel(dummyCallback)

                continuation.resume(readers)
            }
        },
        object : Callback {
            override fun onFailure(e: TerminalException) {
                continuation.resumeWithException(e)
            }

            override fun onSuccess() {

                something.cancel(dummyCallback)

                continuation.resume(lastReaders!!)
            }
        }
    )
}
```

## Other information
I guess this is just a weird lifecycle setup because if I want to call device discovery twice, I can't as the SDK refuses to call `onUpdateDiscoveredReaders` twice?

**Comment by billfinn-stripe** [comment]
Yes, I think it's a weird lifecycle setup as you point out. If you want to call `discoverReaders` multiple times, you can:

1. Cancel the first `discoverReaders` call (by calling `Cancelable::cancel` on the returned `Cancelable`) before calling `discoverReaders` again; or
2. Set a `timeout` in the `DiscoveryConfiguration`. This timeout is only respected for Bluetooth and USB readers. For IP readers, the discover operations makes a single HTTP request to list the readers registered to your account.
