### ISSUE TITLE
Stripe Version in Android terminal SDK 

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#347]
require 'stripe'
intent = Stripe::PaymentIntent.retrieve(
  'pi_1DlIVK2eZvKYlo2123456789,
  {
    stripe_version: '2022-11-15',
  }
)
intent.capture

how to set **stripe_version: '2022-02-19',**  in android terminal sdk

**Comment by chr-stripe** [comment]
Hi @VijayRathodM, if you are having an issue using the Stripe Ruby SDK please file that issue in the repository for that SDK here: https://github.com/stripe/stripe-ruby
