### ISSUE TITLE
Stripe localmobile 2.22.0 leads to build errors

### ISSUE THREAD

**Issue by TatsuUkraine** [stripe/stripe-terminal-android#349]
## Summary
After updating localmobile deps to 2.22.0 Android build fails with an error
```
Duplicate class org.bouncycastle.jce.provider.BouncyCastleProvider found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-stripeterminal-localmobile-2.22.0-runtime (com.stripe:stripeterminal-localmobile:2.22.0)
Duplicate class org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-stripeterminal-localmobile-2.22.0-runtime (com.stripe:stripeterminal-localmobile:2.22.0)
```

## SDK version
2.22.0

## Other information
In the app we have Stripe Terminal SDK and Stripe SDK.
All works fine with v2.21.*

**Comment by rv-stripe** [comment]
@TatsuUkraine Are you able to reproduce this issue in our example application and provide the full error?

**Comment by TatsuUkraine** [comment]
@rv-stripe you just need to install Stripe SDK alongside with Stripe Terminal SDK

**Comment by rv-stripe** [comment]
We're tracking this and should have a fix for the next release.

**Comment by TatsuUkraine** [comment]
Thanks you!

**Comment by yogen-p** [comment]
Eagerly waiting for this to be fixed 🤞🏼

**Comment by rv-stripe** [comment]
This issue should be fixed in the latest release. Please let me know if you still have issues.

**Comment by TatsuUkraine** [comment]
Yep, sorry, forgot to close it. Thank you!
