### ISSUE TITLE
Can I connect to reader over USB. with empty location ID , I mean make the reader not restricted to location

### ISSUE THREAD

**Issue by msoliman22** [stripe/stripe-terminal-android#352]
Can I connect to reader over USB. with empty location ID , I mean make the reader not restricted to location

**Comment by msoliman22** [comment]
another question , if there is a more efficient approach to managing location IDs if we need to set up numerous readers nationwide? For instance, is it possible to have a single location ID for readers being used within a specific state or area?

**Comment by chr-stripe** [comment]
You must register your reader to a location to accept payments, but you can change which location they are registered to in the future should you wish to do so. Registering a reader to a given location does not mean it is locked to that location forever. This is why the [`UsbConnectionConfiguration`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-connection-configuration/-usb-connection-configuration/index.html?query=class%20UsbConnectionConfiguration(locationId:%20String,%20autoReconnectOnUnexpectedDisconnect:%20Boolean,%20usbReaderReconnectionListener:%20ReaderReconnectionListener?)%20:%20ConnectionConfiguration)'s constructor requires a non-null location ID to be provided.

Generally it's recommended to associate a location with a single physical operating site your readers are taking payments in. Stripe publishes tips for managing locations and your reader fleet in our [public documentation](https://stripe.com/docs/terminal/fleet/locations). We also have [Stripe Support](https://support.stripe.com/topics/terminal) available to answer any questions that are not specific to technical issues in the Terminal Android SDK.
