### ISSUE TITLE
is M2 Reader will move to success connect block after the update will be done 

### ISSUE THREAD

**Issue by msoliman22** [stripe/stripe-terminal-android#353]
I noticed that sometimes after the update will be done so it's just moved to  install done block then it will not connect again 

```
 Terminal.getInstance().connectUsbReader(reader, connectionConfig, this, object : ReaderCallback {

            override fun onSuccess(reader: Reader) {
           
            }

            override fun onFailure(e: TerminalException) {
                 
            }
        })
```

```
 override fun onFinishInstallingUpdate(update: ReaderSoftwareUpdate?, e: TerminalException?) {
      
    }
```
so after onFinishInstallingUpdate. will be executed  onSuccess(reader: Reader). will not be executed again so in this case how I can know that reader is ready to use and it's connected ?

**Comment by chr-stripe** [comment]
Hi @msoliman22, you will know that the reader is connected and ready to be used once you receive the [`ReaderCallback.onSuccess()`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-callback/index.html) callback.

The [`ReaderListener.onFinishInstallingUpdate()`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/on-finish-installing-update.html) callback is only invoked when the reader has either installed a required update during the connection process (and is always called before the `onSuccess()` callback, or when the reader has installed an optional update via [`Terminal.installAvailableUpdate()`](https://stripe.dev/stripe-terminal-android/core/com.stripe.stripeterminal/-terminal/install-available-update.html).
