### ISSUE TITLE
when IConnectionTokenProvider.FetchConnectionToken returns callback.OnFailure(), SDK is in unrecoverable state

### ISSUE THREAD

**Issue by jasells-bloomerang** [stripe/stripe-terminal-android#355]
## Summary

If request for a connection token fails for any reason, such as general comms failure (we make a request to our own server here to get a token), and the implemented `FetchConnectionToken ` method returns `callback.OnFailure("some comms failure occurred fetching the token")` as a result, the SDK will never attempt to call `FetchConnectionToken` again.

Even attempting to "reset" the SDK via `com.stripe.stripeterminal.clearCachedCredentials()` does nothing to recover ability to discover readers.

At this point, an application restart is required to reset the SDK.  

Is there a way to clear the static instance returned by `com.stripe.stripeterminal.getInstance()` so that `com.stripe.stripeterminal.initTerminal()` can be called again for a "soft-reset" instead of app-resart?

## Android version

13

## Impacted devices (Android devices or readers)

Pixel 4

readers: both BT and Internal (NFC).

## SDK version

2.20.0

**Comment by billfinn-stripe** [comment]
Can you elaborate at what point the connection token is failing? Are you performing a particular operation? Are you just calling `initTerminal`? In either case, you should be able to retry the operation or re-initing Terminal, and the SDK should attempt to re-fetch a connection token.

**Comment by jasells-bloomerang** [comment]
It is failing after application code calls `initTerminal`.  So, the very first attempt, even before we can attempt `discover`

**Comment by jasells-bloomerang** [comment]
As a reference point, the iOS Terminal SDK is ok with an error returned at this point, as when `discover()` is called, it will request a new token anyway.

**Comment by ugochukwu-stripe** [comment]
Got it, probably unrelated to this issue then since `NSURLErrorDomain` is an iOS platform error
