### ISSUE TITLE
Bluetooth connection fail  [Device pop up pairing message to allow the connection ]

### ISSUE THREAD

**Issue by msoliman22** [stripe/stripe-terminal-android#359]
so we are trying to connect over Bluetooth on device that running on android 9 [K2 Pro] so everytime I am trying to connect over bluetooth so the device will pop up pairing message and then the connection will fail after pressing on Pair , I am still following up with the manufacture to help us to remove this pop up but please let me know if stripe team can help us with the reason behind the connection fail because the error will be simply "Connect reader failed unexpectedly "  without more info

please check this image thx 

<img width="1440" alt="Screen Shot 2023-08-02 at 1 05 06 PM" src="https://github.com/stripe/stripe-terminal-android/assets/92383246/52e20055-8825-4992-8485-00f8227eb2d4">

**Comment by dmatthews-stripe** [comment]
Hi @msoliman22 . We will be archiving this ticket due to inactivity. Please feel free to reopen if this happens again!
