### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Kikimora** [stripe/stripe-terminal-android#360]
## Summary

SDK documentation does not explain thread safety. One can assume entire SDK is thread safe, but my own anecdotal evidence suggest it is not. 

Please explain two things:
- What SDK operations can be launched from multiple threads? In the official example most operations launched from main thread except payment related, they are sequenced but run by multiple threads. 
- What operations can run concurrently e.g. discovering readers while also collecting a payment method from a connected reader.

Thanks

**Comment by chr-stripe** [comment]
> What SDK operations can be launched from multiple threads? In the official example most operations launched from main thread except payment related, they are sequenced but run by multiple threads.

SDK operations can be launched from any thread. The SDK ensures that they will all be executed asynchronously on a background thread so as to not block the main thread while being run. If you attempt to start a new operation that requires reader interactions (eg: collecting a payment method) while another reader operation is still in progress, it will be queued up and executed only once the first one completes.

> What operations can run concurrently e.g. discovering readers while also collecting a payment method from a connected reader.

Only a few select operations can be run concurrently with other ones; operations that only fetch data and have no side effects. As of today this includes:

- `Terminal.listLocations()`
- `Terminal.retrievePaymentIntent()`
- `Terminal.retrieveSetupIntent()`
