### ISSUE TITLE
Is it true that tap to pay on Android is still not self-serve?

### ISSUE THREAD

**Issue by atrauzzi** [stripe/stripe-terminal-android#363]
The readme file [mentions that tap to pay on Android is still not self serve](https://github.com/stripe/stripe-terminal-android/blob/ef06ea6b30ff609fda4d4aa6f18d95c90380e812/README.md?plain=1#L138-L139).

I just wanted to confirm whether this is still the case, or if there's a specific point at which tap to pay will begin working for me without having to reach out to Stripe?

(I ask specifically because the entire Stripe Dashboard UI makes it seem like the functionality is fully released and self-serve.)

If the information is out of date, perhaps it's worth updating the readme to not include this part so that people aren't mislead into thinking the functionality isn't self-serve?

**Comment by maggiewhite-stripe** [comment]
You're right that the README file is not accurate - it's self-serve in every country where Terminal is supported:
https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=android

We will update these docs to be more accurate. Thank you for your report!
