### ISSUE TITLE
"Must have a country code to connect to a Tap to Pay reader." after upgrading from 2.23.1 to 3.0.0

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stripe/stripe-terminal-android#372]
## Summary
After updating to 3.0.0 today we received the error: "Must have a country code to connect to a Tap to Pay reader." even though we provide a valid Stripe Location ID ("tm_...").

## Code to reproduce

```kotlin

class TtpaDiscoveryListener(val context: StripeViewModel, val callback: StripeViewModel.UserCallback) :   DiscoveryListener, Callback {

override fun onUpdateDiscoveredReaders(readers: List<Reader>) {

val config = ConnectionConfiguration.LocalMobileConnectionConfiguration(
'tm_....'
        )


        Terminal.getInstance().connectLocalMobileReader(readers.get(0), config, object :
            ReaderCallback {


            override fun onFailure(e: TerminalException) {
                callback.onFailure(e)
// -> exception here: Must have a country code to connect to a Tap to Pay reader.

            }

            override fun onSuccess(reader: Reader) {
...
            }
        })
    }

```

## Android version
11

## Impacted devices (Android devices or readers)
TTPA internal reader on Zebra TC26 BK

## SDK version
3.0.0 (was working fine on 2.23.1)

![Bildschirmfoto 2023-09-18 um 15 23 11](https://github.com/stripe/stripe-terminal-android/assets/10075/b2097697-8927-4bb1-84f3-aaae93b2eb1c)

## Additional information

The country has been set in the Stripe Backend.

I'm also currently chatting via Discord with your developers about it.

**Comment by chr-stripe** [comment]
Thank you for the report! We've identified the issue and will be releasing a fix for this in the upcoming SDK version `3.1.0`.
