### ISSUE TITLE
Question around USB `collectPaymentMethod` function

### ISSUE THREAD

**Issue by jbuda** [stripe/stripe-terminal-android#376]
## Summary
More of question really about the potential reasons / issues that could prevent `collectPaymentMethod` from returning any response on the callback. We have the terminal connected via USB.

It's a difficult one to reproduce and very temperamental but more often than not it works fine. Once the `createPaymentIntent` function is called and a response is returned, we execute the `collectPaymentMethod` function with the returned `Payment Intent`. 

Occasionally the `collectPaymentMethod` does not return with any response and looking in the logs on Stripe we are experiencing `incomplete` transactions and no attempt to run the collect payments request. Internet is always present and on but for whatever reason we seem to experience this callback from returning either a success or failure.

In one circumstance the Terminal was in a state that would never collect any payments and a restart of the device was the only resolution. We are trying to work out why this is happening and what would cause this issue. Rebooting the Android device does not (most of the time) resolve this issue either.

Quite a broad question and if the code was wrong we would expect this payment to never succeed, but it is functioning except for occasional instances. Are there any logs that can be viewed that exist on the Terminal itself, perhaps to help diagnose the issue.

## Android version

Only have it running on Android 8 and 10

## Impacted devices (Android devices or readers)

Wisepad 3

## SDK version

Stripe 2.21.1

**Comment by chance-yang** [comment]
I encountered the same problem. The difference is that I used a Bluetooth connection.
I'm using an M2 card reader on Android.

**Comment by chr-stripe** [comment]
Hi folks, sorry for the delay in responding. We don't anticipate there would be any reason for the reader or the SDK to get stuck like this, but if that does happen in the future I would recommend upgrading to a more recent SDK to see if the issue no longer occurs.

If you're still able to encounter this more than occasionally on newer versions, providing a reader serial number, payment intent id, and a rough time of when the issue occurred would be helpful for us to investigate what might be happening on the reader.

**Comment by dmatthews-stripe** [comment]
Hi @chance-yang and @jbuda , we will be closing this ticket due to inactivity. If this issue occurs again, please provide the reader serial, payment intent id and time of when the issue occurred and we will further investigate.
