### ISSUE TITLE
The callback of calling the createPaymentIntent method is very slow.

### ISSUE THREAD

**Issue by Jason-IUVO** [stripe/stripe-terminal-android#383]
## Summary
When I call the createPaymentIntent method, I will print a log at the beginning of the call, and then print another log in the callback, but now it will occasionally take about 31 seconds to create successfully, and because createPaymentIntent cannot be cancelled, many attempts will be superimposed for about 31 seconds in the case that the first call has not been responded to, and several createPaymentIntent methods during this period will respond to success at a similar point in time.

## Code to reproduce
```
callbackPaymentIntentStatus(
                    null,
                    CustomPaymentStatus.START_CREATE_PAYMENT_INTENT,
                    null
                )
Terminal.getInstance()
                    .createPaymentIntent(params, object : PaymentIntentCallback {
                        override fun onSuccess(paymentIntent: PaymentIntent) {
                            callbackPaymentIntentStatus(
                                currentPaymentIntent,
                                CustomPaymentStatus.CREATE_PAYMENT_INTENT_SUCCESS,
                                null
                            )
                        }

                        override fun onFailure(e: TerminalException) {
                            currentPaymentIntent = null
                            callbackPaymentIntentStatus(null, CustomPaymentStatus.CREATE_PAYMENT_INTENT_FAIL, e)
                        }
                    })
```

## Android version
Android 9

## Impacted devices (Android devices or readers)
Reader: M2

## SDK version
2.22.0

**Comment by bperez-stripe** [comment]
It looks like this issue is related to integration support. The fastest way to get support for your integration is to reach out directly to our support team: https://support.stripe.com/contact. Gitlab issues should only be submitted for bug reports or feature requests.
