### ISSUE TITLE
Xamarin / .NET MAUI Bindings Support

### ISSUE THREAD

**Issue by dev2442422** [stripe/stripe-terminal-android#393]
## Summary
I am currently working through attempting to create an Android Java Library binding to the Stripe Terminal SDK. I am noticing the stripe terminal SDK has a large amount of dependencies on other .aar files making the binding process difficult. 

Is there any officially supported or recommended way of creating Xamarin / .NET MAUI bindings for the Stripe Terminal SDK for Android?

**Comment by bperez-stripe** [comment]
Thank you for reaching out. Unfortunately we do not have any officially supported/recommended way of creating Xamarin / .NET bindings for any of the Terminal SDKs today.
