### ISSUE TITLE
Testing Tap to Pay with physical test card

### ISSUE THREAD

**Issue by jolen10** [stripe/stripe-terminal-android#397]
With a previous version of the SDK (I think it's 2.20.1), a development (debuggable) build can make a tap to pay transaction using a Stripe physical test card but now it is giving me an LOCAL_MOBILE_DEBUG_NOT_SUPPORTED error saying:

"Debuggable applications are not supported in the production version of the localmobile reader. Please use a simulated version of the reader by setting `DiscoveryConfiguration.isSimulated` to true."

Setting the `DiscoveryConfiguration.isSimulated` to true will also just use a simulated card and will not let us use the physical Stripe test cards.

Is there a way to make a Tap to Pay transaction with test cards in a debug build?

We ignored the issue before and just decided to use the older version that works but is no longer the case when we migrated to version 3.

**Comment by lins-stripe** [comment]
This was changed in SDK version [2.21.0](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2210---2023-06-05) and above:

> Update: Using the production version of the localmobile reader with debuggable applications now fails during discovery with a TerminalErrorCode::LOCAL_MOBILE_DEBUG_NOT_SUPPORTED error for security and compliance reasons. Developers should test and integrate the Tap to Pay on Android SDK with a simulated version of the reader by setting DiscoveryConfiguration.isSimulated to true.

If you need to test with a debuggable app, you can continue to use `2.20.1`.
