### ISSUE TITLE
collectPaymentMethod does not return with any response

### ISSUE THREAD

**Issue by chance-yang** [stripe/stripe-terminal-android#398]
## Summary

The collectPaymentMethod does not return with any response, neither for success nor for failure.
Previously when we were using version stripeterminal:3.0.0-b1, sometimes there was no response when calling retrievePaymentIntent. Now that we have upgraded to version stripeterminal:3.0.0-b6, we found that there is no callback when using collectPaymentMethod.

Logs as follows:
<img width="1099" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/041eb89b-5ee0-4444-b15c-076fdb582ab7">

By the way, this is the first payment of the day today.

## Android version

Android 12
## SDK version

implementation "com.stripe:stripeterminal:3.0.0-b6"
implementation "com.stripe:stripeterminal-localmobile:2.21.1"
implementation "com.stripe:stripeterminal-core:2.21.1"
## Other information

Card Reader SN ：STRM26214135984
Bluetooth connection.

**Comment by lins-stripe** [comment]
Looking at the [changelog](https://git.corp.stripe.com/stripe-internal/android/blob/master/terminalsdk/public/CHANGELOG.md#2210---2023-06-05) of the 2.21.0 SDK (3.0.0-b6 is based off of 2.21.0):

```
Update: Terminal.retrievePaymentIntent and Terminal.retrieveSetupIntent will no longer be blocking if an existing reader operation is in progress.
```

Could you confirm whether your integration is properly accounting for this change?

**Comment by chance-yang** [comment]
Hi lins, 
I'm sorry, I'm not sure what "if an existing reader operation is in progress" specifically includes.Actually, this is the first payment on November 7th and the last payment was at 2023-11-06 20:17:56; therefore, I don't think there could be another ongoing operation. We checked the paymentStatus before calling retrievePaymentIntent and only proceeded when it was READY.
1. What does paymentStatus ”READY+“ mean? I noticed that the normal status should be READY.
2. How can I determine if an operation is in progress?

Here is my code snippet, please help me to see if the integration is correct.

`public void paymentIntent(String clientSecret) {
        StripeLogHelper.info(TAG, "paymentIntentNet:" + clientSecret);
        StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.OPERATE_MSG, "paymentIntentNet:" + clientSecret);
        if (!Terminal.isInitialized()) {
            Exception e = new Exception("stripe terminal sdk not initialized");
            StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, e);
            return;
        }
        ConnectionStatus connectionStatus = Terminal.getInstance().getConnectionStatus();
        StripeLogHelper.info(TAG, "Terminal connectionStatus :" + connectionStatus);
        if (!connectionStatus.equals(ConnectionStatus.CONNECTED)) {
            Exception e = new Exception("stripe terminal connect state is not connected");
            StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, e);
            return;
        }
        PaymentStatus paymentStatus = Terminal.getInstance().getPaymentStatus();
        StripeLogHelper.info(TAG, "Terminal paymentStatus :" + paymentStatus);
        if (!paymentStatus.equals(PaymentStatus.READY)) {
            Exception e = new Exception("stripe terminal payment state is not ready");
            StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, e);
            return;
        }
        isRetrievePayIntent = true;
        StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_START, "paymentIntentNet:" + clientSecret);
        Terminal.getInstance().retrievePaymentIntent(clientSecret, new PaymentIntentCallback() {
            @Override
            public void onSuccess(@NonNull PaymentIntent paymentIntent) {
                StripeLogHelper.info(TAG, "retrievePaymentIntent onSuccess");
                if (!isRetrievePayIntent) {
                    StripeLogHelper.info(TAG, "retrievePaymentIntent return");
                    return;
                }
                isRetrievePayIntent = false;
                StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_INTENT, paymentIntent);
                currentPaymentIntent = paymentIntent;
                collectPaymentMethod(true);
            }

            @Override
            public void onFailure(@NonNull TerminalException exception) {
                StripeLogHelper.info(TAG, "retrievePaymentIntent onFailure");
                if (!isRetrievePayIntent) {
                    StripeLogHelper.info(TAG, "retrievePaymentIntent return");
                    return;
                }
                isRetrievePayIntent = false;
                StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, exception);
            }
        });
    }

    @OptIn(markerClass = OfflineMode.class)
    private void collectPaymentMethod(boolean updatePaymentIntent) {
        StripeLogHelper.info(TAG, "collectPaymentMethod()");
        if (!mOfflinePayEnable && Terminal.getInstance().getNetworkStatus() != NetworkStatus.ONLINE) {
            StripeLogHelper.info(TAG, "collectPaymentMethod onFailure " + StripeConstant.STRIPE_OFFLINE_TIPS);
            Exception e = new Exception(StripeConstant.STRIPE_OFFLINE_TIPS);
            StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, e);
            return;
        }
        StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.OPERATE_MSG, "collectPaymentMethod()");
        collecting = true;
        CollectConfiguration collectConfig = new CollectConfiguration.Builder()
                //.updatePaymentIntent(updatePaymentIntent)
                .build();
        collectCancelable = Terminal.getInstance().collectPaymentMethod(currentPaymentIntent,
                new PaymentIntentCallback() {
                    @Override
                    public void onSuccess(@NonNull PaymentIntent paymentIntent) {
                        PaymentIntentInfo paymentIntentInfo = DataMappingUtil.mapping(paymentIntent,
                                "collectPaymentMethod-onSuccess");
                        currentPaymentIntent = paymentIntent;
                        StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_READ_SUCCESS, paymentIntentInfo);
                        collecting = false;
                    }

                    @Override
                    public void onFailure(@NonNull TerminalException exception) {
                        StripeLogHelper.info(TAG, "collectPaymentMethod-onFailure:" + exception.toString());
                        collecting = false;
                        TerminalException.TerminalErrorCode errorCode = exception.getErrorCode();
                        if (errorCode != TerminalException.TerminalErrorCode.CANCELED) {
                            StripeStatusCall.getInstance().sendPosMessage(StripeStatusCall.PAY_FAIL, exception);
                            cancelPay();
                        }
                    }
                }, collectConfig);
    }`

**Comment by lins-stripe** [comment]
If you need support for your integration, please reach out directly to our support team: https://support.stripe.com/contact. Github tickets issues should only be submitted for bug reports or feature requests.

If you encounter a similar issue in the future, please first try to reproduce with the Terminal sample application, and, if it doesn't happen within the sample application, compare your implementation with the sample application to spot any differences.
