### ISSUE TITLE
Provide Library outside of Gradle

### ISSUE THREAD

**Issue by joshbartley** [stripe/stripe-terminal-android#40]
I am working on a Xamarin app, and I had to nab the com.stripe:stripeterminal:1.0.0-b3 package out of gradle to load it into a Xamarin binding project. It would be great if this package was available to download from the Releases tab for when an update occurs in the future

**Comment by danwaters-stripe** [comment]
Thanks for the feedack. That's a good point. I've added the `1.0.0-b4.aar` file to the latest release and will continue doing that for all future releases.
