### ISSUE TITLE
Unable to use compatible Samsung SM-S918B as a tap on phone device

### ISSUE THREAD

**Issue by GPRSBirkbeck** [stripe/stripe-terminal-android#405]
## Summary

Users that have a Samsung SM-S918B (Smartphone Samsung Galaxy S23 Ultra) are not given the option to 

## Code to reproduce

I believe this is due to never being able to get `DiscoveryMethod.LOCAL_MOBILE` or `connectLocalMobileReader()` not working correctly.

## Android version

Android 14

## Impacted devices (Android devices or readers)

Currently only `Samsung SM-S918B`
## SDK version

```
'stripe_terminal' : '2.22.0',
'stripe_android' : '20.34.4',
```

## Other information

Thank you!

**Comment by lins-stripe** [comment]
Hey, please double check that you're following the setup instructions [here](https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices), you'll need the `com.stripe:stripeterminal-localmobile` and `com.stripe:stripeterminal-core` dependencies.

If you have other integration questions, please reach out directly to our support team: https://support.stripe.com/contact.
