### ISSUE TITLE
Is it possible to keep payment intent always "open" on Wisepad 3?

### ISSUE THREAD

**Issue by msgolubev** [stripe/stripe-terminal-android#406]
I want to use BBPos Wisepad 3 for unattended payments with some kind of vending machine which doesn't have any input controls to initiate the payment. So I want POS-terminal will be always waiting for the card or the phone with NFC to be tapped. The payment amount is always the same.

Thanks in advance.

**Comment by chr-stripe** [comment]
Hi @msgolubev, this page is primarily for reporting issues or feature requests for the Terminal Android SDK. If you have questions regarding general integration support, please reach out directly to our support team: https://support.stripe.com/contact.

We have some support documentation about unattended Terminal support published there as well: https://support.stripe.com/questions/terminal-support-for-attended-and-semi-attended-scenarios
