### ISSUE TITLE
Tap to Pay on LocalMobile failed to connect with Local Mobile reader 

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#407]
Hi Team,

On some of our device, Tap to pay failed to connect with the local mobile reader with the error `Failed to generate key pair`
The error occur on the following code snippet given below

	
	val config = ConnectionConfiguration.LocalMobileConnectionConfiguration(MYLOCATIONID);
	Terminal.getInstance().connectLocalMobileReader(firstReader, config, object : ReaderCallback {
		
		override fun onSuccess(reader: Reader) {
			// Success will do further tap process
		}

	    override fun onFailure(e: TerminalException) {
	    	Log.d("TapLOG", "Local Reader Connection :: "+ e.errorMessage); 
	    	// On Some device failed with error `Local Reader Connection :: Failed to generate key pair`
	    }
	});

From the code it seems like a connectivity issue with local mobile reader, Could you please let me know how this happens for certain devices only? My stripe terminal SDK version is `3.1.0`

Thank You

**Comment by chr-stripe** [comment]
Hi @ajithv11, can you use the [bug report template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&projects=&template=terminal-android-sdk-issue.md&title=) to provide more information about which devices you're running into this issue on?

**Comment by billfinn-stripe** [comment]
I'm going to close this issue due to inactivity. Feel free to reopen using the bug report template if it still persists.
