### ISSUE TITLE
Expired API Key provided

### ISSUE THREAD

**Issue by Jason-IUVO** [stripe/stripe-terminal-android#410]
## Summary
Based on the logs from the production environment, an error occurred when calling the `createPaymentIntent` method with the following details: 
errorMessage: Expired API Key provided: pss_live_YW*********************************************************************_******zLbP, 
errorCode: NETWORK_ERROR.SESSION_EXPIRED.

And within one hour, multiple devices encountered errors, with different API keys as well：
pss_live_YW*********************************************************************_******ZHX3
pss_live_YW*********************************************************************_******zLbP
pss_live_YW*********************************************************************_******6ASN
pss_live_YW*********************************************************************_******bWgG

## Code to reproduce
```
Terminal.getInstance()
                    .createPaymentIntent(params, object : PaymentIntentCallback {
                        override fun onSuccess(paymentIntent: PaymentIntent) {
                            callbackPaymentIntentStatus(
                                currentPaymentIntent,
                                CustomPaymentStatus.CREATE_PAYMENT_INTENT_SUCCESS,
                                null
                            )
                        }

                        override fun onFailure(e: TerminalException) {
                            currentPaymentIntent = null
                            callbackPaymentIntentStatus(null, CustomPaymentStatus.CREATE_PAYMENT_INTENT_FAIL, e)
                        }
                    })
```

## Android version
Android 9

## Impacted devices (Android devices or readers)
Reader: M2

## SDK version
2.22.0

**Comment by basitjawaid** [comment]
Similar bug encountered, @gliu-stripe can you help ?

**Comment by basitjawaid** [comment]
@Jason-IUVO are able to resolve this bug?

**Comment by billfinn-stripe** [comment]
Can you reproduce this error using the latest SDK version?

**Comment by basitjawaid** [comment]
@billfinn-stripe I have integrated the latest sdk, will share my experience here.

**Comment by dmatthews-stripe** [comment]
@basitjawaid we will be closing this ticket out, if this is still an issue, please let us know by re-opening this ticket or opening a new ticket.
