### ISSUE TITLE
Stripe M2 Firmware Update 

### ISSUE THREAD

**Issue by msoliman22** [stripe/stripe-terminal-android#415]
Hello , are we expecting from stripe to push firmware update to the reader each 5 months or it can be shorter ?  also is every required update will be optional at the beginning then it will be required at specific date ?

**Comment by dmatthews-stripe** [comment]
Hi @msoliman22 , we will be aiming to release new FW monthly. Yes, for firmware updates, we will set them as optional and then set them to be required after 2 weeks from the release time.

**Comment by dmatthews-stripe** [comment]
Hi @msoliman22 , we will be closing this ticket due to inactivity.
