### ISSUE TITLE
ReaderCallback event not called

### ISSUE THREAD

**Issue by kyungbonkim** [stripe/stripe-terminal-android#416]
## Summary

I tried connectUsbReader but Not Trigerred event ReaderCallback onSuccess, onFailure
For the first two weeks, it was working well, but suddenly, the function is not being called
but Trigerred event onConnectionStatusChange
I would greatly appreciate it if you could provide a response to this matter. Thank you.

## Android version

7.1.2

## Impacted devices (Android devices or readers)

WISEPAD 3

## SDK version

2.23.2

**Comment by kyungbonkim** [comment]
I soved this problem by firmware update

**Comment by dmatthews-stripe** [comment]
@kyungbonkim , thank you for letting us know the issue is resolved, we will close this ticket.
