### ISSUE TITLE
Encountered 'Transaction timed out' when calling collectPaymentMethod.

### ISSUE THREAD

**Issue by chance-yang** [stripe/stripe-terminal-android#419]
## Summary

Encountered 'Transaction timed out' when calling collectPaymentMethod.  Use Bluetooth Connection.
We have encountered this error many times. After encountering the problem, we must reset the Stripe card reader to resolve it.

1. STRM26229003642  
<img width="1306" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/57ea521d-c8e1-4f5d-bea9-a113fb83ceb7">

2. STRM26229004157
<img width="1196" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/20e569f7-d446-4c7f-ab7a-ce3af0d43cf7">

3. STRM26214135984
<img width="1161" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/49f11b31-2f52-4d7f-8e3d-5d65de0e20d4">

## Android version

Android 13
## Impacted devices (Android devices or readers)

Galaxy Tab A7 Lite

## SDK version

com.stripe:stripeterminal:3.0.0-b6

**Comment by chance-yang** [comment]
<img width="1206" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/66d4d6ae-fd79-432f-b3b8-90d563fabbc7">
Hello, we have encountered this issue, as mentioned in the above log.
SN: STRM26229003626

**Comment by bperez-stripe** [comment]
@chance-yang Have you seen this issue since updating to a non beta version of 3.x?

**Comment by chance-yang** [comment]
Hello, thank you for your response. We are currently testing the Stripe 3.2.1 version and have not yet released it widely. This issue is sporadic, and we have not been able to consistently reproduce it. We have also been tracking this issue on the 3.x versions. We hope you can find the root cause of the problem. Otherwise, it remains a potential risk for us, as we must restart the card reader and the application to recover whenever an issue occurs.

**Comment by ugochukwu-stripe** [comment]
@chance-yang, I was looking at some of the logs for the reader `STRM26229003626`, and don't see anything out of the norm, I noticed a timeout on January 25th during collect operation that occurred after a reader disconnect event, which is expected as attempts to communicate with the reader would timeout after a disconnect. Your application would get a `ReaderListener::onUnexpectedDisconnect` callback when this occurs, where you can initiate a reconnect; you could also look into our auto-reconnect feature [^1], if you haven't already.

[^1]: [Stripe Terminal auto reconnect](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=bluetooth#2.-automatically-attempt-reconnection)

**Comment by dmatthews-stripe** [comment]
Hi @chance-yang, we will be closing this ticket due to inactivity. If you are still experiencing this issue, please feel free to open a new ticket.
