### ISSUE TITLE
The battery level obtained from Stripe M2 connectedReader.getBatteryLevel() is incorrect.

### ISSUE THREAD

**Issue by OliverYang0305** [stripe/stripe-terminal-android#423]
## Summary

The battery level obtained from Stripe M2 connectedReader.getBatteryLevel() is incorrect.
Our application actively queries the battery level of the M2 device. The result obtained is 60%, but in reality, it is 100%. This continuous prompting for charging has caused some inconvenience to customers.

The log is as follows.
<img width="1056" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/158253967/9aada485-1443-4427-9fd8-00e860894e96">

## Code to reproduce

`Reader connectedReader = Terminal.getInstance().getConnectedReader();
            if (connectedReader == null) {
                return 0;
            }
            Float batteryLevelF = connectedReader.getBatteryLevel();
            if (batteryLevelF == null) {
                return 0;
            }
            float nowBattery = batteryLevelF * 100;`

## Android version

Android 9.
## Impacted devices (Android devices or readers)

Stripe M2 SN:  STRM26229025856
## SDK version

com.stripe:stripeterminal:3.0.0-b6

**Comment by bperez-stripe** [comment]
Hi @OliverYang0305. Are you able to reproduce this with the latest SDK release?

**Comment by OliverYang0305** [comment]
@bperez-stripe Hi, I tested on version 3.3.0, and the problem still exists. The return value of connectedReader.getBatteryLevel() seems to always be the battery level at the time of connection.

**Comment by udayTechnosouls** [comment]
I got same issue like seems to always be the battery level at the time of connection. I have set timer and every 5 mit checking Battery Level 
code : ` Terminal.getInstance().connectedReader?.batteryLevel?.times(100) ?: 0.0F`
Where else I can found  Battery Level or How I can refresh Battery Level ?

**Comment by chr-stripe** [comment]
Hi all! With the release of Terminal SDK 3.6.0, `Terminal.connectedReader`'s battery level will now be updated whenever the mobile reader's battery info is reported.
