### ISSUE TITLE
INTEGRATION_ERROR.LOCAL_MOBILE_DEVICE_TEMPERED

### ISSUE THREAD

**Issue by L-is-0** [stripe/stripe-terminal-android#426]
## Summary
Got INTEGRATION_ERROR.LOCAL_MOBILE_DEVICE_TEMPERED error from Stripe SDK 

## Android version
Android 11

## Impacted devices (Android devices or readers)
Tap to pay

## SDK version
3.2.1

## Other information
Happened multiple times on device id 902269 on 09/02/2024 and 10/02/2024
Here is the detailed error message from the logs

INTEGRATION_ERROR.LOCAL_MOBILE_DEVICE_TAMPERED
ATTESTATION_FAILURE (req_aG66nvh2Oy428l): Unexpected error encountered. Please try clearing the application data in the settings application and contact Stripe support if the issue persists

happened at the initial stage when the app was trying to init the local mobile SDK

**Comment by gliu-stripe** [comment]
Thanks for reaching out! Have you tried clearing the application data in your settings as mentioned?

**Comment by TTRuslan** [comment]
> Thanks for reaching out! Have you tried clearing the application data in your settings as mentioned?

Yes, we tried to clear app data, but issue still exist.

**Comment by L-is-0** [comment]
anyone could please advise on this issue?

**Comment by gliu-stripe** [comment]
Hi @L-is-0, are you still experiencing the issue after completely uninstalling and reinstalling the app?

**Comment by TTRuslan** [comment]
> Hi @L-is-0, are you still experiencing the issue after completely uninstalling and reinstalling the app?

Hi @gliu-stripe, unfortunately, reinstalling the app isn't an option for us since the devices are located remotely. Is there anything else you can suggest?

**Comment by gliu-stripe** [comment]
@TTRuslan, unfortunately this is the only mechanism we have right now to get the installation back into a healthy state. If you're working with a user, you could try asking them. I apologize that we don't have a better way to resolve this right now

**Comment by gliu-stripe** [comment]
@L-is-0 While the error we surface from our SDK may look the same (`INTEGRATION_ERROR.LOCAL_MOBILE_DEVICE_TEMPERED`, `Unexpected error encountered`), there could be a variety of different reasons causing the actual error to occur. Based on our logs, the one device that is still experiencing the error appears to have a unique issue with a type of bad stale data. From our logs, we did not observe this specific kind of staleness issue occur on any other device except that one in the past 30 days. Hence, our recommendation right now is to just try completely reinstalling the app if clearing the data did not work.

**Comment by L-is-0** [comment]
hi @gliu-stripe thank you for the clarification, could you please confirm why and how it has stale data? 
also how often this will happen?

**Comment by gliu-stripe** [comment]
@L-is-0 We don't have visibility into what exactly caused it to have stale data as this specific issue is not something we normally see (we only saw it happen on that single device)

**Comment by L-is-0** [comment]
Thank you @gliu-stripe - could you guarantee that if we reinstall the app the issue will not come back? How to stop this from happening on other devices

**Comment by gliu-stripe** [comment]
This issue shouldn't reoccur, but we can't fully guarantee that it will never happen again
