### ISSUE TITLE
SimulatorConfiguration for Tap to Pay payments

### ISSUE THREAD

**Issue by wkol** [stripe/stripe-terminal-android#432]
## Summary
For Bluetooth/Internet readers, we have used the `SimulatorConfiguration` in order to simulate more complex cases such as various charge declines, refunds, etc. For Tap to Pay readers, the same setup of `SimulatorConifiguration` seems to not work. The screen with the "Tap to simulate payment" button is shown, but after clicking the button, payment succeeds instead of being declined. Also, when inspecting the test payment details inside the dashboard, we can see that the card used is still the same. Am I making mistakes during the setup, or is the simulation of different cards for Tap to Pay not yet supported?

## Code to reproduce
After initializing the Terminal object, the proper simulated card is set through `SimulatorConfiguration`
```kotlin
Terminal.getInstance().simulatorConfiguration = SimulatorConfiguration(
    simulatedCard = SimulatedCard(SimulatedCardType.CHARGE_DECLINED)
)
```
Later, during the connection process, `true` is passed as the `isSimulated` parameter in the DiscoveryConfiguration.
```kotlin
Terminal.getInstance().discoverReaders(
    config = DiscoveryConfiguration(
        ...
        discoveryMethod = DiscoveryMethod.LOCAL_MOBILE,
        isSimulated = true
    )
)
```

## Android version
14, but I assume this does not make a difference.

## Impacted devices (Android devices or readers)
Tap to Pay readers

## SDK version
2.23.3

## Other information
The same simulation configuration works as intended for Bluetooth or internet readers.

**Comment by billfinn-stripe** [comment]
This is now fixed in 3.5.0:
https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#350---2024-04-09
