### ISSUE TITLE
Failed to generate key pair

### ISSUE THREAD

**Issue by batuhanseckinnnn** [stripe/stripe-terminal-android#440]
Hello,

I am currently developing an application with Flutter that integrates with Stripe Terminal. However, as far as I know, there is no official support for Stripe Terminal directly in Flutter, so I am using the [mek_stripe_terminal](https://pub.dev/packages/mek_stripe_terminal) plugin as an alternative.

I initially reported an error to the owner of the mek_stripe_terminal plugin and after discussing for a while, I began to suspect that the error might be related to the Stripe Terminal Android SDK.

I am having difficulty pinpointing exactly what the error is.

Could you please help me identify the details of this error and provide insight into what might be causing it?

All details are available in this link. I can provide additional information if necessary.
https://github.com/BreX900/mek-packages/issues/47

Thank you!

**Comment by batuhanseckinnnn** [comment]
Can anyone please help us looking into this issue? @gliu-stripe @rv-stripe

**Comment by gliu-stripe** [comment]
@batuhanseckinnnn could you post the error that you're seeing?

**Comment by gliu-stripe** [comment]
We usually see errors related to failed key pair generation when a device is not supported for Tap to Pay. This is unfortunately a device-specific limitation. See [our section on supported devices](https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices). If you want to use the Terminal SDK without Tap to Pay, you won't encounter this issue.

**Comment by batuhanseckinnnn** [comment]
Implementing it this way seems to have solved the problem for me.

``` implementation "com.stripe:stripeterminal:3.x.x" ```

But this time I'm having connection problems with your latest version, 3.4.0. So, I have a timer in my application that constantly checks the connection status. If the connection is lost and the necessary conditions are met to reconnect, it automatically tries to reconnect.

First opening process of the application:

- Attempting to automatically connect to the reader with serial number STRM26214084171. For this, the reader must be findable.
- connecting
- connected
- automatically connected to the reader with STRM26214084171 serial number



Loop after disconnection:
- Reader Unexpected Disconnected: STRM26214084171(2024-03-11T10:03:49.129097)
- Attempting to automatically connect to the reader with serial number STRM26214084171. For this, the reader must be findable. (2024-03-11T10:08:46.949027)
- connecting (2024-03-11T10:08:46.962361)
- notConnected (2024-03-11T10:09:07.408187)

- Reader Unexpected Disconnected: STRM26214084171 (2024-03-11T10:09:07.409489)
...

The same cycle continues like this after the first connection is broken

Firebase crashlytics :
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: USB unexpectedly disconnected during operation.
       at TerminalPlatform._throwIfIsHostException(terminal_platform.dart:185)
       at _$TerminalPlatform.discoverReaders.<fn>(terminal_platform.api.dart:21)
       
You have declined the necessary permission, please allow from settings to continue.


We develop applications for kiosk devices, and once installed, no settings of the device are changed. It doesn't make sense how I could get an error regarding permission after the first connection is established.

If you need more information, I can provide it or create a new issue for this problem.

**Comment by maxa-stripe** [comment]
@batuhanseckinnnn, Could you provide your integration code, OS name & version, and the part of your Android manifest which lists requested permissions? As a reminder, [these permissions][0] must be requested by your app _and_ granted by the OS in order to enable BLE connectivity to the M2 reader.

[0]: https://docs.stripe.com/terminal/payments/setup-integration?terminal-sdk-platform=android#configure

**Comment by batuhanseckinnnn** [comment]
I think it would be best to close this issue for now. I will try to explain the other error I received in more detail under a new title.

Thanks.
