### ISSUE TITLE
Can‘t read card info and collectPaymentMethod time out

### ISSUE THREAD

**Issue by chance-yang** [stripe/stripe-terminal-android#441]
## Summary

Hello, our M2 card reader device has encountered two issues.

1. Inserting a bank card does not read the card information. It has not been successful since March 13th at 14:13.
<img width="1127" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/2bddbdf2-8e00-4428-9a41-977a0e0d5fab">

2. After calling the `collectPaymentMethod `method, there is no response. Normally, we notice that after calling the `collectPaymentMethod` method, the `TerminalInitListener`'s `onPaymentStatusChange `immediately callbacks with the status `WAITING_FOR_INPUT`. However, at 2024-03-13 17:55:59.792, after calling collectPaymentMethod, there were no callbacks from the SDK within 10 seconds, so our program considers it a "Collect payment method timeout."
<img width="857" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/218acb2e-c35b-42c9-9d55-f6eba8a1de18">

Attached is the complete log.
[Stripe_2024-03-13.txt](https://github.com/stripe/stripe-terminal-android/files/14598033/Stripe_2024-03-13.txt)

## Android version

Android 13

## Impacted devices (Android devices or readers)

Samsung  Galaxy Tab A7 Lite
## SDK version

com.stripe:stripeterminal:3.0.0-b6

## Other information

Stripe Reader M2  STRM26229002966    
Bluetooth connection

**Comment by dmatthews-stripe** [comment]
Hi @chance-yang have you tried this on the latest version of the SDK, 3.4?

**Comment by chance-yang** [comment]
Hi @dmatthews-stripe , we have many devices operating on the Android 7.0 system, therefore, we are unable to use the 3.x version of the SDK.

**Comment by xiaoshen-stripe** [comment]
Hi @chance-yang 
Thank you for raising this issue. 

I see you are on the beta SDK version "com.stripe:stripeterminal:3.0.0-b6" - are you using offline mode at all, which is only supported on SDK V3+ [0]? 
If offline mode is not a required, than can you try out the latest Android V2 minor version [1] and see if the issues persist? 
This should still support Android 7.x systems. 

We appreciate you being one of our beta users for SDK v3.
For future reference - once the SDK version is GA'ed, we do not maintain beta versions with necessary bug fixes/security updates. We will make this clear in our documentation going forward.  

Thanks,
Xiao
[0] https://docs.stripe.com/terminal/references/sdk-migration-guide?terminal-sdk-platform=android#review-support-for-offline-payments

[1] https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2233---2023-12-22

**Comment by xiaoshen-stripe** [comment]
Hi @chance-yang  - as we have not received any further response from you, we will close this ticket for now. 

Also note that SDK V2 is now past its support date. 
https://github.com/stripe/stripe-terminal-android/blob/master/SUPPORT.md#release-status
