### ISSUE TITLE
Add callback to know when a card is inserted or removed outside collect state

### ISSUE THREAD

**Issue by Oshariser** [stripe/stripe-terminal-android#446]
I want to know at any moment if a card is inserted or removed, not only in collect state.

**Comment by billfinn-stripe** [comment]
Hi @Oshariser -- can you share more information on why you would like this information?

**Comment by Oshariser** [comment]
Hi @billfinn-stripe, our customer want to insert a card to unlock our app and start doing some payment. It's a condition to allow only card owner to do payment and avoid for example children to have access and play with our app.

**Comment by billfinn-stripe** [comment]
Hi @Oshariser -- that's helpful. So, in other words, you'd like to use card insertion (any card -- doesn't have to be a proper credit card) as a signal for your POS application to unlock?

**Comment by Oshariser** [comment]
@billfinn-stripe exactly

**Comment by ugochukwu-stripe** [comment]
Hi @Oshariser , curious what your integration set up is like, are you're using a `Bluetooth/Usb` Reader or an Internet Reader?

**Comment by Oshariser** [comment]
Hi @ugochukwu-stripe we are using usb Stripe Reader M2

**Comment by cwoods-stripe** [comment]
This feature is now available in Terminal Android SDK 3.7.0
https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md

**Comment by vastopa** [comment]
Is this fix already available in the iOS SDK or will it be made available to align implementations?

**Comment by ugochukwu-stripe** [comment]
@vastopa I believe the iOS SDK already supports this feature, feel free to open an [issue](https://github.com/stripe/stripe-terminal-ios/issues) if it isn't working as expected.
