### ISSUE TITLE
Stripe Contactless Activity doesn't showing the tap to pay spot and amount while using latest sdk version 3.4.0

### ISSUE THREAD

**Issue by aadii2610** [stripe/stripe-terminal-android#448]
### The issue i am getting while i reached on the payment screen.The amount is not displaying and neither is the tap to pay animation which indicates the spot behind the device.
**Note:I am using the same demo code provided by the stripe by just changing the version of localmobile to latest one**

## Android version
I am using android 14 but my targetsdk is 33

## Impacted devices (Android devices or readers)
Testing it on Samsung A14

## SDK version
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    
  
![stripe issue](https://github.com/stripe/stripe-terminal-android/assets/136782933/b895f0d7-feb2-49fc-ba3d-5df6b51b1a48)
  implementation "com.stripe:stripeterminal-localmobile:3.4.0"
    implementation "com.stripe:stripeterminal-core:3.4.0"

**Comment by mindy-stripe** [comment]
Hi @aadii2610, thanks for the report. This screen is the simulated local mobile reader screen, so it does not show the purple tap circle, and you instead must tap the "TAP TO SIMULATE PAYMENT" button instead. 

If you wish to use your phone's tap to pay screen, please ensure you have disabled the "simulated" toggle when discovering for readers.

**Comment by mindy-stripe** [comment]
There does seem to be a bug with the simulated reader UI where the total amount is missing, and we will look to fix that in a future SDK release. Thanks!
