### ISSUE TITLE
READER_MISSING_ENCRYPTION_KEYS Error still coming in SDK 3.4.0

### ISSUE THREAD

**Issue by upworkhans** [stripe/stripe-terminal-android#450]
## Summary
We are still getting the same error READER_MISSING_ENCRYPTION_KEYS even after updating the SDK to 3.4.0
 
We are using Stripe M2 Reader & once this error comes, we have to clear POS App Cache, Reboot Stripe, Restart POS to make it work.

## Android version
Android 13

## Impacted devices (Android devices or readers)
All

## SDK version
3.4.0

## Other information
Here is the screen shot of the issue that I am getting
![be947c52-db50-4ab1-8ac7-0ddce57f2236](https://github.com/stripe/stripe-terminal-android/assets/32158153/b64737f2-9419-496c-a0a4-af0c3d1c9940)

**Comment by ugochukwu-stripe** [comment]
Hello @upworkhans , could you share the serial number for the reader you're seeing getting this error on, and could you also confirm that reconnecting to the reader after this error does not resolve the issue, and it's only fixed when you go through the steps you mentioned above

**Comment by ugochukwu-stripe** [comment]
We'd be adding a fix in the SDK to reboot the reader when it encounters a `READER_MISSING_ENCRYPTION_KEYS` error, as we've noticed the reader gets back into a good state after a reboot. I'll follow up on this issue once the release is out.

**Comment by ugochukwu-stripe** [comment]
We've rolled out the feature to reboot the bluetooth/Usb reader when the SDK encounters this error, could you please upgrade to version `3.6` [^1] and let us know if you're still experiencing this issue.

[^1]: https://github.com/stripe/stripe-terminal-android/releases/tag/v3.6.0

**Comment by xiaoshen-stripe** [comment]
Hi @upworkhans 
want to check in and confirm if you are still experiencing any reader connection error due to READER_MISSING_ENCRYPTION_KEYS since you upgraded to the new SDK? 

If so, we can eliminate this scenario and focus on the other error scenarios that you have. Thanks
