### ISSUE TITLE
Tap to pay android via Stripe dashboard app failing to accept interac payments

### ISSUE THREAD

**Issue by doryza** [stripe/stripe-terminal-android#460]
I was wondering if this issue while using Tap To Pay for Android is specific to the Stripe app because perhaps it doesn't have regional considerations for interac... Or is it that Tap To Pay Android doesn't support interac payments via the "payment_method_types[]"=interac_present " parameter?

**Comment by sjl-stripe** [comment]
This is expected - Tap To Pay on Android doesn't support interac payments.

**Comment by doryza** [comment]
are you certain of this? documentations hints otherwise and we notice that Square is supporting it on request, see image;
![image (3)~2](https://github.com/stripe/stripe-terminal-android/assets/40502568/f7090fd9-ff50-4031-ade0-58c9db5ee099)
Can we request it as a feature?

**Comment by sjl-stripe** [comment]
Thank you for drawing our attention to this. We are currently monitoring interest in this feature, even though it hasn't been scheduled for development.

If you are an existing Stripe customer, could you kindly provide us with your account name and ID, which will help us record your interest in this feature? Appreciate your support!

**Comment by doryza** [comment]
acct_1PCEbe2N0Rzj7gw1

**Comment by doryza** [comment]
Are we certain that even with the proper intent included this will not work? We were ready to develop and test if functionnal as documentation isn't clear about this.

**Comment by sjl-stripe** [comment]
Yes, we're certain about this. We recognize the need for better documentation and we'll update it to avoid any future confusion.

**Comment by sjl-stripe** [comment]
You can refer to our [Supported Card Brands documentation](https://docs.stripe.com/terminal/payments/collect-card-payment/supported-card-brands#in-person-brand-capabilities) for detailed information on the card brands we currently support for the Tap to Pay feature.

**Comment by doryza** [comment]
Can we realistically expect that stripe may adopt this in the short term (2-4 weeks)?

**Comment by doryza** [comment]
BTW some of these cards brands fail on the stripe app, for instance debit/inerac cobranded by visa or MC due to the fact that everything is handled by interac

**Comment by sjl-stripe** [comment]
> Can we realistically expect that stripe may adopt this in the short term (2-4 weeks)?

Currently, it's not in this year's roadmap to add support for it.

> BTW some of these cards brands fail on the stripe app, for instance debit/inerac cobranded by visa or MC due to the fact that everything is handled by interac

This is expected. Card-present transactions with co-branded interac cards [are routed through Interac](https://docs.stripe.com/terminal/payments/regional?integration-country=CA#interac-payments).

**Comment by doryza** [comment]
Right, just explaining that that link for supported brands is somewhat erroneous in stating that Visa and MC bearing card (such as cobranded debit) is compatible with all terminals. As in Canada those are routed differently, thus the table should separate visa and visa debit, etc.
As you can probably tell, we're very adamant on being able to accept interac/debit in all variations using Tap To Pay for Android in Canada. We have a scheduled call tomorrow in regards to this. Do you have a contact we can exchange to clarify if this CAN be added to the roadmap and if so, chime in on potential expectations on turn around?

**Comment by sjl-stripe** [comment]
It looks like you are already in contact with our account executive/support team regarding this matter, so I'll be closing this GitHub issue. Thank you!

**Comment by alex-reusables** [comment]
@sjl-stripe we are also very keen on this feature and you can register our interest: `acct_1J9uW2Bb49XQ2DGy`
