### ISSUE TITLE
Stop Discovery not working after reader disconnect

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#461]
When the connection to the reader is successful and then disconnected to search again, the issue arises as stopping the discovery does not work properly, preventing the detection of a new reader.

SDK Version 
com.stripe:stripeterminal:3.5.0

**Comment by chr-stripe** [comment]
Hi @VijayRathodM, can you use the [bug report template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&projects=&template=terminal-android-sdk-issue.md&title=) to provide more information about which devices you're running into this issue on? Especially if you have a reader serial number handy, that would be useful for us to check our logs to see what's happening.

**Comment by VijayRathodM** [comment]
now resolve
