### ISSUE TITLE
eftpos support for Tap to Pay on Android devices

### ISSUE THREAD

**Issue by tzecheng** [stripe/stripe-terminal-android#472]
## Summary
Transactions using eftpos cards (Australia) are not accepted on Android TTP devices. iOS devices work fine.
Apologies if I have posted to the wrong group.

## Impacted devices (Android devices or readers)
Android phones with Tap to Pay

## Other information
This doc https://docs.stripe.com/terminal/payments/collect-card-payment/supported-card-brands does NOT mention Android TTP apps.  We have tried the app in the field and it does not work for eftpos debit cards.  We have quite a number of Android users who have clients with eftpos cards.
Is there any plan to support this feature in the near future?
Thanks.

**Comment by tzecheng** [comment]
Hi there, is there any update on this?  Thanks.

**Comment by maggiewhite-stripe** [comment]
Hi @tzecheng, thanks for reaching out! You are correct that Tap to Pay on Android currently does not support EFTPOS cards. We are working on adding EFTPOS support but don't have a public ship date to share yet.
