### ISSUE TITLE
Timeout with onRequestApplicationSelection

### ISSUE THREAD

**Issue by loganthompson** [stripe/stripe-terminal-android#48]
During a Live Mode charge with a MasterCard, the software will request an application selection with the List<{MASTERCARD}>

`com.stripe.stripeterminal.BbposDeviceControllerListener.onRequestSelectApplication`

As there is no method to handle this (I'm assuming it will be automatic just like the iOS version?), 10 seconds later the charge will time out.

**Comment by danwaters-stripe** [comment]
Thanks for the report. This issue has been fixed in release 1.0.0-b9.
