### ISSUE TITLE
[bug] Contactless transaction failed com.stripe.core.aidIrpc.AidIRpcException: Failed to send request to AIDL server.

### ISSUE THREAD

**Issue by nabilfreeman** [stripe/stripe-terminal-android#505]
## Summary
I have previously posted about this issue on the `stripe-terminal-react-native`  repo: https://github.com/stripe/stripe-terminal-react-native/issues/809

Video: https://www.youtube.com/watch?v=t9nXQoPK6nY

I am quite sure this is a bug at the Stripe SDK level, or even the OS level after many days of testing, debugging and simplifying our implementation of Tap to Pay on Android.

Repeatably on Android, after calling collectPaymentMethod to present the Tap to Pay card reader, the reader screen dismisses and this error in thrown. The full text in the alert body is the entirety of the error message:

Contactless transaction failed com.stripe.core.aidIrpc.AidIRpcException: Failed to send request to AIDL server.

It appears this issue was introduced after updating from targetSdkVersion & compileSdkVersion 33 to 34.

It is still possible to take a contactless payment on Android, so this appears to be intermittent.

My best guess is that this is related to card read errors ("Try again" and loud beep on Android). After two or three of these, the sheet closes and the error is triggered.

In general, it seems that the Android tap to pay reader is very unreliable, and the user has to endure several "Try again" errors before successfully processing the payment. This was the case before updating the targetSdkVersion, so I am not sure if it is related.

## Code to reproduce
Steps to reproduce the behavior are outlined below.

1. Trigger collectPaymentMethod({ paymentIntent })
2. Observe payment sheet appears
3. Tap a payment card in the indicated location
4. Observe either a successful payment (if so, restart the steps here), or a loud beep and "Try again" error
After 2-3 "Try again" errors, observe the payment sheet dismisses and collectPaymentMethod promise rejects with the error message in the issue title.

I have recorded a video of the problem here:

https://www.youtube.com/watch?v=t9nXQoPK6nY

I will make an example application that reliably reproduces the issue, but we need to balance this against some other pressing issues at our startup so I am posting here first in case we can get to a solution faster.

## Android version
14

## Impacted devices (Android devices or readers)
Internal Tap to Pay reader on a Google Pixel 6a, with reader serial number `3f80cfc2-2753-4560-b481-6553b8373326`

## SDK version
3.7.1 (as dictated by `stripe-terminal-react-native` `^0.0.1-beta.21`)

## Other information
I've been in touch with a few people from Stripe today on the developer Discord. Here's the threads:

https://discord.com/channels/841573134531821608/1285245446662393918

https://discord.com/channels/841573134531821608/1285272503220043839

Unfortunately we didn't get to a solution.

The serial number of the device in the video: `3f80cfc2-2753-4560-b481-6553b8373326`

The developer I spoke to was able to locate the errors, but wasn't able to reproduce the issue using a test card.

This has been very difficult to debug for us, because we have limited access to information/telemetry about what is causing the errors, and we need to push a whole new production build through our CI every time we tweak the code.

Currently in production we have a working TTP implementation that is reliable but very slow. This version regresses on the functionality of TTP so we can't ship it, and we also cannot downgrade the library due to the Play Store requiring a minimum `targetSdkVersion` of 34.

Please help!!!

**Comment by dmatthews-stripe** [comment]
We are actively working on this in this ticket: https://github.com/stripe/stripe-terminal-react-native/issues/809

Closing this ticket.
