### ISSUE TITLE
Reader S700 swipe card supported ?

### ISSUE THREAD

**Issue by VijayRathodM** [stripe/stripe-terminal-android#507]

**Comment by xiaoshen-stripe** [comment]
Yes, swipe on the S700 is supported.
Please reference: https://docs.stripe.com/terminal/payments/setup-reader#reader
<img width="846" alt="image" src="https://github.com/user-attachments/assets/7341e547-42ff-4a36-806b-1c78a10d73f3">

As we want to keep Github issues focused on SDK related questions, feel free to  reach out to Stripe support for feature questions going forward.
