### ISSUE TITLE
Docs missing createPaymentIntent example

### ISSUE THREAD

**Issue by jbcullis** [stripe/stripe-terminal-android#51]
In the documentation, the example for createPaymentIntent seems to be missing and goes straight onto retrievePaymentIntent.

**Comment by bg-stripe** [comment]
Hi @jbcullis ! Could you share which docs you're looking at? I think we do have an example for createPaymentIntent, but maybe we're looking in different places:

![image](https://user-images.githubusercontent.com/23086960/60828850-63876880-a168-11e9-977c-ffb2c3d23b16.png)
https://stripe.com/docs/terminal/payments#create-client-android

**Comment by jbcullis** [comment]
Hi @bg-stripe  - on further inspection it's only missing on safari. Not sure if it's something weird on my setup but the other code examples are working. Strange.
Either way, closing the issue as the example is clearly there.

<img width="1296" alt="Screen Shot 2019-07-09 at 12 14 00 AM" src="https://user-images.githubusercontent.com/27532334/60859043-e9de9180-a1de-11e9-8926-1e9ff84e7348.png">
