### ISSUE TITLE
com.stripe.stripeterminal.external.models.TerminalException - ATTESTATION_FAILURE

### ISSUE THREAD

**Issue by dev-innopix** [stripe/stripe-terminal-android#516]
Hi we are facing issues with Stripe Tap to Pay on Android Device, our merchants are facing this error with their sunmi l2s pro devices while trying to connected after discovering. It gives error like ATTESTATION_FAILURE

**Comment by PravinSpaceo** [comment]
I was facing no issues until yesterday, but now I'm encountering the same problem.

 onFailure ATTESTATION_FAILURE (req_1n94********): Unexpected error encountered. Please try clearing the application data in the settings application and contact Stripe support if the issue persists.

**Comment by developerSoluzione1** [comment]
We have an experienced with a Sunmi V2s with no problem, instead with a Zebra we have a problem like yours.
We're using 3.9.0 version.

**Comment by PravinSpaceo** [comment]
I've been using the Tap to Pay feature with NFC technology to enable quick contactless payments, and I'm now encountering this error. My current setup is on version 3.10.1. @[dmatthews-stripe] may help us

**Comment by TatsuUkraine** [comment]
got report about the same error from one of our clients

**Comment by chr-stripe** [comment]
Hello all,

Thanks for writing in. From 21:43 November 13–17:35 November 14 UTC, Android devices were presenting an “ATTESTATION_FAILURE” when a customer used Tap to Pay on a new Android device. The issue has been resolved.

We’re sorry for the trouble this has caused. Please let us know if you have any additional questions.
