### ISSUE TITLE
Testing Tap to Pay with different physical test card

### ISSUE THREAD

**Issue by petitTrung** [stripe/stripe-terminal-android#518]
## Summary
Hello,

I made some Tap-to-Pay tests with the SDK 2.20.0 from this application : https://github.com/stripe-samples/tap-to-pay-android-demo.

I was able to use physical testing cards but since the 3.x version, I cannot figure out how to use my physical testing cards because there is always a button to simulate the payment action.

Could you please tell me if there is any configuration which allow us to use physical testing cards with 3.x version ?

## Android version
Android 11

## Impacted devices (Android devices or readers)
OnePlus 6T/7T

## SDK version
3.1.0

**Comment by devraj** [comment]
@petitTrung not sure if you ever figured this out? I tried to run the app as the `release` variant and it does provide me with the card collection UI. 

At the moment I still can't see the details of the card in `test` mode being captured into the Stripe payment intent.
