### ISSUE TITLE
Persisting connection across andrid app sessions

### ISSUE THREAD

**Issue by Jarrette** [stripe/stripe-terminal-android#52]
How can I make it so the user doesn't have to discover and reconnect to reader after app is restarted?

**Comment by chander-stripe** [comment]
Hi @Jarrette ,

Unfortunately there's not a very clean way of doing this right now with the existing SDK - 
The good news is that the upcoming version (coming in a week-ish or so) will have lifecycle hooks that will do this for you! :)

I'll update this issue when we release the next version, along with updated documentation to do precisely this.

**Comment by Joel-Raju** [comment]
would be great to have it

**Comment by Joel-Raju** [comment]
Can we know when the API will be available ?

**Comment by Joel-Raju** [comment]
okay, sounds good. 👍

**Comment by chander-stripe** [comment]
Hi @Joel-Raju - just letting you know that RC1 has been released, and I'll be shifting my focus to updating the docs to give you an example of how to do this. Thanks for your patience :)

**Comment by Joel-Raju** [comment]
Hi @chander-stripe, could you point me to the link on how to use the persistent connection ?

I've looked at https://stripe.com/docs/terminal/readers/connecting/bbpos-chipper2xbt#discover-readers-android. Its not mentioned there. 

Thanks

**Comment by Joel-Raju** [comment]
Any update on this ?

**Comment by Jarrette** [comment]
Also looking for updates on this, would be a great feature.  Clients are not liking having to reconnect every time the app is closed.

**Comment by chander-stripe** [comment]
One thing that could be done on the app side (instead of in the Stripe SDK) is to, whenever you connect to a reader, store it into SharedPrefs, and when the app relaunches, look up that ID and auto-call `discoverReaders`; if you find that ID, start the connection.

**Comment by chander-stripe** [comment]
We're likely not going to build this into our SDK, as it's something very few users want at this point, and can be done effectively on the application side. We've also updated the docs - https://stripe.com/docs/terminal/readers/connecting#automatic-reconnection
