### ISSUE TITLE
Stripe M2 Reader goes in Autoupdate mode affecting sales

### ISSUE THREAD

**Issue by madinaapps** [stripe/stripe-terminal-android#522]
## Summary

Our Enviornment 
Reader : Stripe M2
Connectivity is Via USB
SDK : com.stripe:stripeterminal:4.0.0
Android Version : 8.5

We have build android app to accept payments using above configuration. We started seeing following issue for last few days. 

Every time we switch Stripe account and connect reader goes in auto update mode. It waits there for 1-2 minutes to finish process and its affecting our sales.

Even after M2 reader is updated then also it goes in auto update mode. 

What can be done to stop this behavior

Hamid

**Comment by CoderzHeaven** [comment]
We are facing the same issue as well.
Reader keeps downloading and installing everytime we switch accounts and gets stuck.

**Comment by bric-stripe** [comment]
Hi, could you provide a serial number and/or two account ids that are getting hit with this?

**Comment by madinaapps** [comment]
STRM26229006154

acct_1CS5GlLcGDKFzSC2 epic.sadaqa
acct_18sbvKEIxcQ1y6BX  epic.operations

**Comment by bric-stripe** [comment]
Thanks for providing that serial and those accounts. We found and fixed a backend issue that was causing this so this should be resolved now. Please let us know if you're still seeing it though.

**Comment by madinaapps** [comment]
was it resolved only for 2 specific accounts are it was resolved in general.

**Comment by bric-stripe** [comment]
It was resolved for all accounts.

**Comment by dmatthews-stripe** [comment]
@madinaapps we are closing this issue as it has been resolved, please feel free to re-open or open a new ticket if you still continue to have issues.

**Comment by CoderzHeaven** [comment]
Hi,
We are having same issues again, Could you please check it ASAP.
Thanks.

**Comment by bric-stripe** [comment]
@CoderzHeaven can you share a reader serial number that is experiencing this? On Nov 10th the latest M2 update became required so all readers should be updating to version `2.01.00.21.SZZZ.01-SZZZ_Prod_US_v10-481001`. If a reader isn't on that version the update would be expected but then when switching accounts it should stay on that version.

**Comment by CoderzHeaven** [comment]
Its the same readers we gave above.

Also there is a new crash happening now

Corrupt proto payload in the queue: terminal_sdk_wire_metrics
java.io.EOFException
	at com.squareup.wire.ProtoReader.internalNextLengthDelimited(ProtoReader.kt:152)
	at com.squareup.wire.ProtoReader.nextTag(ProtoReader.kt:184)
	at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:421)
	at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:286)
	at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:210)
	at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:164)
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:457)
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:455)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:27)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:11)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.populateBatch(QueueFileCollector.kt:245)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.access$populateBatch(QueueFileCollector.kt:26)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:180)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
terminal_sdk_wire_events batch of size 12 generated.
terminal_sdk_wire_traces_2 batch of size 32 generated.
Background concurrent copying GC freed 11MB AllocSpace bytes, 158(7964KB) LOS objects, 49% free, 18MB/37MB, paused 785us,73us total 108.951ms
Input channel destroyed: 'ClientS', fd=199
FATAL EXCEPTION: main
Process: com.madinaapps.madinaappskiosk, PID: 13758
java.lang.NegativeArraySizeException: -1592786944
	at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:549)
	at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:514)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.populateBatch(QueueFileCollector.kt:425)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.access$populateBatch(QueueFileCollector.kt:26)
	at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:180)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(AppScope), StandaloneCoroutine{Cancelling}@a60cbbe, Dispatchers.Main.immediate]
Sending signal. PID: 13758 SIG: 9

**Comment by bric-stripe** [comment]
According to our logs STRM26229006154 hasn't been installing updates in the last week. Are you able to capture adb logcat logs from a run where you're seeing that issue?

please file a new issue for the exception so we can track that separately, including any repro steps or scenarios where you're hitting that if possible.

**Comment by CoderzHeaven** [comment]
What is the reason for the reader not updating? Also why would it crash the app if the reader is not updated?
how can it be captured from dev side?
It crashes all the time Terminal is initialized.
The logs from the adb are pasted above.

**Comment by CoderzHeaven** [comment]
Also the reader is not connecting the the app after it is sitting connected overnight. Its not even proceeding to initialize the Terminal.

**Comment by madinaapps** [comment]
> Its the same readers we gave above.
> 
> Also there is a new crash happening now
> 
> Corrupt proto payload in the queue: terminal_sdk_wire_metrics java.io.EOFException at com.squareup.wire.ProtoReader.internalNextLengthDelimited(ProtoReader.kt:152) at com.squareup.wire.ProtoReader.nextTag(ProtoReader.kt:184) at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:421) at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:286) at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:210) at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:164) at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:457) at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:455) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:27) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:11) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.populateBatch(QueueFileCollector.kt:245) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.access$populateBatch(QueueFileCollector.kt:26) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:180) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012) terminal_sdk_wire_events batch of size 12 generated. terminal_sdk_wire_traces_2 batch of size 32 generated. Background concurrent copying GC freed 11MB AllocSpace bytes, 158(7964KB) LOS objects, 49% free, 18MB/37MB, paused 785us,73us total 108.951ms Input channel destroyed: 'ClientS', fd=199 FATAL EXCEPTION: main Process: com.madinaapps.madinaappskiosk, PID: 13758 java.lang.NegativeArraySizeException: -1592786944 at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:549) at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:514) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.populateBatch(QueueFileCollector.kt:425) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.access$populateBatch(QueueFileCollector.kt:26) at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:180) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(AppScope), StandaloneCoroutine{Cancelling}@a60cbbe, Dispatchers.Main.immediate] Sending signal. PID: 13758 SIG: 9

Any updates on this crash ?

**Comment by bperez-stripe** [comment]
Hi @madinaapps . Can you try clearing the app's cache and storage to see if resolves the crash you are seeing on the one device?

In regards to updates, firmware updates are made on an as needed basis as mentioned in our docs [here](https://docs.stripe.com/terminal/mobile-readers#reader-software-updates). Firmware updates are typically optional for several days before they become required in order for you to evaluate on a small number of devices before they are more widely deployed. Readers power cycle every 24 hours to check for updates and you can leverage rebootReader call to make sure those every 24 hour power cycles occur during the most convenient time for your specific needs.

**Comment by CoderzHeaven** [comment]
Clearing the cache is not working.

**Comment by bperez-stripe** [comment]
@CoderzHeaven was app storage cleared as well? I'm specifically referring to the device with the java.io.EOFException.

**Comment by dmatthews-stripe** [comment]
@CoderzHeaven this issue is closed, if you continue to experience the issue any further please log a new issue.
