### ISSUE TITLE
Is there a way to check if Terminal object has been initialized ?

### ISSUE THREAD

**Issue by Joel-Raju** [stripe/stripe-terminal-android#54]
Is there a way to check if the `Terminal` object has been initialized before invoking the `Terminal.initTerminal()`, which throws an exception if already initialized?

I'm currently using the `Terminal.getInstance()` method which also throws an exception if it has not been initialized.

**Comment by chander-stripe** [comment]
Not an elegant way right now, no - our example app does the following:

```kotlin
    /**
     * A version of initialize that is safe to call multiple times, and can be called
     * even if the Terminal has been initialized previously
     */
    private fun safeInitialize() {
        try {
            Terminal.getInstance()
            // Terminal has already been initialized, ignore...
        } catch (e: IllegalStateException) {
            // Terminal has not been initialized, so do so now
            initialize()
        }
    }
```

**Comment by Joel-Raju** [comment]
@chander-stripe this is what I've been doing, but I think it is better to have an API to check it rather than doing the plumbing

**Comment by chander-stripe** [comment]
@danwaters-stripe has recently merged a patch to expose an `isInitialized` property that exposes whether or not `initialize()` should be called. This will be available in the next release.

**Comment by chander-stripe** [comment]
Hi - we decided to punt on a b10 / b11 release and instead move towards general availability. The next release will be RC1 , where this new API will be present (hence the delay). Thanks for your patience!

**Comment by chander-stripe** [comment]
@rscherf & @Joel-Raju  - we just released RC1 which now has this API (see the changelog). Closing the issue now - thanks for your patience!!
