### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by jrsadik7** [stripe/stripe-terminal-android#55]
getting manifest merge error after the library added.

implementation "com.stripe:stripeterminal:1.0.0-b9"

**Comment by jrsadik7** [comment]
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.30.0'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    google()
    mavenCentral()
    jcenter()
    maven { url "https://jitpack.io" }
}
apply from: 'dependencies.gradle'
android {
    compileSdkVersion 28

    defaultConfig {
        applicationId ""
        minSdkVersion 18
        targetSdkVersion 28
        versionCode 4
        versionName ""
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    flavorDimensions "dev"

    androidExtensions {
        experimental = true
    }

    dataBinding {
        enabled = true
    }

    productFlavors {
        dev {
                   }

        production {
                   }

        devGooglePayDisabled {
                   }

        productionGooglePayDisabled {
                    }
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    // for running in emulator
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }

    useLibrary 'org.apache.http.legacy'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':pk-library')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

//    implementation supportLibs
//    implementation networkLibs
//    implementation rxJavaLibs
//    implementation googlePlayLibs
//    implementation misc

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
//    debugImplementation debugLibs
//    releaseImplementation releaseLibs

    // APT dependencies
//    kapt annotationProcessorLibs
//    kaptTest daggerCompiler
//    kaptAndroidTest daggerCompiler

    testImplementation unitTestLibs
    androidTestImplementation androidTestsLibs

    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
    implementation('org.apache.httpcomponents:httpmime:4.3') {
        exclude module: "httpclient"
    }

    implementation('com.crashlytics.sdk.android:crashlytics:2.9.0@aar') {
        transitive = true
    }

    implementation 'com.github.BlackBoxVision:material-wheel-view:v0.0.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'

    implementation 'cn.aigestudio.wheelpicker:WheelPicker:1.1.2'


//    androidX supportLibs
//    implementation "com.android.support:appcompat-v7:$versions.support"
    implementation "androidx.appcompat:appcompat:1.0.2"

//    implementation "com.android.support:design:$versions.support"
    implementation "com.google.android.material:material:1.1.0-alpha09"

//    implementation "com.android.support:design:$versions.support"
    implementation "com.google.android.material:material:1.1.0-alpha09"

//    implementation "com.android.support:cardview-v7:$versions.support"
    implementation "androidx.cardview:cardview:1.0.0"

//    implementation "com.android.support:support-annotations:$versions.support"
    implementation "androidx.annotation:annotation:1.1.0"


    implementation "com.android.support:support-vector-drawable:$versions.support"
    implementation "androidx.vectordrawable:vectordrawable:1.0.1"

//    implementation "com.android.support:animated-vector-drawable:$versions.support"
    implementation "androidx.vectordrawable:vectordrawable-animated:1.0.0"


    //retrofit
    implementation "com.squareup.retrofit2:retrofit:2.5.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.4.0"
    implementation "com.squareup.retrofit2:converter-gson:2.5.0"

    //okhttp
    implementation "com.squareup.okhttp3:logging-interceptor:3.11.0"
    implementation "com.squareup.okhttp3:okhttp:3.12.0"

    //rxJavaLibs
    implementation "io.reactivex.rxjava2:rxkotlin:2.1.0"
    implementation "io.reactivex.rxjava2:rxandroid:2.1.0"
    implementation "com.tspoon.traceur:traceur:1.0.1"
    implementation "com.tbruyelle.rxpermissions:rxpermissions:0.9.4"


    //googlePlay
    implementation "com.google.firebase:firebase-appindexing:19.0.0"
    implementation "com.google.android.gms:play-services-places:17.0.0"
    implementation "com.google.android.gms:play-services-wallet:17.0.0"


    //misc
    implementation "androidx.multidex:multidex:2.0.1"
    implementation "com.google.code.gson:gson:2.8.5"
    implementation "com.jakewharton.timber:timber:4.7.1"
//    implementation "com.jakewharton:butterknife:8.6.0"
    implementation "com.google.dagger:dagger:2.17"
    implementation "com.github.bumptech.glide:glide:4.8.0"
    implementation "com.tspoon.traceur:traceur:1.0.1"
//    implementation "org.parceler:parceler-api:1.1.11"
    implementation "io.card:android-sdk:5.5.1"
    implementation "com.stripe:stripe-android:8.1.0"
    implementation "me.dm7.barcodescanner:zxing:1.8.4"
    implementation "com.nulab-inc:zxcvbn:1.2.2"
    implementation "com.github.kenglxn.QRGen:android:2.4.0"


//     Stripe Java library
    implementation "com.stripe:stripe-java:7.1.0"
//
//     Stripe Terminal library
    implementation "com.stripe:stripeterminal:1.0.0-b9"


    //debug
    debugImplementation "com.readystatesoftware.chuck:library:1.0.4"
    debugImplementation "com.squareup.leakcanary:leakcanary-android:1.5.1"


    //release
    releaseImplementation "com.readystatesoftware.chuck:library-no-op:1.0.4"
    releaseImplementation "com.github.ajitsing:sherlock-no-op:1.0.3@aar"

    //annotationProccessorlibs

//    kapt "org.parceler:parceler:1.1.9"
    kapt "com.google.dagger:dagger-compiler:2.16"

//    kaptTest "org.parceler:parceler:1.1.9"
    kaptTest "com.google.dagger:dagger-compiler:2.16"
    kaptAndroidTest "com.google.dagger:dagger-compiler:2.16"
}
`

**Comment by jrsadik7** [comment]
i have posted build.gradle file

**Comment by chander-stripe** [comment]
@jrsadik7 can you post the full error, or is it just that one line?

**Comment by jrsadik7** [comment]
it is just one line

**Comment by chander-stripe** [comment]
Hi @jrsadik7  - @danwaters-stripe just released the latest release candidate, and this update has both a Java and Kotlin version. Could you try updating to the latest version and seeing if this issue persists?

**Comment by chander-stripe** [comment]
Closing for now, please file a new issue if this persists on the new RC1 library. Thanks!

**Comment by Monika-Paliwal** [comment]
@jrsadik7 I am facing issue when I add the proguard rules for stripe but it does not support the rules, Please update any idea.
