### ISSUE TITLE
okhttp3 conflict with React Native

### ISSUE THREAD

**Issue by ollym** [stripe/stripe-terminal-android#61]
The version of okhttp3 being required by Stripe is `4.1.0` but react native only supports `3.12.1` - this has caused a crash in our application.

We're trying to circumvent this by overriding the version of okhttp in react native but will use this issue to track our progress, any thoughts you can provide would be helpful.

Thanks

**Comment by ollym** [comment]
Hi Chander, we tried a few things like upgrading okhttp to the latest 4.x version but still no luck. Have you come to any conclusions internally? We need to know if Stripe plans to support React Native officially or not, and if not we'll have to figure out an alternative (if there is one). Thanks

**Comment by chander-stripe** [comment]
@ollym I think we're going to try and release a shadowjar version of okhttp which _could_ theoretically solve your problem - give us some time to try and release that.

> We need to know if Stripe plans to support React Native officially or not

There are no official plans to support React Native, but we definitely don't want to break RN users' experience either.

**Comment by ollym** [comment]
Thanks @chander-stripe if you have a version you'd like us to test please let me know.

**Comment by chander-stripe** [comment]
For those following along on this issue, we’ve provided a React Native compatible version of the build to @ollym to test, and if it works well, we will release in RC2 for all users. Thanks for reporting these issues!

**Comment by Joel-Raju** [comment]
Hi @chander-stripe, could you publish the react native compatible version to Maven ? I'd also like to try it out.

Thanks

**Comment by chander-stripe** [comment]
Hi @Joel-Raju , we're trying to avoid having these less tested version out on Maven, since they live forever there, and folks sometimes accidentally use older versions which creates unnecessary tickets and hassles.

So for now we're going to just partner with @ollym to test, but we will definitely fast follow with RC2 relatively quickly, where you can test as well!

Thanks for your patience! (And for offering to test 😄)

**Comment by danwaters-stripe** [comment]
We just released version 1.0.0-rc2 that should fix this problem. Try it out and let us know how it goes!

**Comment by jakubkarlicek** [comment]
Hey, tested and works fine. Thanks
