### ISSUE TITLE
Reader software update not calling callback

### ISSUE THREAD

**Issue by ball1008** [stripe/stripe-terminal-android#62]
We use the below code to update readers.  The update occurs successfully but the callback is never called.

Terminal.getInstance().installUpdate(softwareUpdate, TerminalAdapter.this, new Callback() {
                                @Override
                                public void onSuccess() {
                                    view.setEnabled(true);
                                    selectedHolder.updateProgressBar.setVisibility(View.GONE);
                                    Log.e("FoodMood:Stripe", "ManageTabletFragment:updateButtonListener-> installed update ");
                                }

                                @Override
                                public void onFailure(@NotNull TerminalException e) {
                                    view.setEnabled(true);
                                    selectedHolder.updateProgressBar.setVisibility(View.GONE);
                                    Log.e("FoodMood:Stripe", "ManageTabletFragment:updateButtonListener-> Error installing update " + e.getErrorMessage());
                                }
                            });

**Comment by danwaters-stripe** [comment]
I think the issue might be that you need to put your UI logic into a `runOnUiThread` call in order for it to be run the way you expect. Try doing this and see if that helps:

```
Terminal.getInstance().installUpdate(softwareUpdate, TerminalAdapter.this, new Callback() {
    @Override
    public void onSuccess() {
        activity.runOnUiThread(() -> {
            view.setEnabled(true);
            selectedHolder.updateProgressBar.setVisibility(View.GONE);
            Log.e("FoodMood:Stripe", "ManageTabletFragment:updateButtonListener-> installed update ");
        }
    }

    @Override
    public void onFailure(@NotNull TerminalException e) {
        activity.runOnUiThread(() -> {
            view.setEnabled(true);
            selectedHolder.updateProgressBar.setVisibility(View.GONE);
            Log.e("FoodMood:Stripe", "ManageTabletFragment:updateButtonListener-> Error installing update " + e.getErrorMessage());
        }
    }
});
```

**Comment by ball1008** [comment]
The recommended changes worked.  Thanks.
