### ISSUE TITLE
Battery Percentage During Discover

### ISSUE THREAD

**Issue by satishru** [stripe/stripe-terminal-android#63]
Is there any way to get battery percentage after discovery?.
I am able get it after connecting to reader, but I need battery percentage after discovery also.

**Comment by chander-stripe** [comment]
Oh interesting! That's a use case we hadn't thought of. I don't _think_ there is a way right now (let me double check and get back to you), but we could put it on our roadmap if there isn't.

**Comment by satishru** [comment]
Please check and confirm

**Comment by chander-stripe** [comment]
Yeah - confirmed. Battery information and all other reader information is only available once we have connected to a reader, not before.

**Comment by chander-stripe** [comment]
Going to close this issue for now until we have a meaningful path forward to be able to support this.
