### ISSUE TITLE
Location not updating once connected

### ISSUE THREAD

**Issue by ball1008** [stripe/stripe-terminal-android#66]
The dashboard states "Mobile readers like the BBPOS Chipper 2X BT will show up in this section after you connect to them for the first time."  I have connected to my BBPOS reader successfully but nothing shows in the dashboard.

**Comment by chander-stripe** [comment]
Closing out this stale issue. If you have any issues, I'd recommend reaching out to the Stripe technical support staff, as issues are really meant for bugs with the SDK and not as a general debugging forum.
