### ISSUE TITLE
Tapping the card to do the payment doesn't work. Insert and swipe works.

### ISSUE THREAD

**Issue by Joel-Raju** [stripe/stripe-terminal-android#74]
## Summary
Tapping the card to do the payment doesn't work, the BBPOS doesn't detect the tap. Insert and swipe works. 

## Code to reproduce
    Terminal.getInstance().collectPaymentMethod(paymentIntent,
    new ReaderDisplayListener() {
        @Override
        public void onRequestReaderInput(ReaderInputOptions options) {
        }

        @Override
        public void onRequestReaderDisplayMessage(ReaderDisplayMessage message) {
        }
    },
    new PaymentIntentCallback() {
        @Override
        public void onSuccess(PaymentIntent paymentIntent) {
            processPayment(paymentIntent, promise);
        }

        @Override
        public void onFailure(TerminalException exception) {
            exception.printStackTrace();
        }
    });

## Android version
Android 5.1

## Impacted devices (Android devices or readers)
BBPOS Reader and Android devices running 5.1.1 to 9

## SDK version
Version 1.0.0

## Other information
It also doesn't work on Android 9.0

**Comment by danwaters-stripe** [comment]
Hi Joel,

Is this behavior seen after you call `readReusableCard`? If so, we don't support tap for that method. However, it's fully supported for `collectPaymentMethod`, which is likely what you want to be using if you're making payments at the time of purchase. For more info, see here: https://stripe.com/docs/terminal/payments/saving-cards#saving-cards-for-online-payments

**Comment by Joel-Raju** [comment]
Hey Dan, its happening with the `collectPaymentMethod`. I've updated the the issue with the code snippet.

Thanks

**Comment by Joel-Raju** [comment]
Hi @chander-stripe, the insert seems to be working now, but its taking longer to detect. Earlier it used to take around 2-3 sec now it takes around 6 sec.

Here is the stack dump 

```10-28 18:10:56.542 D/StripeTerminal(  911): class=LogFlusher message="Reporting traces" num_traces=3
10-28 18:10:57.773 D/StripeTerminal(  911): class=LogFlusher message="Sent 3 traces"
10-28 18:10:57.773 D/StripeTerminal(  911): class=LogFlusher message="Reporting events" num_events=3
10-28 18:10:57.824 D/StripeTerminal(  911): class=LogFlusher message="Sent 3 events"
10-28 18:11:15.641 D/StripeTerminal(  911): class=Terminal message=createPaymentIntent
10-28 18:11:15.651 D/StripeTerminal(  911): class=ApiClient message=createPaymentIntent
10-28 18:11:15.891 I/StripeTerminal(  911): class=ApiClient api_request_id=req_21pLkdyxyyDntX
10-28 18:11:16.041 D/StripeTerminal(  911): class=Terminal message=collectPaymentMethod
10-28 18:11:16.041 D/StripeTerminal(  911): class=TerminalListenerProxy message=onPaymentStatusChange(WAITING_FOR_INPUT)
10-28 18:11:16.041 D/StripeTerminal(  911): class=BbposBluetoothAdapter message=collectPaymentMethod
10-28 18:11:16.041 D/StripeTerminal(  911): class=BbposDeviceController message=startEmv
10-28 18:11:17.062 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onRequestDisplayText(PRESENT_CARD)
10-28 18:11:17.423 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onWaitingForCard(SWIPE_OR_INSERT_OR_TAP)
10-28 18:11:18.123 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onRequestDisplayText(REMOVE_CARD)
10-28 18:11:18.464 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onRequestDisplayText(AUTHORISING)
10-28 18:11:26.612 D/StripeTerminal(  911): class=BbposDeviceControllerListener message="onRequestOnlineProcess([String length 1602])"
10-28 18:11:26.622 D/StripeTerminal(  911): class=BbposDeviceController message=sendOnlineProcessResult
10-28 18:11:26.622 D/StripeTerminal(  911): class=Terminal message=processPayment
10-28 18:11:26.622 D/StripeTerminal(  911): class=TerminalListenerProxy message=onPaymentStatusChange(PROCESSING)
10-28 18:11:26.632 D/StripeTerminal(  911): class=ApiClient message=processPayment
10-28 18:11:27.412 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onRequestDisplayText(DECLINED)
10-28 18:11:28.123 I/StripeTerminal(  911): class=ApiClient api_request_id=req_Ha0bWv7Fw3KEfq
10-28 18:11:28.153 D/StripeTerminal(  911): class=TerminalListenerProxy message=onPaymentStatusChange(READY)
10-28 18:11:38.854 D/StripeTerminal(  911): class=BbposDeviceControllerListener message="onReturnBatchData([String length 1610])"
10-28 18:11:39.244 D/StripeTerminal(  911): class=BbposDeviceControllerListener message=onReturnTransactionResult(DECLINED)
```

**Comment by chris-oswald** [comment]
I'd like to piggy back on this.  I'm on Android 7.1 and I'm using the latest version of the terminal SDK.  When I "dip" a card backwards (chip not in), it tells me to try another read method.  When I do that "Tapping" no longer works until I cancel and start again.  It's very consistent and easily reproducible.  Can you shed any light on why the tap method stops working?

**Comment by chander-stripe** [comment]
@chris-oswald are you able to replicate this issue with the example apps?

**Comment by chris-oswald** [comment]
Fair point, I'll deploy your test app this weekend and see what happens.

Thanks,
Chris

**Comment by chris-oswald** [comment]
Ok, I upgraded from 1.0.1 to 1.0.8 and whatever has happened between those versions seems to have addressed the issues.  I'm good to go!  Sorry for any trouble!

**Comment by chander-stripe** [comment]
Glad to hear it!
