### ISSUE TITLE
Android-gradle can't be build using android studio on Ubuntu 18.04

### ISSUE THREAD

**Issue by ganesh-trabacus** [stripe/stripe-terminal-android#75]
I tried building Examples from repo, as java-app but it's having issues while gradle building, if you have apk file is then please share it as apk, to download directly, so no need to build gradle everytime when we try to use demo.
thank you.

**Comment by danwaters-stripe** [comment]
Hi, can you let us know what error you're seeing when you attempt to build with gradle?

**Comment by ganesh-trabacus** [comment]
@danwaters-stripe, thanks for quick reply.
I upgraded gradle and managed to build apk and install on virtual device, but app "Terminal" starts and automatically closes.

[
![Screenshot from 2019-10-30 23-45-46](https://user-images.githubusercontent.com/54972604/67886607-bea5f680-fb6f-11e9-8aca-604fac6c3855.png)
](url)

and my project structure is this...
![Screenshot from 2019-10-30 23-46-14](https://user-images.githubusercontent.com/54972604/67886639-cd8ca900-fb6f-11e9-9281-e1c89000f4df.png)

I saw all files and sdk path is correct, but app is not bundled properly, 

do you have build-up apk to share?

**Comment by chander-stripe** [comment]
Hi @ganesh-trabacus  - can you re-launch the app and paste the full Logcat stack trace?

**Comment by ganesh-trabacus** [comment]
@chander-stripe , thanks for telling LogCat stack trace, I didn't check logs before, but after checking it, it showed error of backend url was missing.

I created python demo-server as localhost and gave it's url to android app in ApiClient.java and it worked.

thanks @Stripe-Team.
