### ISSUE TITLE
Localization of ReaderInputOptions

### ISSUE THREAD

**Issue by edmond-c** [stripe/stripe-terminal-android#76]
## Summary

The `onRequestReaderInput` callback is called with `ReaderInputOptions`. The class only has one public method `toString()`, which is not localized.

Since the options class represents a set of available options, i.e. tap, chip, swipe. A simple equality comparison is insufficient.

A lack of primitive representation also limits options for deferring localization to a hybrid app.

In contrast, `ReaderInputOptions` in the iOS SDK extends from `OptionSet`, with methods like `contains:` for quick check and `rawValue` for raw bit manipulations.

Appreciate all the hard work from your team! Everything else works beautifully. Thank you

## Code to reproduce

N/A

## Android version

All

## Impacted devices (Android devices or readers)

All

## SDK version

1.0.0-rc2

## Other information

https://stripe.dev/stripe-terminal-android/com/stripe/stripeterminal/callable/ReaderDisplayListener.html#onRequestReaderInput-options-
https://stripe.dev/stripe-terminal-android/com/stripe/stripeterminal/model/external/ReaderInputOptions.html
https://stripe.com/docs/terminal/payments#collect-handling-events
https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPReaderInputOptions.html
https://developer.apple.com/documentation/swift/optionset

**Comment by rv-stripe** [comment]
I believe this is no longer an issue in newer versions of the project.
Closing this older issue out. Please re-open if you still have issues.
