### ISSUE TITLE
[Help needed, not issue-with-app] How to automate whole terminal-android-payment process, without manually clicking buttons to select device from list and click collect-payment button

### ISSUE THREAD

**Issue by ganesh-trabacus** [stripe/stripe-terminal-android#78]
Hello Stripe-Team, first thanks for Example-demo-app.

I am using it for testing after I solved backend url-pathfixing error of `slash(/)` , 

Your example app is great but I need to automate it's process from start-to-end,

My device is BBPOS 2x Chipper(without display), 

Current stripe app is having few steps to do card/swipe payment, as follows,

1) open app, click button -> discover readers,

2) Discover readers -> it shows list of devices,

3) select any device, 

4) selected device will connected.

5) click btn-> Collect card payment

6) enter amount, 

7) click btn-> Collect payment-> 

8) then It will start/wait/accept card, by swipe/tap/insert.

Now, 
How I wanted to implement is:

1) open app, it will discover all devices(in background), 

2) select first device(index=0) automatically, 

3) connect to first device(automatically), 

4) enter amount(which I will pass from my server, dynamically, using intent, app="https", not from android-app, but only from server), 

5) autoclick after I pass amount from backend only, 

6) then click automatically button -> collect payment.

Currenly, I have automated some clicks from stackoverflow-help, as here also I have changed fragments id and skipped payment page and amount-entering page, 

but I only wanted to automate all steps, such that It will only use android-app to connect to hardware device and all will be automated, 
and it will fetch data from server through indent-filter,( by passing schema=http, app=myApp, data=params needed)

If have experience in Android-then tell me how to do it, though I have figured it out most part by myself.

**Comment by ganesh-trabacus** [comment]
my stackoverflow question(solved partially) https://stackoverflow.com/questions/58767446/how-to-call-activity-directly-without-clicking-button/58767501?noredirect=1#comment103821787_58767501

**Comment by danwaters-stripe** [comment]
I would recommend using our example app as guidance to create an app that will do what you want. Automating clicks will probably get you some unexpected behavior, and probably won't map exactly to the flow that you want. Feel free to use https://support.stripe.com/ or email support-terminal@stripe.com for more help!

**Comment by ganesh-trabacus** [comment]
Thanks @danwaters-stripe , for reply.
I will refer your main-demo-app, to customize my-app.

Automating clicks will be be good-practice, then what do you suggest to?

I tried asking on StackOverflow [here](https://stackoverflow.com/questions/58825901/how-to-click-button-inside-methon-adapter-in-recyclerview)

please have a look, if possible. :)
