### ISSUE TITLE
Java example will not build using Gradle 3.5.3, cannot generate view binders java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sgehrman** [stripe/stripe-terminal-android#81]
Android studio gave me this message:

To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin from the current version 3.5.0 to version 3.5.3 and Gradle to version 5.4.1. Release notes

It doesn't build if you upgrade.  

"cannot generate view binders java.lang.StackOverflowError"

**Comment by chander-stripe** [comment]
Hi - I've since fixed this ; can you try building with version 1.0.2 and letting me know if you still get this issue? I've reverted the problematic view binders.
