### ISSUE TITLE
StripeTerminal: READER_ERROR.BLUETOOTH_DISCONNECTED: Bluetooth unexpectedly disconnected during operation

### ISSUE THREAD

**Issue by anton8900** [stripe/stripe-terminal-android#83]
Still the same issue https://github.com/stripe/stripe-terminal-android/issues/70

device serial: CHB204902001016
used last example
library version 1.0.1
to make example work i just used secret = "pst_test_2FcW9n5NnF293zD77***************"
it always fails with this error during connecting the device and then jump back to the first fragment

12-12 14:48:14.630 30640-30693/com.stripe.example.javaapp E/StripeTerminal: READER_ERROR.BLUETOOTH_DISCONNECTED: Bluetooth unexpectedly disconnected during operation.
com.stripe.stripeterminal.model.external.TerminalException
at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.onDisconnectReader(BbposBluetoothAdapter.kt:229)
at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onBTDisconnected(BbposDeviceControllerListener.kt:93)
at com.stripe.bbpos.bbdevice.BBDeviceController$aaa042zz.run(SourceFile:1)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5637)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by anton8900** [comment]
Looks like it don't work only with the phone: Land Rover X8
With beta version of your library and this phone all works
If you need more logs i'll send

**Comment by chander-stripe** [comment]
@anton8900 - what was the beta version of the library you used when it worked? And was it the same phone on both beta and 1.0.1 versions? Trying to get a sense of the total diff between your last working version and this one. Thanks.

**Comment by anton8900** [comment]
So with version 1.0.0-b9 it works, but with rc1 already don't

**Comment by anton8900** [comment]
The phone the same, if i downgrade to b9 it starts to work, but with rc1 and higher connecting to the reader fails with that error

**Comment by legomanaustralia** [comment]
Hi @chander-stripe confirming here it does appear to work on **some** devices but not others.

When we were using the initial b9 version it was working on all devices.

Now the RC-1 only works on a subset of the devices we've been testing on (we've tried the 1.0.0 and the 1.0.1 and see the same result of partial success across the number of devices we're testing).

If it helps we're able to see the devices in the list of devices we wish to connect to but are unfortunately able to actually connect. We've also tried a number of the stripe terminals to ensure it wasn't a bad unit but we're seeing it on all of the half dozen we've tested on, some being test units and some being production units (i.e purchased from stripe admin).

Is there potential for us to nominate stripe account_ids that can use the older version of the beta in production until this is resolved?

**Comment by legomanaustralia** [comment]
Did some further testing with this today and it seems like an issue when the reader isn't in pairing mode properly, hard reseting the reader using the reset seems to make it start working again. Will continue to mess around with them and see if we can figure it out.

**Comment by anton8900** [comment]
So Land Rover X8 running android 5.1
Looks like that is the issue
So we suggest that library started to work incorrectly with old android phones because you started to use BLE exclusively

**Comment by legomanaustralia** [comment]
@chander-stripe confirming we had a really big issue with this at our last trial, constant dropouts and disconnections.

It appears as tho the BLE implementation is really unstable on older android 6 devices, to double check we fell back to the b7 and it appears to work without the same disconnection issues. Almost like the stripe library has a connection issue then has to go through the entire re-pairing process or in some cases be turned off and restarted in order for it to function again.

**Comment by legomanaustralia** [comment]
Still seeing this on 1.0.8 although it now throws this on every single payment. The initial connection step does seem more solid tho.

**Comment by chander-stripe** [comment]
@legomanaustralia are you trying to pair from the system bluetooth menu or from within the app?

**Comment by chander-stripe** [comment]
Also, are you getting this error from the sample apps?

**Comment by legomanaustralia** [comment]
1. Pairing within the application 
2. Yep it also happens in the sample application - appears to be linked to the lower OS version and BLE only in the RC versions

**Comment by chander-stripe** [comment]
Thanks for the quick response - what's the first api version that you're seeing this behavior in? 23 (6.0) ?

**Comment by chander-stripe** [comment]
The rc1 was the first version we switched to BLE over BT, so I'm wondering if it's just bad BLE connectivity on older android devices. I'll order both an Android 5 and Android 6 device to test, thanks.

**Comment by chander-stripe** [comment]
For internal reasons we've been forced to bump our min sdk (going forward) to API level 24, so all future releases of the sdk will target those builds.

I've also been able to repro (not 100% of the time) the issue here, and it looks like an issue from one of our third party libraries. They've released a newer version of their SDK which our newer library versions are using, but again that targets api level 24.

Apologies for the delay here.
