### ISSUE TITLE
Error building the Example app in Android Studio 3.5.3

### ISSUE THREAD

**Issue by jorge-acosta-abstracta** [stripe/stripe-terminal-android#90]
OS: macOS Catalina 10.15.3 (19D76)
Android Studio: 3.5.3

We've imported the Example project, after the project is imported Gradle Project Sync Failed. 

Reason: Could not find method buildFeatures().

File: javapp/build.gradle

Line:

    buildFeatures {
        dataBinding = true
    }

Log: 

ERROR: Could not find method buildFeatures() for arguments [build_8s3vbh1b09i8m78pb47rlm49y$_run_closure1$_closure5@d18ba6e] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

**Comment by chander-stripe** [comment]
@jorge-acosta-abstracta it depends on which version of Android Studio (and gradle) you're using. The above syntax is used for the newer versions of gradle (Android Studio 4.0 canary and above)

If you're using 3.5.3, please use the following:

```gradle
dataBinding {
    enabled = true
}
```

Let me know if this works

**Comment by jorge-acosta-abstracta** [comment]
Dear Chander, 

I'm leaving this note so others can read that this solution worked perfectly.

Thank you so much for your quick help !

**Comment by chander-stripe** [comment]
Glad to hear it! I'll add some documentation letting folks know in the README to change the gradle file depending on which version of Android Studio they're using.
