### ISSUE TITLE
Reader discovery only works once

### ISSUE THREAD

**Issue by raphaelm** [stripe/stripe-terminal-android#94]
## Summary
Our app has an activity that calls ``discoverReaders`` to show users a list of nearby readers. If the user selects a reader and connects, everything works fine.

However, if the user exists the activity without selecting a reader and then tries again later, nothing will happen, neither ``onUpdateDiscoveredReaders``, nor ``onSuccess``, nor ``onFailure`` is called and no error message in the logs. ``discoverReaders`` will only work again after an app restart, or a successful connect+disconnect (which is impossible at this point since the user can't select a reader).

## Android version
Android 9

## Impacted devices (Android devices or readers)
BBPOS Chipper 2X

## SDK version
1.0.8

**Comment by danwaters-stripe** [comment]
Hi Raphael,

Are you calling `cancel()` on your discover readers `Cancelable` when the activity is exited? If you don't do that, the discover readers operation will continue running in the background, which will prevent you from doing anything else with your `Terminal` instance.

**Comment by raphaelm** [comment]
Yep, this seems to be the case :) Feel free to close this, or move it to a documentation issue, since it would be very great if the documentation would mention it. The examples on https://stripe.com/docs/terminal/readers/connecting/bbpos-chipper2xbt#discover-readers-android don't even suggest that the function returns a cancelable.

**Comment by chander-stripe** [comment]
Thanks for the feedback; I'll update the docs accordingly.

**Comment by chander-stripe** [comment]
@raphaelm we've updated our documentation accordingly - https://stripe.com/docs/terminal/readers/connecting/bbpos-chipper2xbt .

**Comment by billfinn-stripe** [comment]
@atrauzzi -- when discovering Bluetooth readers, the discovery process continues indefinitely until/unless a timeout is reached, the operation is canceled, or the integration connects to a reader.
