### ISSUE TITLE
ERROR: Could not find method buildFeatures() for arguments [build_5kx9rly54z3f8v5sm60daa14c$_run_closure1$_closure5@51dace3d] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

### ISSUE THREAD

**Issue by Harvinkour** [stripe/stripe-terminal-android#97]

**Comment by chander-stripe** [comment]
@Harvinkour please fill out the sections of the issue template; otherwise it's very difficult for us to understand what's going on.

**Comment by singhvijay9757** [comment]
I am also getting the same issue when added 
 buildFeatures {
        viewBinding = true
    }
My gradle version is 5.6.4
